<?php

/**
 * This Software is the property of Data Development and is protected
 * by copyright law - it is NOT Freeware.
 *
 * Any unauthorized use of this software without a valid license
 * is a violation of the license agreement and will be prosecuted by
 * civil and criminal law.
 *
 * http://www.shopmodule.com
 *
 * @copyright (C) D3 Data Development (Inh. Thomas Dartsch)
 * @author    D3 Data Development - Daniel Seifert <support@shopmodule.com>
 * @link      http://www.oxidmodule.com
 */

$sLangName = "English";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(

//Navigation
    'charset'                                         => 'UTF-8',
    'd3mxextsearch'                                   => '<i class="fa fa-fw fa-search-plus"></i> Extended Search',
    'd3mxextsearch_settings'                          => 'Settings',
    'd3mxextsearch_statistic'                         => 'Statistic',
    'd3mxextsearch_syneditor'                         => 'Synonym Editor',
    'd3tbclextsearch_syneditor_main'                  => 'Main',
    'd3tbclextsearch_syneditor_manage'                => 'Edit synonyms',
    'd3tbclextsearch_syneditor_family'                => 'Synonym family',
    'd3tbclextsearch_syneditor_synset'                => 'Edit synonym group',
    'd3tbclextsearch_settings_results'                => 'Base Settings',
    'd3tbclextsearch_settings_navigation'             => 'Filters + Display Settings',
    'd3tbclextsearch_settings_quick'                  => 'Suggest Search',
    'd3tbclextsearch_settings_browser'                => 'Browser Plugins',
    'd3tbclextsearch_settings_content'                => 'Content Search',
    'd3tbclextsearch_settings_statistik'              => 'Statistic',

    'D3_EXTSEARCH_LIST_SETTLANG'                      => 'settings for language',
    'D3_EXTSEARCH_HELPLINK'                           => 'Fragen-zu-speziellen-Modulen/Erweiterte-Suche/',
    'D3_EXTSEARCH_HELPLINK_CONFIG'                    => '',

    'D3_EXTSEARCH_TRANSL'                             => 'Extended Search',

    'D3_EXTSEARCH_CONFIGVARS_SADDTITLE'               => 'module edition:',
    'D3_EXTSEARCH_CONFIGVARS_BLUSEFILTERINARTICLELISTS' => 'filters in article lists available:',
    'D3_EXTSEARCH_CONFIGVARS_FEATUREBIT1'             => 'filters in article lists available:',

    'D3_EXTSEARCH_MAIN_DEBUGACTIVE_DESC'              => 'In debug mode, the used database queries are displayed in the browser console and FirePHP console for easier programming and troubleshooting (Ajax requests can only be issued in FirePHP for technical reasons.). To view the queries, please install the FirePHP add-on for your browser. Alternatively, use the GET parameter "d3forcedebug=1" on the Ajax request for forced debug output. Please deactivate the debug mode for live operation, as database caching is not used with activated debug mode.',
    'D3_EXTSEARCH_MAIN_MAINSETTINGS'                  => 'Common Settings',
    'D3_EXTSEARCH_MAIN_FIELDLIST'                     => 'these fields will used in similar and quicksearch<br>relevance => field name (example.: 50 => oxtitle)',
    'D3_EXTSEARCH_MAIN_SORTDEBUG'                     => 'result field analysis',
    'D3_EXTSEARCH_MAIN_SORTDEBUG_DESC'                => 'Insert your search term. <br>In the table you\'ll get all relevance values according to every field, which fits to the hit. You can change all relevance values "... in ..." in the "extended search" settings. "D3PUSH" is the articles importance. The relevance for each article in the result list ("d3Priority") is calculated by this formula: <blockquote>((sum from all "... in ..." fields) x D3PUSH) + D3PUSH</blockquote>',
    'D3_EXTSEARCH_MAIN_SORTDEBUG_START'               => 'start search',
    'D3_EXTSEARCH_MAIN_SORTDEBUG_WORD_IN_'            => '"%1$s" as a complete word in the field "%2$s"',
    'D3_EXTSEARCH_MAIN_SORTDEBUG_PART_IN_'            => '"%1$s" as part of a word in the field "%2$s"',
    'D3_EXTSEARCH_MAIN_SORTDEBUG_article_IN_category' => 'article in category',
    'D3_EXTSEARCH_MAIN_SORTDEBUG_article_IN_manufacturer' => 'article in manufacturer or vendor',
    'D3_EXTSEARCH_MAIN_NOFIELDSDEFINED'               => '<b>There are no fields defined.</b><br>Standard: \'oxtitle\', \'oxsearchkeys\' and \'oxartnum\'',
    'D3_EXTSEARCH_MAIN_FIELDLIST_DESC'                => 'Here you enter the article table fields (from tables "oxarticles" or "oxartextends") in which you want to search. The field names can be found in the shop database. The default entries are oxtitle, oxsearchkeys, oxartnum. This is a regular search in the title, the search terms and the article number. Enter each field in a separate line followed by a line break. For further options of the module it may be necessary to add entries here. If you change these entries, the search index must be recreated again. <br> <br> In addition to the fields, you can also specify here how important the respective data field is for the results. Enter the relevance of the respective field before the field names with => separated. The higher the relevance, the higher an article will be shown if the search term occurs in this field (to be activated separately). If the search term is found in several fields, the relevance adds up. If no relevance is specified, the field automatically receives the value 10. Further information can be found in the manual in the chapter "Relevance and Importance".',
    'SHOP_CONFIG_SEARCHFIELDS'                        => 'Fields to be considered in Search<br>"extended search" use own settings / edit in <input type="button" onclick="document.getElementById(\'myedit\').target = \'basefrm\'; document.getElementById(\'myedit\').fnc.value=\'\';document.getElementById(\'myedit\').cl.value=\'d3_cfg_extsearch_main\';document.getElementById(\'myedit\').submit();" value="extended search">',
    'SHOP_CONFIG_SEARCHUSEAND'                        => 'If several search terms are entered, all search terms must appear in a search result (AND). (If the option is not active, only one search term must occur (OR).)',
    'D3_EXTSEARCH_MAIN_PUTINLEAVEOUT'                 => 'allow included and excluded letters in search string',
    'D3_EXTSEARCH_MAIN_PUTINLEAVEOUT_DESC'            => 'If you set this option, the articles to be found may also have fewer (omitted) or more (inserted) letters than your search term. With difficult search terms, activation may be worthwhile. However, if you have understandable article titles, we recommend that you do not activate them for the time being. Example: The search for "lamshade" also finds "lampshade".',
    'D3_EXTSEARCH_MAIN_MULIPLEWORDS'                  => 'use of multiple search words',
    'D3_EXTSEARCH_MAIN_MULIPLEWORDS_DESC'             => 'Specify how the module handles multiple search terms. This will allow you to decide whether to search with the complete, connected term. Then the search term must necessarily occur in a field. If you specify that each search term is used separately, the search terms may be scattered across the article fields. We recommend this setting as standard. Alternatively, you offer your customers the use of search syntax. This can be particularly useful for technology-oriented stores. <br> <br> The syntax has the following cases: <br> <br> <ul> <li> In quotation marks (") included: seeks or avoids the entire phrase, otherwise each word is used singly, apostrophes are currently not supported </li> <li> Minus (-): word or phrase should not appear in hits </li> <li> Suggested plus (+) (optional): word or Word phrase must be included in hits </li> <li> Unsigned plus is accepted </li> <li> Sign and enclose quotes can be combined </li> </ul> <br> Possible applications: <br> <ul> <li> one </li> <li> "one two" </li> <li> + one </li> <li> + "one two" </li> <li> -three </li> <li> - "three four" </li> </ul>',
    'D3_EXTSEARCH_MAIN_MULIPLEWORDS_SINGLE'           => 'every word will searched separatly',
    'D3_EXTSEARCH_MAIN_MULIPLEWORDS_WHOLE'            => 'will used as complete string',
    'D3_EXTSEARCH_MAIN_MULIPLEWORDS_SYNTAX'           => 'user controlled by search syntax',
    'D3_EXTSEARCH_MAIN_SORTING'                       => 'Article Sorting',
    'D3_EXTSEARCH_MAIN_ORDERBYPRIORITY'               => 'sort hits by relevance',
    'D3_EXTSEARCH_MAIN_ORDERBYPRIORITY_DESC'          => 'Relevance defines how well a found article matches the search term. (Therefore, the relevance sorting is only available in the search.) In categories, this is not available.) If the search term on the article, it should of course be shown in the hits. However, the hits where the search term appears in the title are certainly more meaningful to your client than if the word you are looking for appears somewhere in the later description. When defining the search fields to use, you can specify how high the hit is scored for each search field. For more information, please refer to the module manual in the chapter "Relevance and Importance". <br> <br> Activate the option "Sort hits by relevance", if the search is allowed to change the order of articles according to this logic. The relevance sorting is automatically added to the existing sorting options. <br> <br> If the customer has not selected his own hit sorting, the search hits are then sorted according to their set relevance. You determine the relevance to the database fields defined for the search. The sum of the relevance of the fields containing the search term is then used as a sorting criterion. In connection with the importance of the articles (to be activated separately) the relevance can multiply. You can follow the sorting of your articles in the "Result field analysis".',
    'D3_EXTSEARCH_MAIN_ORDERBYPUSH'                   => 'sort hits by importance',
    'D3_EXTSEARCH_MAIN_ORDERBYPUSH_DESC'              => 'Certainly you differentiate in your article assortment according to main articles, Nebenartikeln and other accessories. This rating can also be included in the search results. For example, if you enable this setting, your customers will be shown the main items, less important items will appear later in the hits. <br> <br> How important an item in the assortment is, you decide on the item itself. In the admin section of the shop, you will find the setting under "Manage articles -> Articles -> Advanced -> Importance of the article in the assortment". You can fill the setting with the values 1 (normal) to 3 (particularly important) via the field "d3push" via external imports or merchandise management connections.',
    'D3_EXTSEARCH_MAIN_ORDERBYALTERNATIVE'            => 'additional sorting with identical relevance sort value',
    'D3_EXTSEARCH_MAIN_ORDERBYALTERNATIVE_DESC'       => 'The sort order is calculated based on the settings set here for each item. If several articles have an identical sorting value, they can be sorted among themselves according to a further criterion. The name of a field of the article table is allowed here (without language addition). Use asc and desc to set whether to sort in ascending or descending order.',
    'D3_EXTSEARCH_MAIN_VARIANTSETTINGS'               => 'Variant Search',
    'D3_EXTSEARCH_MAIN_VARIANTSEARCH'                 => 'shop search for variant articles too',
    'D3_EXTSEARCH_MAIN_VARIANTUSAGE'                  => 'if an article variant is found, show ...',
    'D3_EXTSEARCH_MAIN_VARIANTUSAGE_SHOWPARENT'       => '... there parent article in list',
    'D3_EXTSEARCH_MAIN_VARIANTUSAGE_SHOWVARIANT'      => '... the variant itself in list',
    'D3_EXTSEARCH_MAIN_SHOWVARIANTSWITHOUTFILTERS'    => 'show variants even without filtering',
    'D3_EXTSEARCH_MAIN_SHOWVARIANTSWITHOUTFILTERS_DESC'=> 'Displaying variant articles is usually only useful when filtering specifically for them. If the variant articles should also be shown without filtering, activate this option. The article lists can then become more extensive. This option affects search results and (if active) also categories.',
    'D3_EXTSEARCH_MAIN_VARIANTINALIST'                => 'special variant handling are also used in article lists',
    'D3_EXTSEARCH_MAIN_VARIANTCHECKPARENTACTIVE'      => 'check parent article active status explicitly',
    'D3_EXTSEARCH_MAIN_VARIANTUSAGE_DESC'             => '<p>Set here whether, in the case of a variant found, this variant itself or its parent article should be shown in the result list. When displaying the parent article instead of the variant, please note that the parent articles must also be active and selectable. An additional check for this only takes place if it has been explicitly configured.</p><p>When the parent articles are displayed, the number of matching variants is still shown at the usable filters, as these are the basis for the filters. This discrepancy can confuse the shop visitor. In this case, deactivate the display of the number of articles found for the filter.',
    'D3_EXTSEARCH_MAIN_VARIANTINALIST_DESC'           => 'If category, vendor and manufacturer pages are also to use these variant settings, activate this option. Variants are only shown in filtered item lists. The category assignment is obtained from the parent item. Attributes, manufacturer and vendor must be assigned directly to the variants. Attributes, manufacturers and vendors of the parent item are disregarded.',
    'D3_EXTSEARCH_MAIN_VARIANTSEARCH_DESC'            => 'Instead of searching for regular articles as usual, the shop also finds individual variant articles with this option. Please also enter \'oxvarselect\' in the field list and regenerate the search index.',
    'D3_EXTSEARCH_MAIN_VARIANTCHECKPARENTACTIVE_DESC' => 'For performance reasons, we generally assume that active and purchasable variant articles also have an active parent article. If this can differ in your shop, set this option. Then, for each variant article, it is checked if its parent article is also available. <br> <br> Note that this option requires a lot of power. Alternatively, make sure through the database that variants of inactive parent articles are also not active.',
    'D3_EXTSEARCH_MAIN_OWNFORMFIELDS'                 => 'check for individual filter form fields',
    'D3_EXTSEARCH_MAIN_OWNFORMFIELDS_DESC'            => 'This option allows you to offer the customer additional fields for restricting hits in a simple way. We dedicated this function to a separate chapter in the module manual (see "Technical Explanations").',
    'D3_EXTSEARCH_MAIN_LOGSETTINGS'                   => 'Statistic',
    'D3_EXTSEARCH_MAIN_LOGHITLESS'                    => 'log resultless searches in statistic',
    'D3_EXTSEARCH_MAIN_LOGHITLESS_DESC'               => 'If the customer starts a search query that can not provide results, the search terms are recorded for you. You will find the list under the \'Logging\' tab and can also optimize your products for these terms.',
    'D3_EXTSEARCH_MAIN_LOGFORSEARCH'                  => 'log all search queries in statistic',
    'D3_EXTSEARCH_MAIN_LOGFORSEARCH_DESC'             => 'logs all searches for the in-module statistics. This setting can also be set without other shop functions being logged. If the shop-wide logging is activated, the search queries are generally written.',
    'D3_EXTSEARCH_MAIN_PHONETICS'                     => 'Phonetic Search (search for similar sound)',
    'D3_EXTSEARCH_MAIN_PHONETICS_DESC'                => 'This is the fault-tolerant search that finds sound-like hits, even if they were written differently. This makes the search for typographical errors tolerant.',
    'D3_EXTSEARCH_MAIN_SIMILARSEARCH'                 => 'if there is no search result, shop search for similar-sounding articles (e.g.: search: <i>Pflan<b>s</b>e</i>, result: <i>Pflan<b>z</b>e</i>)',
    'D3_EXTSEARCH_MAIN_SIMILARSEARCH_DESC'            => 'Here you activate (or deactivate) the phonetic search. For example, this will catch you from typing errors in the search query, and the customer will most likely find your desired articles. If at the same time the search for meaning (semantic) is activated, it is first tried to find matching matches. If this fails, hits are determined by the sound search.',
    'D3_EXTSEARCH_MAIN_PHONETICLANG'                  => 'for similar search used language',
    'D3_EXTSEARCH_MAIN_PHONETICLANG_DESC'             => 'Since the different human languages differ in their pronunciation and in the word or letter composition, a language-dependent index generation process is necessary for an optimal search result. If you mainly use a different language in your shop than the one shown opposite, please ask us if a module for your language is also available. <br> <br> In the standard version we supply 2 options for the German language. We recommend using the option "German with Vowels", because the accuracy of the search is much higher.',
    'D3_EXTSEARCH_MAIN_SIMILAREXTLIST_1'              => 'shop show additional similar-sounding articles, if regular search contains max.',
    'D3_EXTSEARCH_MAIN_SIMILAREXTLIST_2'              => 'results',
    'D3_EXTSEARCH_MAIN_SIMILAREXTLIST_DESC'           => 'If the search scores only a few hits, you can also provide the customer with similar items. These similar items are shown in the result list after the actual matches. The customer will be informed with a message about the filled-in list. Please use this setting wisely, as the additional hits could confuse the customers.',
    'D3_EXTSEARCH_MAIN_MINPHONLENGTH'                 => 'result precision on short search terms',
    'D3_EXTSEARCH_MAIN_MINPHONLENGTH_LESS'            => 'less precision',
    'D3_EXTSEARCH_MAIN_MINPHONLENGTH_REG'             => 'normal precision',
    'D3_EXTSEARCH_MAIN_MINPHONLENGTH_MORE'            => 'more precision',
    'D3_EXTSEARCH_MAIN_MINPHONLENGTH_DESC'            => 'The indexed similarity search can only work sensibly and efficiently after a certain word length. Therefore, the phonetic search has two different ways of doing things: searching through the previously generated index and the similarity defined at runtime. <br> <br> Both methods have advantages and disadvantages: <br> <ul> <li> The index-based Search is very accurate and fast. However, this requires a minimum length of relevant characters. If the search terms are shorter, the accuracy decreases rapidly and if the search terms are too short, even the entire range of shops would be displayed. </li> <li> For short search words, the similarity to the runtime is automatically calculated. Their strengths lie in the recognition of short search words. Although it is not quite as accurate as the index search. But since the words are short, this does not matter so much here. It should be noted, however, that this type of search requires a bit more processing power and is therefore slower. </li> </ul> <br> <br> When will you switch from one technique to another? If a search is started, the module checks which word makes the most appropriate technique. You can now define how quickly to switch to the index-based search by using the "Search accuracy with short search words" switch. The goal should be to switch to the index as fast as possible, but without generating too many hits. The setting possibilities extend to (phonetic relevant) word lengths between 3 and 5 characters. Just do a few experiments with the search terms that are typical for your shop and vary the settings accordingly. If you have any questions, please contact us.',
    'D3_EXTSEARCH_MAIN_SEMANTICS'                     => 'Semantic Search (search for similar type)',
    'D3_EXTSEARCH_MAIN_SEMANTICS_DESC'                => 'Semantic terms are words that have a similar meaning to the search term. If you are looking for "mugs", you will also find articles that have "cup" content. <br> <br> A suitable lexicon is required for using the semantic search. You can fill this yourself according to your own requirements in the synonym editor (recommended). Information on its operation can be found in the manual. <br> <br> Alternatively, we also provide an extensive standard database. The link can be found in the installation instructions of the module.',
    'D3_EXTSEARCH_MAIN_SEMANTICSEARCH'                => 'shop search for articles with similar sense (e.g.: search: <i>Gew&auml;chs</i>, result: <i>Pflanze</i>)',
    'D3_EXTSEARCH_MAIN_SEMANTICSEARCH_MISSING'        => 'shop search for articles with similar sense (e.g.: search: <i>Gew&auml;chs</i>, result: <i>Pflanze</i>)<br><b>Semantic lexicon isn\'t installed!</b>',
    'D3_EXTSEARCH_MAIN_SEMANTICSEARCH_DESC'           => 'Check this box to enable a similar search in the shop. By e.g. Regional differences may cause your customers to label an item differently, but they may mean your product. If the customer now submits his request, he may be shown the terms that better describe the desired product in your shop.',
    'D3_EXTSEARCH_MAIN_SEMANTICUSEPHONETIC'           => 'if the search term contains spelling errors, in addition to the search for meaning, the correct spelling is tried; however, may produce strongly deviant hits; requires activated phonetic search',
    'D3_EXTSEARCH_MAIN_SEMANTICUSEPHONETIC_DESC'      => 'This setting also allows the same search for the phonetic search, if no similar words are found. However, since the desired meaning is not clear, under certain circumstances strongly deviating hits are shown. We recommend that you use this setting only to a limited extent. <br> To use this setting, first create the index for the same search: "D3 Modules -> Extended Search -> Settings -> Basic Settings -> Search Index -> Dictionary for the reindex the same search ".',
    'D3_EXTSEARCH_MAIN_SAVE'                          => 'save',
    'D3_EXTSEARCH_MAIN_INDEX'                         => 'Search Index',
    'D3_EXTSEARCH_MAIN_INDEX_DESC'                    => 'That the similarity search can work requires the generation of a search index. For this, the defined search fields are prepared for the search with a language-dependent key. Thus, the actual search query is not significantly slower than a regular article search. (However, the search index has no effect on the execution time of other settings.) The index is automatically updated if you enter your articles in the admin area of the shop or if the import tool you are using uses the shop framework (your Oxid partner can provide information on this To give). Manage your articles by other means, regenerate the search index after each article update. The generation requires some computing power, but is usually completed in a few seconds. <br> <br> The regeneration is also necessary if changes are made to the field names to be used.',
    'D3_EXTSEARCH_MAIN_INDEXARTCNT'                   => 'articles per work up run for index',
    'D3_EXTSEARCH_MAIN_INDEXARTCNT_DESC'              => 'The web server aborts scripts after a certain period of time for security reasons. In order to be able to finish the generation of the search index nevertheless, this script processes only a certain number of articles and then restarts. Define here how many articles should be processed in one go. If the generation terminates with an error, reduce the number. The lower the number, the longer the script needs.',
    'D3_EXTSEARCH_MAIN_INDEXERR'                      => 'The required index for the fault-tolerant search is incomplete. Click here to regenerate the list:',
    'D3_EXTSEARCH_MAIN_INDEXNOERR'                    => 'The required index for the fault-tolerant search seems to be complete. At the moment, no action is necessary if you have not changed the language or have imported articles. <br> The index must be created separately for each language of the shop.',
    'D3_EXTSEARCH_MAIN_GENINDEXCMPL'                  => 'Generate outdated phonetic search index',
    'D3_EXTSEARCH_MAIN_GENINDEXCMPL_DESC'             => 'Generates the search index for all changed or added articles in the shop.',
    'D3_EXTSEARCH_MAIN_GENSEMANTICINDEX'              => 'Reindex lexicon for same meaning search',
    'D3_EXTSEARCH_MAIN_GENSEMANTICINDEX_DESC'         => 'For the connection of same meaning search and phonetic search also the lexicon needs the phonetic index. With this button you start the reindexing of the lexicon. Normally this is not necessary.',
    'D3_EXTSEARCH_MAIN_SHOW_POPUP'                    => 'show popup while searching',
    'D3_EXTSEARCH_MAIN_SHOW_POPUP_DESC'               => 'To inform impatient customers during the search process, you can display an information pop-up. You can also design this according to your shop layout in terms of content and graphics.',
    'D3_EXTSEARCH_MAIN_CATEGORY'                      => 'Search in category titles',
    'D3_EXTSEARCH_MAIN_CATEGORY_SEARCH'               => 'search in category titles too and show containing articles',
    'D3_EXTSEARCH_MAIN_CATEGORY_SEARCH_DESC'          => 'The default search finds only hits in the created articles. However, your customer may be looking for a term that lets you name a whole category. If you have set this check, the search term will also be searched in the category name.',
    'D3_EXTSEARCH_MAIN_CATEGORY_ANDOR_DESC'           => 'This setting is only used for searching in category names. There is a separate setting for the article search.',
    'D3_EXTSEARCH_MAIN_CATEGORY_ARTHANDLING'          => 'Show category yourself or their products',
    'D3_EXTSEARCH_MAIN_CATEGORY_ARTINCAT'             => 'Show articles from category',
    'D3_EXTSEARCH_MAIN_CATEGORY_CATINLIST'            => 'Show category for selection',
    'D3_EXTSEARCH_MAIN_CATEGORY_PRIORITY'             => 'relevance at category results',
    'D3_EXTSEARCH_MAIN_CATEGORY_PRIORITY_DESC'        => 'Article hits get their relevance based on the relevance numbers set on the fields. Hits found on the basis of their category affiliation can not contain their relevance in this way. Define here which place in the article list should receive these hits.',
    'D3_EXTSEARCH_MAIN_MANUFACTURER'                  => 'Search in brand and vendor titles',
    'D3_EXTSEARCH_MAIN_MANUFACTURER_SEARCH'           => 'search in brand and vendor titles too and show assigned articles',
    'D3_EXTSEARCH_MAIN_MANUFACTURER_SEARCH_DESC'      => 'The default search finds only hits in the created articles. However, your customer may be looking for a term by which you have named a brand or vendor. If you have set this checkbox, the search terms are searched in the brand or vendor name.',
    'D3_EXTSEARCH_MAIN_MANUFACTURER_ANDOR_DESC'       => 'This setting is only used for the search in brand and vendor names. There is a separate setting for the article search.',
    'D3_EXTSEARCH_MAIN_MANUFACTURER_PRIORITY'         => 'relevance at brand / vendor results',
    'D3_EXTSEARCH_MAIN_MANUFACTURER_PRIORITY_DESC'    => 'Article hits get their relevance based on the relevance numbers set on the fields. Hits found on the basis of their brand or vendor affiliation can not contain their relevance in this way. Define here which place in the article list should receive these hits.',
    'D3_EXTSEARCH_MAIN_ADMINPANEL'                    => 'Admin Panel',
    'D3_EXTSEARCH_MAIN_ADMINSHOWVARIANTS'             => 'in searchresults show variants in article list too',
    'D3_EXTSEARCH_MAIN_ADMINSHOWVARIANTS_DESC'        => 'If you would like to edit your articles in the admin area ("Manage articles -> Articles"), you can search for existing articles there. However, the default search does not take into account variant articles. If you also want to make them searchable, activate this option.',
    'D3_EXTSEARCH_MAIN_USEARTNUMSEARCH'               => 'perform a specialized artnum search',
    'D3_EXTSEARCH_MAIN_USEARTNUMSEARCH_DESC'          => 'If this option is checked, an item number matching the search term is explicitly searched before the actual search run. Found articles are displayed and the search ends. This can lead to faster search results if used frequently.',
    'D3_EXTSEARCH_MAIN_DONTUSEOWNDBVIEWS'             => 'Database queries <b> do not </b> use the module-specific view tables',
    'D3_EXTSEARCH_MAIN_DONTUSEOWNDBVIEWS_DESC'        => 'For performance reasons, the search does not use the system-specific view tables, but comes with optimized versions of it. Depending on the size of the database, their use can speed the speed of database queries up to a factor of 100. If you do <b>not</b> want to use the specialized view tables, check this box. The queries are then routed through the on-look view tables. <br> Note that disabling this option requires the view tables to be updated again.',
    'D3_EXTSEARCH_MAIN_GENERATOR_INCONSISTENTTABLE'   => 'The database article table is inconsistent to longtext table. Please fix it before executing this generator.<br><br>For further informations, check out our FAQ at <a href="%1$s" target="_new">%1$s</a>.',
    'D3_EXTSEARCH_MAIN_GENERATOR_INCONSISTENTTABLE_NOLINK' => 'The database article table is inconsistent to longtext table. Please fix it before executing this generator.',
    'D3_EXTSEARCH_MAIN_GENERATOR_FINISHED'            => 'Finished.',
    'D3_EXTSEARCH_MAIN_GENERATOR_NOTE'                => 'Notice',
    'D3_EXTSEARCH_MAIN_GENERATOR_PROCESSED'           => '%1$s article language(s) (ca. %2$s article(s)) processed<br>Finished!',
    'D3_EXTSEARCH_MAIN_GENERATOR_TERMPROCESSED'       => '%1$s term(s) processed<br>Finished!',
    'D3_EXTSEARCH_MAIN_GENERATOR_PROCESSING'          => 'Processing %1$s&#37;',
    'D3_EXTSEARCH_MAIN_GENERATOR_PROCESSING1'         => 'Processing: %1$s / %2$s article language(s) (ca. %3$s article(s))',
    'D3_EXTSEARCH_MAIN_GENERATOR_PROCESSING3'         => 'Processing: %1$s / %2$s term(s)',
    'D3_EXTSEARCH_MAIN_GENERATOR_PROCESSING2'         => '%1$s&#37; finished',
    'D3_EXTSEARCH_MAIN_GENERATOR_WAIT'                => 'Please wait...',
    'D3_EXTSEARCH_MAIN_GENERATOR_CLOSEWND'            => 'close window',
    'D3_EXTSEARCH_MAIN_GENERATOR_EXCEPTION'           => 'Generation error, the index can unfortunately not be created.',

    'D3_EXTSEARCH_NAVI_MAINSETTINGS'                  => 'Common Settings',
    'D3_EXTSEARCH_NAVI_DISPTYPE'                      => 'Type of filter display',
    'D3_EXTSEARCH_NAVI_DISPTYPE_LINKLIST'             => 'as link list',
    'D3_EXTSEARCH_NAVI_DISPTYPE_DROPDOWN'             => 'as dropdown list',
    'D3_EXTSEARCH_NAVI_DISPTYPE_DESC'                 => 'Here you set the display form of the category, supplier and brand lists. The drop-down lists save space in the display, but can be confusing for many entries. Alternatively, link lists are recommended, which can be restricted in their length. <br> Both forms of display can be edited in the template.',
    'D3_EXTSEARCH_NAVI_EMPTYSEARCH'                   => 'allow search without a term',
    'D3_EXTSEARCH_NAVI_EMPTYSEARCH_DESC'              => 'It may be useful to allow searches without a search term. It may be that the resulting hits are filtered by an additional setting or you want to build an extensive search form, which may not contain a freely definable search term.',
    'D3_EXTSEARCH_NAVI_CATFILTER'                     => 'Category Filter',
    'D3_EXTSEARCH_NAVI_CATLIST'                       => 'show category list',
    'D3_EXTSEARCH_NAVI_CATLIST_DESC'                  => 'Check the box to show your customer a selection of the affected categories for a comprehensive hit list. This allows him to narrow down and improve his search results. The category name and the number of articles in the hit list are displayed.',
    'D3_EXTSEARCH_NAVI_CATLIST_SORT'                  => 'sort by',
    'D3_EXTSEARCH_NAVI_CATLIST_SORT_COUNT'            => 'count of related articles',
    'D3_EXTSEARCH_NAVI_CATLIST_SORT_DATA'             => 'adjustable sort',
    'D3_EXTSEARCH_NAVI_CATLIST_SORT_DESC'             => 'Define the criterion according to which the category list should be sorted. However, this has no influence on the presentation.',
    'D3_EXTSEARCH_NAVI_CATLIST_MORE_DESC'             => 'Further settings for category filters can be found directly at the respective categories in the tab for the search settings.',
    'D3_EXTSEARCH_NAVI_FILTER_DISPLAYTYPE'            => 'displayed selection',
    'D3_EXTSEARCH_NAVI_FILTER_DISPLAYTYPE_COMBINED'   => 'switchable single and multi selection',
    'D3_EXTSEARCH_NAVI_FILTER_DISPLAYTYPE_SINGLE'     => 'single selection only',
    'D3_EXTSEARCH_NAVI_FILTER_DISPLAYTYPE_MULTI'      => 'multi selection only',
    'D3_EXTSEARCH_NAVI_FILTER_DISPLAYTYPE_DESC'       => 'Set how the filters are to be shown to the shopper.<br><br>Single selection displays a DropDown, which submits the single entry immediately after selection. Another entry from this filter is not selectable.<br><br>Multi selection displays all entries as checkboxes. The customer can select all desired entries and submit them off altogether.',
    'D3_EXTSEARCH_NAVI_FILTER_MORE_DESC'              => 'Further settings for attribute filters can be found directly at the respective attributes in the tab for the search settings.',
    'D3_EXTSEARCH_NAVI_CATLISTMAINCATEGORIESONLY'     => 'only show main categories of the articles',
    'D3_EXTSEARCH_NAVI_CATLISTMAINCATEGORIESONLY_DESC'=> 'The option prevents listing additional assigned categories as filters. Only the main categories of the found items are shown.',
    'D3_EXTSEARCH_NAVI_VENDORFILTER'                  => 'Vendor Filter',
    'D3_EXTSEARCH_NAVI_VENDORLIST'                    => 'show vendor list',
    'D3_EXTSEARCH_NAVI_VENDORLIST_DESC'               => 'Just as for the categories, there is also the option of filtering the hit list once again for the vendors. You switch this on here. This option is only available if you have generally activated the vendors in the shop and also allow a search for it. (\'Load and display vendor list\')',
    'D3_EXTSEARCH_NAVI_VENDORLIST_SORT'               => 'sort by',
    'D3_EXTSEARCH_NAVI_VENDORLIST_SORT_COUNT'         => 'count of related articles',
    'D3_EXTSEARCH_NAVI_VENDORLIST_SORT_ALPHA'         => 'alphabetical',
    'D3_EXTSEARCH_NAVI_VENDORLIST_SORT_DESC'          => 'Determine the display order in which the vendors should be listed.',
    'D3_EXTSEARCH_NAVI_MANUFACTURERFILTER'            => 'Brand Filter',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST'              => 'show brand list',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST_DESC'         => 'Just as for the categories, there is also the option of filtering the hit list again by manufacturer. You switch this on here. This option is only available if you have generally activated the manufacturers in the shop and also allow a search for them. (\'Load and display manufacturer list\')',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST_SORT'         => 'sort by',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST_SORT_COUNT'   => 'count of related articles',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST_SORT_ALPHA'   => 'alphabetical',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST_SORT_DESC'    => 'Determine the display order in which the manufacturers should be listed.',
    'D3_EXTSEARCH_NAVI_REDIRECTS'                     => 'Redirects',
    'D3_EXTSEARCH_NAVI_UNIQUEHIT'                     => 'at 1 article hit, shop goes directly to the detail page of the article',
    'D3_EXTSEARCH_NAVI_UNIQUEHIT_DESC'                => 'If your customer has searched so precisely that he has the desired information as the only one in the hit list, you can spare him the detour via the hit list and immediately supply him with the detail page of the article found.',
    'D3_EXTSEARCH_NAVI_UNIQUECONTENTHIT'              => 'at 1 CMS / text hit, shop changes directly to the CMS page',
    'D3_EXTSEARCH_NAVI_UNIQUECONTENTHIT_DESC'         => 'If the search result contains no articles, but a single CMS text, it will be redirected directly to the appropriate CMS page. The user leaves the search function of the shop, his search settings are then no longer available.',
    'D3_EXTSEARCH_NAVI_UNIQUEVENDORHIT'               => 'at 1 vendor hit, shop goes directly to the vendor page of the shop',
    'D3_EXTSEARCH_NAVI_UNIQUEVENDORHIT_DESC'          => 'If the search result does not contain any articles, but only one vendor, it will be forwarded directly to the appropriate vendor page of your shop. This option requires "Search by manufacturer and vendor name". The user leaves the search function of the shop, his search settings are then no longer available.',
    'D3_EXTSEARCH_NAVI_UNIQUEMANUFACTURERHIT'         => 'at 1 manufacturer, shop goes directly to the manufacturer page of the shop',
    'D3_EXTSEARCH_NAVI_UNIQUEMANUFACTURERHIT_DESC'    => 'If the search result contains no articles, but a single manufacturer, it will be forwarded directly to the appropriate manufacturer page of your shop. This option requires "Search by manufacturer and vendor name". The user leaves the search function of the shop, his search settings are then no longer available.',
    'D3_EXTSEARCH_NAVI_CONTENTS'                      => 'Information pages / CMS Texts',
    'D3_EXTSEARCH_NAVI_CONTENTLIST'                   => 'search in CMS pages',
    'D3_EXTSEARCH_NAVI_CONTENTLIST_DESC'              => 'Activate this option if you also want to make your information searchable for your customers. Please note that you have to activate every single CMS text for the search. This avoids that e.g. Info texts intended for e-mails are to be considered by the search. Activate directly on the text: <br> <br> "Customer Information -> CMS Pages -> Main -> can be searched"',
    'D3_EXTSEARCH_NAVI_ATTRIBUTEFILTER'               => 'Attribute Filter',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST'                 => 'show attribute list',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_DESC'            => 'Set this option, if attributes can used for filtering. <br>Every attribute can excluded from usage on its setting page ("Administer Products > Attributes").',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_ASSIGNMENT'      => 'use attribute activation per category, vendor, manufacturer',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_ASSIGNMENT_DESC' => 'If not all available attributes are to be offered for filtering in these elements, you can <ul> <li> generally exclude each attribute from the filtering or </li> <li> alternatively also define which attribute may be used in which element </li> </ul> If you would like to use the individual assignment, please activate this option. For performance reasons, this is not activated per default. <br> <br> Please set the assignments to the respective category, vendor, manufacturer or corresponding to the respective attribute.',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_ASSIGNMENT_NA'   => 'Assignment Usage are not enabled.',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_ASSIGNMENT_NA_DESC'  => 'The use of the assignments must be activated for performance reasons in the settings of the module (D3 Modules -> Extended Search -> Settings -> Filter + Display -> Attribute Filter -> Use attribute activation per category). Until then you can set the assignment. However, these are only used after activation.',
    'D3_EXTSEARCH_NAVI_ATTRIBUTES_COMBINE'            => 'multiple attribute selection will combined via "OR"',
    'D3_EXTSEARCH_NAVI_ATTRIBUTES_COMBINE_DESC'       => 'Activate this option if, for example, you also want to show articles that have only one of the properties when the selected color and material have been selected. Without this option, only items that have both properties at the same time will be shown.',
    'D3_EXTSEARCH_NAVI_ATTRIBUTES_SORT'               => 'attributes sort by',
    'D3_EXTSEARCH_NAVI_ATTRIBUTES_SORT_POS'           => 'adjustable attribute position',
    'D3_EXTSEARCH_NAVI_ATTRIBUTES_SORT_TITLE'         => 'attribute title',
    'D3_EXTSEARCH_NAVI_ATTRIBUTES_SORT_DESC'          => 'Here you define the order of the displayed attributes.',
    'D3_EXTSEARCH_NAVI_ATTRIBUTEVALUES_COMBINE'       => 'multiple attribute value selections ("multi selection") will combined via "AND"',
    'D3_EXTSEARCH_NAVI_ATTRIBUTEVALUES_COMBINE_DESC'  => 'Activate this option, for example, if the selected color "red" and "green" only show items that have both colors at the same time. Without this option, articles with only one of the two properties will also be shown.',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_SORT'            => 'attribute values sort by',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_SORT_COUNT'      => 'count of related articles',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_SORT_POS'        => 'adjustable attribute list position',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_SORT_TITLE'      => 'attribute value title',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_SORT_DESC'       => 'Here you define the order of the displayed attribute values. <br> <br> The attribute list position can be stored in the database. Unfortunately, the OXID shop does not offer a standard way to change these values in the backend.',
    'D3_EXTSEARCH_NAVI_NOATTRIBUTEARTS'               => 'allow filter for articles, wich aren\'t assigned to this attribute',
    'D3_EXTSEARCH_NAVI_NOATTRIBUTEARTS_DESC'          => 'With this option, the attribute filters offer the option of filtering for items that are e.g. expressly assigned to no color or material.',
    'D3_EXTSEARCH_NAVI_SHOWNOTSELECTABLEATTRIBUTES'   => 'don\'t hide not (safely) selectable attribute values',
    'D3_EXTSEARCH_NAVI_SHOWNOTSELECTABLEATTRIBUTES_DESC' => 'When filtering articles via attributes, other attributes that cannot be selected with certainty are normally hidden. If the shop visitor wishes to add additional attribute values to his hit list, these can be displayed. However, invalid attribute combinations may then be selected that do not result in a hit.<br>Note that an additional data query is executed to determine these attributes. Depending on the article attribute structure, this may require additional loading time. The display of available items count should then be deactivated, as the values are still correct but then no longer plausible.',
    'D3_EXTSEARCH_NAVI_CONTENTSEARCHINLONGTEXT'       => 'search in CMS longtexts too',
    'D3_EXTSEARCH_NAVI_CONTENTLONG_DESC'              => 'If you also want to search the content of the title of your text, activate these options. Note that this requires more power.',
    'D3_EXTSEARCH_NAVI_SMALLLISTITEMS'                => 'Limit category, vendor, manufacturer and text lists <br> (customer can show all results on request, only works with "link lists")',
    'D3_EXTSEARCH_NAVI_SMALLLISTITEMS_2'              => ' entries',
    'D3_EXTSEARCH_NAVI_SMALLLISTITEMS_DESC'           => 'For many search hits, the list of categories, manufacturers, vendors and texts can be very long. The article hits may slip out of the display area. Limit the number of categories and manufacturers displayed to keep these lists short. If these lists are then actually shortened, your customer will have a button available to display these lists completely on request.',
    'D3_EXTSEARCH_NAVI_ALISTFILTER'                   => 'show filters in article lists too (e.g. category, brand, vendor)',
    'D3_EXTSEARCH_NAVI_ALISTFILTER_DESC'              => 'Article lists can also be restricted with filters. Filtering is possible in category views, manufacturer and vendor lists. Here you have category, manufacturer, supplier, attribute and price filters available. Options are the settings for the search. <br> If this entry is not selectable, this option is probably not included in your module license. Have your license extended for this.',
    'D3_EXTSEARCH_NAVI_PRICELIST'                     => 'show price steps',
    'D3_EXTSEARCH_NAVI_PRICEFILTER'                   => 'Price Filter',
    'D3_EXTSEARCH_NAVI_PRICELIST_DESC'                => 'All found articles are divided into price categories and offered as further filter criteria. Thus, the customer can choose a certain price range for his desired items. Discounts are not included in the category prices. Found articles are less expensive than the search request.',
    'D3_EXTSEARCH_NAVI_PRICELIST_ITEMS'               => 'maximum count of price steps',
    'D3_EXTSEARCH_NAVI_PRICELIST_ITEMS_DESC'          => 'So many price ranges are displayed at the maximum. Normally, however, this can be less, since empty price ranges (ie without contained articles) are filtered out. (only effective when displayed as dropdown list)',
    'D3_EXTSEARCH_NAVI_PRICELIST_ROUNDED'             => 'price limits will rounded',
    'D3_EXTSEARCH_NAVI_PRICELIST_ROUNDED_DESC'        => 'The smallest price range starts at the lowest possible price, the largest price range extends to the highest price. The boundaries in between are calculated. However, these can sometimes be at crooked cents. With the option, the prices of the margins are rounded, but the margins are less meaningful. (only effective when displayed as dropdown list)',
    'D3_EXTSEARCH_NAVI_PRICELIST_DISPLAY'             => 'price steps display type',
    'D3_EXTSEARCH_NAVI_PRICELIST_DISPLAY_DESC'        => 'In addition to the usual dropdown or link lists, you can also use sliders for the price ranges. This makes the selection more intuitive for your customers.',
    'D3_EXTSEARCH_NAVI_PRICELIST_DISPLAY_LISTTYPE'    => 'as dropdown',
    'D3_EXTSEARCH_NAVI_PRICELIST_DISPLAY_SLIDER'      => 'as jQuery slider',
    'D3_EXTSEARCH_NAVI_PRICELIST_REQU'                => '* jQuery slider requires installed jQuery framework in actual version (tried with version 1.4.2) with components "jQueryUI Core", "jQueryUI Widget", "jQueryUI Mouse" and "jQueryUI Slider".',
    'D3_EXTSEARCH_NAVI_HIGHLIGHT'                     => 'highlight found contents in search results',
    'D3_EXTSEARCH_NAVI_HIGHLIGHT_DESC'                => 'Sometimes the term you are looking for appears in the middle of descriptions. Use this option to visually highlight the term. <br> <br> To do so, set what the highlighting should look like in the template \'d3_ext_search_highlight.tpl\'. In \'inc/product.tpl\', replace all variables that should contain accents with the Smarty call \[\{d3_extsearch_highlight text=$variable name\}\], replacing $ variable-name with the actual text variable.',
    'D3_EXTSEARCH_NAVI_DONTSHOWFILTERARTICLECOUNT'    => 'Number of items found for the filter is <b>not</b> displayed',
    'D3_EXTSEARCH_NAVI_DONTSHOWFILTERARTICLECOUNT_DESC'=> 'The number of matching items is shown on the offered item filters. If the display is not wanted, it can be deactivated here.',
    'D3_EXTSEARCH_NAVI_INDEXFILTER'                   => 'Index Letters',
    'D3_EXTSEARCH_NAVI_SHOWINDEX'                     => 'show index letters',
    'D3_EXTSEARCH_NAVI_SHOWINDEX_DESC'                => 'This index is a small tab above the hit list, which allows your customers to select the articles by their first letter. The display of the letter index can be edited via CSS and the enclosed templates.',
    'D3_EXTSEARCH_NAVI_FILTERFIELDNAME'               => 'used field name for index letter',
    'D3_EXTSEARCH_NAVI_FILTERFIELDNAME_DESC'          => 'Using this field name, the index letter is determined and the articles are filtered by selecting a letter. All fields from the table oxarticles (without language addition) are possible here.',
    'D3_EXTSEARCH_NAVI_OWNFORMFIELDS'                 => 'individual filters',
    'D3_EXTSEARCH_NAVI_SAVE'                          => 'save',

    'D3_EXTSEARCH_QUICK'                              => 'suggest results',
    'D3_EXTSEARCH_QUICK_ACTIVE'                       => 'when entering the search term suggestions are delivered',
    'D3_EXTSEARCH_QUICK_ACTIVE_DESC'                  => '<img src="../modules/d3/extsearch/out/admin/img/d3_extsearch_quicksearch.jpg"><br>Give your customer the opportunity to find items even faster. The quick search already shows the first hits in a separate frame while entering the search term. <br> In mobile views, the quick hit list is not shown for reasons of usability. <br> <br> The results window of the quick search can be customized via CSS and template adjustments be designed.',
    'D3_EXTSEARCH_QUICK_FULLOBJECTS'                  => 'Suggest search loads complete objects, instead of performance-optimized allocation',
    'D3_EXTSEARCH_QUICK_FULLOBJECTS_DESC'             => 'For the usual representation of the suggest search, a performance-optimized assignment of the result data is sufficient. For the display of certain information (e.g., calculated prices, etc.), it is necessary to load the complete objects. However, this reduces the charging speed.',
    'D3_EXTSEARCH_QUICK_COUNT'                        => 'maximum number of items to be loaded in the suggest search',
    'D3_EXTSEARCH_QUICK_COUNT_DESC'                   => 'For performance reasons, the suggest search hits are only shown from a maximum number. If more hits are found, the article list does not blend in, instead a hint is shown. Increase the value if you do not get suggest hits for common search terms. But please check the load of your server / account afterwards. The default value is 200.',
    'D3_EXTSEARCH_QUICK_LOADCATEGORIES'               => 'In addition, search for appropriately named categories',
    'D3_EXTSEARCH_QUICK_LOADCATEGORIES_DESC'          => 'In addition to articles, categories are also searched in the suggest search. Please note that this option consumes additional resources, which slow down the suggest search.',
    'D3_EXTSEARCH_QUICK_LOADMANUFACTURERS'            => 'In addition, also search for appropriately named manufacturers',
    'D3_EXTSEARCH_QUICK_LOADMANUFACTURERS_DESC'       => 'In addition to articles, the suggest Search also searches for manufacturers. Please note that this option consumes additional resources, which slow down the suggest search.',
    'D3_EXTSEARCH_QUICK_LOADVENDORS'                  => 'In addition, also search for appropriately named vendors',
    'D3_EXTSEARCH_QUICK_LOADVENDORS_DESC'             => 'In addition to articles, vendors are also searched in the suggest search. Please note that this option consumes additional resources, which slow down the suggest search.',
    'D3_EXTSEARCH_QUICK_LOADCONTENT'                  => 'In addition, also search for appropriately named texts',
    'D3_EXTSEARCH_QUICK_LOADCONTENT_DESC'             => 'Besides articles, texts are also searched in the suggest search. Please note that this option consumes additional resources, which slow down the suggest search. <br> <br> To use this option, it is necessary that the text search is also activated for the regular hit list ("Basic settings" tab).',
    'D3_EXTSEARCH_QUICK_CMPLOBJ'                      => 'before Oxid 4.3.0: load entire article object, otherwise only ID, title and icon. <br> Activate only when needed, consumes more resources. ',
    'D3_EXTSEARCH_QUICK_CMPLOBJ_DESC'                 => 'The presentation of the suggest matches can be adjusted graphically by you in a template to your shop. You may need additional data for your desired display except the article name and link to the article. Thus, for example, also thumbnails, the price or a shopping cart button. For this you need information that is not available in the standard version. Set this checkbox to make all article data available. <br> <br> From Shop version 4.3.0 it is absolutely necessary to load the complete article object. This setting is then ignored.',
    'D3_EXTSEARCH_QUICK_LOADVARIANTS'                 => 'Load variant articles and show them in the suggest search <br> Enter additionally \'oxvarselect\' in the search fields.',
    'D3_EXTSEARCH_QUICK_LOADVARIANTS_DESC'            => 'Normally the shop search does not search for product variants. However, if you have many variant articles in your shop, it may make sense to unlock the search.',
    'D3_EXTSEARCH_QUICK_SAVE'                         => 'save',
    'D3_EXTSEARCH_QUICK_TPLNOTICE'                    => 'Note: To graphically customize the suggest result window, expand the template blocks in \'d3_ext_search_suggestsearch.tpl\'.',
    'D3_EXTSEARCH_QUICK_IAS'                          => 'interactive search (selection search)',
    'D3_EXTSEARCH_QUICK_SHOWIAS'                      => 'show interactive search (if text part is selected)',
    'D3_EXTSEARCH_QUICK_SHOWIAS_DESC'                 => 'If you mark a word in the shop, a small form will be displayed near you, with the help of which you can immediately search for the highlighted word. If you click elsewhere in the shop, the window disappears.',

    'D3_EXTSEARCH_STAT_TYPE'                          => 'evaluation:',
    'D3_EXTSEARCH_STAT_NOHITS'                        => 'no evaluations available',
    'D3_EXTSEARCH_STAT_NOREPORTBASE'                  => 'Your shop doesn\'t support this statistics.',
    'D3_EXTSEARCH_STAT_NOREPORTBASE_DESC'             => 'To use statistics, the OXID class \'OeStatistics_Report_Base\' is required. In OXID eShop, this script is provided by a separate "Statistics" module. Therefore, the graphical evaluation in your shop can unfortunately not be used without its installation.',
    'D3_EXTSEARCH_STAT_TYPEHITLESS'                   => 'Search queries without hits',
    'D3_EXTSEARCH_STAT_TYPEMOSTHITS'                  => 'Search queries with the most hits',
    'D3_EXTSEARCH_STAT_TYPEMOSTSEARCHES'              => 'most common search terms',
    'D3_EXTSEARCH_STAT_LANG'                          => 'language:',
    'D3_EXTSEARCH_STAT_TIME'                          => 'period:',
    'D3_EXTSEARCH_STAT_GENERATESTAT'                  => 'Create evaluation',
    'D3_EXTSEARCH_STAT_SEARCHWORD'                    => 'search term',
    'D3_EXTSEARCH_STAT_HITS'                          => 'hits',
    'D3_EXTSEARCH_STAT_SEARCHES'                      => 'requests',
    'D3_EXTSEARCH_STAT_TYPES_CATEGORY'                => 'category',
    'D3_EXTSEARCH_STAT_TYPES_PRICE'                   => 'price',
    'D3_EXTSEARCH_STAT_TYPES_VENDOR'                  => 'vendor',
    'D3_EXTSEARCH_STAT_TYPES_MANUFACTURER'            => 'brand',
    'D3_EXTSEARCH_STAT_TYPES_OWNLIKE'                 => 'own search field (LIKE)',
    'D3_EXTSEARCH_STAT_TYPES_OWNIS'                   => 'own search field (IS)',
    'D3_EXTSEARCH_STAT_TYPES_OWNBITSET'               => 'own search field (BITSET)',
    'D3_EXTSEARCH_STAT_TYPES_OWNVALUE'                => '%s => "%s"',
    'D3_EXTSEARCH_STAT_TYPES_ATTRIBUTE'               => 'attributes',
    'D3_EXTSEARCH_STAT_TYPES_INDEXLETTER'             => 'index letter',
    'D3_EXTSEARCH_STAT_TYPES_UNKNOWN'                 => 'unknown filter',
    'D3_EXTSEARCH_STAT_STATDESC_HITLESS'              => 'hitless searches in %s to "%s" ',
    'D3_EXTSEARCH_STAT_STATDESC_MOSTSEARCHES'         => 'searches in %s to "%s" ',
    'D3_EXTSEARCH_STAT_NOITEMS'                       => 'there are no items for your search',
    'D3_EXTSEARCH_STAT_NOITEMS_DESC'                  => 'If you have expected data here, please check whether statistics collection is activated appropriately in the module settings.',
    'D3_EXTSEARCH_STAT_SELECTFILTER'                  => 'Set the desired filter and send your selection to get results.',

    'D3_EXTSEARCH_PLUGIN_SETTINGS'                    => 'settings',
    'D3_EXTSEARCH_PLUGIN_SEARCHACTIVE'                => 'offer the user in the browser to install the search plugin',
    'D3_EXTSEARCH_PLUGIN_SEARCHACTIVE_DESC'           => 'In current browsers you will find in the upper right corner a possibility to start the most important search engines from anywhere on the Internet. Offer your customers to add your shop to this list too. So it is enough to select your shop in the drop-down box and enter the search term. Immediately your shop will be shown with the search hits. Your shop title is used as description text, you can define an icon below.',
    'D3_EXTSEARCH_PLUGIN_INSTALLLINK'                 => 'show an installation link in the shop search',
    'D3_EXTSEARCH_PLUGIN_INSTALLLINK_DESC'            => 'If your customer can add your shop to the search engine list, this is indicated in the browser by a colored border. However, this is not very noticeable, many users missed this out. It\'s better to add an additional link in the search results to indicate this feature.',
    'D3_EXTSEARCH_PLUGIN_SEARCHICON'                  => 'Icon for browser plugin',
    'D3_EXTSEARCH_PLUGIN_CHOOSEICON'                  => 'Please choose an icon.',
    'D3_EXTSEARCH_PLUGIN_SEARCHICON_DESC'             => 'Define the icon which should be displayed in the browser plugin. The icon must have a size of 16 x 16 pixels and be available in PNG or JPG format.',
    'D3_EXTSEARCH_PLUGIN_SAVE'                        => 'save',
    'D3_EXTSEARCH_PLUGIN_GENERATE'                    => 'generation',
    'D3_EXTSEARCH_PLUGIN_GENERATE_DESC'               => 'If you have changed your shop title, set a new icon or even moved your shop to a new address, it is necessary to update the search plugin. Please also advise your customers to update the plugin. It does not renew itself automatically.',
    'D3_EXTSEARCH_PLUGIN_STARTGENERATING'             => 'start Creation',
    'D3_EXTSEARCH_PLUGIN_GENERATEFILE'                => 'Create installation file:',
    'D3_EXTSEARCH_PLUGIN_GENERATENOTICE'              => 'With the creation of the installation file you have completed all necessary steps. If your customer starts the integration, this file is automatically read from your server.',
    'D3_EXTSEARCH_PLUGIN_CREATE_SUCC'                 => 'Plugin file was generated successfully.',
    'D3_EXTSEARCH_PLUGIN_CREATE_NSUCC'                => 'Plugin file could not be created.',

    'D3_EXTSEARCH REPORT_MOSTSEARCHES'                => 'Search terms (only available in search module)',
    'D3_EXTSEARCH_STATISTIC_MOSTSEARCHES'             => 'most common search terms',
    'D3_EXTSEARCH_STATISTIC_MOST_DESC'                => 'So often the chosen term was searched',
    'D3_EXTSEARCH_STATISTIC_FURTHERFILTERS'           => '(limited by further filters)',
    'D3_EXTSEARCH_STATISTIC_GRAPH'                    => 'graphical analysis',

    'D3_EXTSEARCH_CONTENT_SEARCHABLE'                 => '<img src="../modules/d3/modcfg/public/d3logo.php" alt="D³" title="D³ Data Development"> CMS is searchable',
    'D3_EXTSEARCH_PUSH'                               => '<img src="../modules/d3/modcfg/public/d3logo.php" alt="D³" title="D³ Data Development"> importance of these article in the whole assortment',
    'D3_EXTSEARCH_PUSH_1'                             => 'normal',
    'D3_EXTSEARCH_PUSH_2'                             => 'important',
    'D3_EXTSEARCH_PUSH_3'                             => 'very important',
    'D3_EXTSEARCH_PUSH_DESC'                          => 'D³ Modul "extended Suche": The importance defines the first order of the articles in the search (when using the "extended search"). In combination with field relevance, importance functions as a factor. For example, particularly important articles have the 3 times relevance of normally weighted articles. Note this also when assigning the field relevance.',

    'D3_EXTSEARCH_ATTRIBUTE_NOTUSE4FILTER'            => 'DO NOT use attribute for filter',
    'D3_EXTSEARCH_ATTRIBUTE_NOTUSE4FILTER_DESC'       => 'Certain attributes can be excluded from the filter list if, for example, they are only used for article management.',
    'D3_EXTSEARCH_ATTRIBUTE_USECORRESPONDINGVALUES'   => 'adds corresponding attribute values',
    'D3_EXTSEARCH_ATTRIBUTE_USECORRESPONDINGVALUES_DESC' => '<p>If synonyms are set for the selected attribute value in the synonym editor, they are added to the selection without the customer having to select them explicitly.</p><p>This is useful, for example, for identical or very similar values (e.g. clothing sizes in the EU and US formats).</p>',
    'D3_EXTSEARCH_CATEGORY_NOTUSE4FILTER'             => 'DO NOT use category for filters and category results',

    'D3_EXTSEARCH_SYNED_NOLEXICON'                    => 'The semantic lexicon isn\'t installed! Please check manual for further informations.',
    'D3_EXTSEARCH_SYNED_WORD'                         => 'word',
    'D3_EXTSEARCH_SYNED_WORD_DESC'                    => 'Search for a specific term, enter it here and submit.',
    'D3_EXTSEARCH_SYNED_ALTWORD'                      => 'same meaning words',
    'D3_EXTSEARCH_SYNED_SYNSETID'                     => 'Synonym ID',
    'D3_EXTSEARCH_SYNED_SYNSETID_DESC'                => 'Search for a specific synonym ID, enter it here and submit.',
    'D3_EXTSEARCH_SYNED_SAVENEWSYN'                   => 'save new synonym',
    'D3_EXTSEARCH_SYNED_SAVENEWSYN_DESC'              => 'Define another term for the chosen meaning here.',
    'D3_EXTSEARCH_SYNED_DELETESYN'                    => 'Should the synonym really be deleted?',

    'D3_EXTSEARCH_SYNED_MAIN_NEWWORD'                 => 'New term / phrase',

    'D3_EXTSEARCH_SYNED_MAIN_WORD'                    => 'term / phrase:',
    'D3_EXTSEARCH_SYNED_MAIN_WORD_DESC'               => 'If you would like to create suitable terms for a new word meaning, note the first term here. Insert the term here only if the word meaning does not yet exist in the lexicon. Otherwise, enter the new term in the appropriate meaning in the "Edit synonyms" tab.',
    'D3_EXTSEARCH_SYNED_MAIN_COMMENT'                 => 'comment:',
    'D3_EXTSEARCH_SYNED_MAIN_COMMENT_DESC'            => 'The comment serves exclusively to make further internal explanations to the term. It is not used for the search.',
    'D3_EXTSEARCH_SYNED_MAIN_SYNSETID'                => 'Synonym ID:',
    'D3_EXTSEARCH_SYNED_MAIN_SYNSETID_DESC'           => 'In a uniform synonym ID, all terms with the same meaning are stored. New entries will automatically be assigned a new ID. If a term has been mistakenly assigned the wrong meaning, choose the synonym ID from the appropriate meaning and change it to your term.',
    'D3_EXTSEARCH_SYNED_MAIN_LANGUAGE'                => 'language:',
    'D3_EXTSEARCH_SYNED_MAIN_LANGUAGE_DESC'           => 'Determine from this, from which language the selected term originates and in which this is to be used. Only the languages activated in the shop are available.',
    'D3_EXTSEARCH_SYNED_MAIN_LANGUAGE_DISABLED'       => '(disabled)',
    'D3_EXTSEARCH_SYNED_MAIN_SYNONYMUSE'              => 'Synonym is used',
    'D3_EXTSEARCH_SYNED_MAIN_SYNONYMUSEFORTERMS'      => 'to supplement the search terms',
    'D3_EXTSEARCH_SYNED_MAIN_SYNONYMUSEFORTERMS_DESC' => 'If the synonym use is activated in the module basic settings, this synonym is used when the shop visitor searches for one of the other assigned terms. For example, regional terms can be made searchable without having to maintain them on all articles.',
    'D3_EXTSEARCH_SYNED_MAIN_SYNONYMUSEFORATTRIBUTES' => 'for corresponding attribute values',
    'D3_EXTSEARCH_SYNED_MAIN_SYNONYMUSEFORATTRIBUTES_DESC' => 'If corresponding values are activated for some attributes, this synonym is also used when filtering by one of the other assigned terms. For example, you can search for country-specific clothing sizes.',

    'D3_EXTSEARCH_SYNED_MANAGE_DESC'                  => 'The synonyms shown here are alternative terms for the meaning chosen above.',
    'D3_EXTSEARCH_SYNED_MANAGE_EDIT'                  => 'edit',
    'D3_EXTSEARCH_SYNED_MANAGE_EDIT_DESC'             => 'If you want to add additional details to the term or assign it to a different meaning, click on the symbol. The admin area changes to the editing area for exactly the term.',
    'D3_EXTSEARCH_SYNED_MANAGE_SYNONYM'               => 'Synonym',

    'D3_EXTSEARCH_SETTINGS'                           => 'Settings for <img src="../modules/d3/modcfg/public/d3logo.php" alt="D3" title="D3 Data Development"> Extended Search',
    'D3_EXTSEARCH_SETTINGS_DESC'                      => 'Use requires activated module',
    'tbclattribute_extsearch'                         => 'Search and filter settings',
    'D3_EXTSEARCH_ASSIGNCATEGORIES'                   => 'assign filterable categories',
    'D3_EXTSEARCH_ASSIGNCATEGORIES_DESC'              => 'If the selected attribute should only be shown for filtering at certain categories, assign these categories here. Without an assignment, the attribute is used for filtering in all categories in which corresponding articles are available. <br> <br> The assignment only works if the attribute is not always excluded from being used as a filter (Manage Articles -> Attributes -> Search and Filter Settings -> Attribute is NOT used in Filter Result Lists) and the use of this custom mapping has been enabled in the Basic Module Settings (D3 Modules -> Extended Search -> Preferences -> Filter + Display -> Attribute Filter -> Use attribute activation per category, manufacturer and vendor).',
    'D3_EXTSEARCH_ASSIGNMANUFACTURERS'                => 'assign filterable manufacturers',
    'D3_EXTSEARCH_ASSIGNMANUFACTURERS_DESC'           => 'If the selected attribute should only be shown for filtering at certain manufacturers, assign these manufacturer here. Without an assignment, the attribute is used for filtering in all manufacturers in which corresponding articles are available. <br> <br> The assignment only works if the attribute is not always excluded from being used as a filter (Manage Articles -> Attributes -> Search and Filter Settings -> Attribute is NOT used in Filter Result Lists) and the use of this custom mapping has been enabled in the Basic Module Settings (D3 Modules -> Extended Search -> Preferences -> Filter + Display -> Attribute Filter -> Use attribute activation per category, manufacturer and vendor).',
    'D3_EXTSEARCH_ASSIGNVENDORS'                      => 'assign filterable vendors',
    'D3_EXTSEARCH_ASSIGNVENDORS_DESC'                 => 'If the selected attribute should only be shown for filtering at certain vendors, assign these vendor here. Without an assignment, the attribute is used for filtering in all vendors in which corresponding articles are available. <br> <br> The assignment only works if the attribute is not always excluded from being used as a filter (Manage Articles -> Attributes -> Search and Filter Settings -> Attribute is NOT used in Filter Result Lists) and the use of this custom mapping has been enabled in the Basic Module Settings (D3 Modules -> Extended Search -> Preferences -> Filter + Display -> Attribute Filter -> Use attribute activation per category, manufacturer and vendor).',
    'tbclcategory_extsearch'                          => 'Search and filter settings',
    'D3_EXTSEARCH_AJAX_ALLCATEGORIES'                 => 'All categories',
    'D3_EXTSEARCH_AJAX_SETCATEGORIES'                 => 'Assigned categories',
    'D3_EXTSEARCH_AJAX_ALLMANUFACTURERS'              => 'All manufacturers',
    'D3_EXTSEARCH_AJAX_SETMANUFACTURERS'              => 'Assigned manufacturers',
    'D3_EXTSEARCH_AJAX_ALLVENDORS'                    => 'All vendors',
    'D3_EXTSEARCH_AJAX_SETVENDORS'                    => 'Assigned vendors',

    'GENERAL_AJAX_SORT_D3NOTUSE4FILTER'               => 'not useable for filters',
    'GENERAL_AJAX_SORT_OXSHORTDESC'                   => 'shortdescription',

    'D3_EXTSEARCH_UPDATE_GENPHONETIC'                 => '"extended search": The module update made changes in the database structure for the similarity search. Therefore, after completing this installation, update the search index in the admin area of the module.',

    'GENERAL_ARTICLE_D3_PHONETIC'                     => 'extSearch - phonetic index', // Multilang-Fields for importer
    'GENERAL_ARTICLE_D3_SEARCHINDEXDATE'              => 'extSearch - date of last search index generating', // Multilang-Fields for importer
    'GENERAL_ARTICLE_D3PUSH'                          => 'extSearch - product importance', // Multilang-Fields for importer
    'GENERAL_ARTICLE_D3CONTENTHASH'                   => 'extSearch - hash of indexed contents', // Multilang-Fields for importer
    'GENERAL_ARTICLE_OXVARSELECT'                     => 'variant title',

    'D3_EXTSEARCH_CLI_COMMON_RUNFROMCLI'              => 'This script has to be run from the command line',
    'D3_EXTSEARCH_CLI_COMMON_UNVALIDSHOPID'           => 'unvalid shop id',
    'D3_EXTSEARCH_CLI_COMMON_NOGENERATORSCRIPT'       => 'No generation language defined, please set it in the module settings.',
    'D3_EXTSEARCH_CLI_HELP'                           => 'Enables automated tasks / maintenance of the "extended search" module.',
    'D3_EXTSEARCH_CLI_OPTION_VERSION'                 => 'print version',
    'D3_EXTSEARCH_CLI_OPTION_QUIET'                   => 'prevents output from being displayed',
    'D3_EXTSEARCH_CLI_OPTION_LANG'                    => 'optional - language of the output messages, possible values are: "%1$s"',
    'D3_EXTSEARCH_CLI_OPTION_HELP'                    => 'Display this help screen and exit immeadiately.',
    'D3_EXTSEARCH_CLI_OPTION_NOCOLORS'                => 'Do not use any colors in output. Useful when piping output to other tools or files.',
    'D3_EXTSEARCH_CLI_OPTION_LOGLEVELS'               => 'Minimum level of messages to display. Default is "info". Valid levels are: "debug", "info", "notice", "success", "warning", "error", "critical", "alert", "emergency".',
    'D3_EXTSEARCH_CLI_COMMAND'                        => 'This tool accepts a command as first parameter as outlined below:',
    'D3_EXTSEARCH_CLI_COMMAND_GENERATEINDEX'          => 'Generate outdated phonetic search index',
    'D3_EXTSEARCH_CLI_COMMAND_GENERATESEMANTIC'       => 'Reindex lexicon for a search with the same meaning',
    'D3_EXTSEARCH_CLI_COMMAND_FIXARTEXTENDS'          => 'Clean up long text table',
    'D3_EXTSEARCH_CLI_ARGUMENT_SHOPID'                => 'ID of the selected shop, possible values are: "%1$s"',
    'D3_EXTSEARCH_CLI_ARGUMENT_ENCLOSER'              => '", "',
    'D3_EXTSEARCH_CLI_GENERATOR_PROCESSING'           => 'processing ...',
    'D3_EXTSEARCH_CLI_GENERATOR_PROCESSED'            => '%1$s article language(s) (ca. %2$s article(s)) edited - generation completed!',
    'D3_EXTSEARCH_CLI_GENERATOR_TERMPROCESSED'        => '%1$s word(s) edited - generation completed!',
    'D3_EXTSEARCH_CLI_FINISHED_SUCCFESSFULLY'         => 'script successfully finished',

);
