<?php

/**
 * This Software is the property of Data Development and is protected
 * by copyright law - it is NOT Freeware.
 *
 * Any unauthorized use of this software without a valid license
 * is a violation of the license agreement and will be prosecuted by
 * civil and criminal law.
 *
 * http://www.shopmodule.com
 *
 * @copyright (C) D3 Data Development (Inh. Thomas Dartsch)
 * @author    D3 Data Development - Daniel Seifert <support@shopmodule.com>
 * @link      http://www.oxidmodule.com
 */

$sLangName = "English";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(

//Navigation
    'charset'                                         => 'UTF-8',
    'd3mxextsearch'                                   => '<i class="fa fa-search-plus"></i> Extended Search',
    'd3mxextsearch_settings'                          => 'Settings',
    'd3mxextsearch_statistic'                         => 'Statistic',
    'd3mxextsearch_syneditor'                         => 'Synonym Editor',
    'd3tbclextsearch_syneditor_main'                  => 'Main',
    'd3tbclextsearch_syneditor_manage'                => 'Edit synonyms',
    'd3tbclextsearch_syneditor_family'                => 'Synonym family',
    'd3tbclextsearch_syneditor_synset'                => 'Edit synonym group',
    'd3tbclextsearch_settings_results'                => 'Base Settings',
    'd3tbclextsearch_settings_navigation'             => 'Filters + Display Settings',
    'd3tbclextsearch_settings_quick'                  => 'Suggest Search',
    'd3tbclextsearch_settings_browser'                => 'Browser Plugins',
    'd3tbclextsearch_settings_content'                => 'Content Search',
    'd3tbclextsearch_settings_statistik'              => 'Statistic',

    'D3_EXTSEARCH_LIST_SETTLANG'                      => 'settings for language',
    'D3_EXTSEARCH_HELPLINK'                           => 'Fragen-zu-speziellen-Modulen/Erweiterte-Suche/',
    'D3_EXTSEARCH_HELPLINK_CONFIG'                    => '',

    'D3_EXTSEARCH_TRANSL'                             => 'Extended Search',

    'D3_EXTSEARCH_CONFIGVARS_SADDTITLE'               => 'module edition:',
    'D3_EXTSEARCH_CONFIGVARS_BLUSEFILTERINARTICLELISTS' => 'filters in article lists available:',
    'D3_EXTSEARCH_CONFIGVARS_FEATUREBIT1'             => 'filters in article lists available:',

    'D3_EXTSEARCH_MAIN_DEBUGACTIVE_DESC'              => 'Debug mode outputs the used database queries for easier programming and debugging in the frontend. Be sure to deactivate it for live operation, as debug mode does not use database caching.',
    'D3_EXTSEARCH_MAIN_MAINSETTINGS'                  => 'Common Settings',
    'D3_EXTSEARCH_MAIN_FIELDLIST'                     => 'these fields will used in similar and quicksearch<br>relevance => field name (example.: 50 => oxtitle)',
    'D3_EXTSEARCH_MAIN_SORTDEBUG'                     => 'result field analysis',
    'D3_EXTSEARCH_MAIN_SORTDEBUG_DESC'                => 'Insert your search term. <br>In the table you\'ll get all relevance values according to every field, which fits to the hit. You can change all relevance values "_IN_" in the "extended search" settings. "D3PUSH" is the articles importance. The relevance for each article in the result list ("d3Priority") is calculated by this formula: <blockquote>((sum from all "_IN_" fields) x D3PUSH) + D3PUSH</blockquote>..._PART_IN_... - search term is contained as part in content of these field<br>..._WORD_IN_... - search term is a single word in these field',
    'D3_EXTSEARCH_MAIN_SORTDEBUG_START'               => 'start search',
    'D3_EXTSEARCH_MAIN_NOFIELDSDEFINED'               => '<b>There are no fields defined.</b><br>Standard: \'oxtitle\', \'oxsearchkeys\' and \'oxartnum\'',
    'D3_EXTSEARCH_MAIN_FIELDLIST_DESC'                => 'Enter the article table fields used in the search here. The field names can be found in the shop database. If you change these entries, the search index must be recreated again. <br> <br> Before the field names, enter the relevance of the relevant field with => separated. The higher the relevance, the higher an article will be shown if the search term occurs in this field (to be activated separately). If the search term is found in several fields, the relevance adds up. If no relevance is specified, the field automatically receives the value 10.',
    'SHOP_CONFIG_SEARCHFIELDS'                        => 'Fields to be considered in Search<br>"extended search" use own settings / edit in <input type="button" onclick="document.getElementById(\'myedit\').target = \'basefrm\'; document.getElementById(\'myedit\').fnc.value=\'\';document.getElementById(\'myedit\').cl.value=\'d3_cfg_extsearch_main\';document.getElementById(\'myedit\').submit();" value="extended search">',
    'SHOP_CONFIG_SEARCHUSEAND'                        => 'If several search terms are entered, all search terms must appear in a search result (AND). (If the option is not active, only one search term must occur (OR).)',
    'D3_EXTSEARCH_MAIN_PUTINLEAVEOUT'                 => 'allow included and excluded letters in search string',
    'D3_EXTSEARCH_MAIN_PUTINLEAVEOUT_DESC'            => 'This option also searches for items whose text contains one more letter (inserted) or less (omitted). However, this can also increase the number of hits and soften the result. This setting has no effect on singular <-> plural hits.',
    'D3_EXTSEARCH_MAIN_MULIPLEWORDS'                  => 'use of multiple search words',
    'D3_EXTSEARCH_MAIN_MULIPLEWORDS_DESC'             => 'If it makes sense that even with multiple search words these are only searched in context, you can activate this here. Otherwise, each of the search words may occur separately and without a link in the results. In syntax mode, the user can designate the mode himself by quoting contiguous words and / or restricting them with plus or minus signs.',
    'D3_EXTSEARCH_MAIN_MULIPLEWORDS_SINGLE'           => 'every word will searched separatly',
    'D3_EXTSEARCH_MAIN_MULIPLEWORDS_WHOLE'            => 'will used as complete string',
    'D3_EXTSEARCH_MAIN_MULIPLEWORDS_SYNTAX'           => 'user controlled by search syntax',
    'D3_EXTSEARCH_MAIN_SORTING'                       => 'Article Sorting',
    'D3_EXTSEARCH_MAIN_ORDERBYPRIORITY'               => 'sort hits by relevance',
    'D3_EXTSEARCH_MAIN_ORDERBYPRIORITY_DESC'          => 'Relevance defines how well a found article matches the search term. (Therefore, relevance sorting is only available in the search, but not available in categories.) <br> If the customer has not selected their own sort, the search hits are sorted by field relevance. You determine the relevance to the database fields defined for the search. The sum of the relevance of the fields containing the search term is then used as a sorting criterion. In conjunction with the importance of the articles (to be activated separately) the relevance can multiply. <br> <br> Formula: <br> Sorting = Relevance Sum * Importance + Importance',
    'D3_EXTSEARCH_MAIN_ORDERBYPUSH'                   => 'sort hits by importance',
    'D3_EXTSEARCH_MAIN_ORDERBYPUSH_DESC'              => 'Importance defines the referral position of an item within your entire assortment. <br> If the customer has not chosen their own sort order, the search hits are sorted by importance. The importance you attach to each article. Without activated field relevance, the importance is the only sorting criterion. In connection with field relevance, the importance acts as a multiplier. Hits in low-priority fields in important articles can set them against unimportant articles with high field relevance and reverse the order if necessary. <br> <br> Formula: <br> Sorting = Relevance Sum * Importance + Importance',
    'D3_EXTSEARCH_MAIN_ORDERBYALTERNATIVE'            => 'additional sorting with identical relevance sort value',
    'D3_EXTSEARCH_MAIN_ORDERBYALTERNATIVE_DESC'       => 'The sort order is calculated based on the settings set here for each item. If several articles have an identical sorting value, they can be sorted among themselves according to a further criterion. The name of a field of the article table is allowed here (without language addition). Use asc and desc to set whether to sort in ascending or descending order.',
    'D3_EXTSEARCH_MAIN_VARIANTSETTINGS'               => 'Variant Search',
    'D3_EXTSEARCH_MAIN_VARIANTSEARCH'                 => 'shop search for variant articles too',
    'D3_EXTSEARCH_MAIN_VARIANTUSAGE'                  => 'if an article variant is found, show ...',
    'D3_EXTSEARCH_MAIN_VARIANTUSAGE_SHOWPARENT'       => '... there parent article in list',
    'D3_EXTSEARCH_MAIN_VARIANTUSAGE_SHOWVARIANT'      => '... the variant itself in list',
    'D3_EXTSEARCH_MAIN_VARIANTCHECKPARENTACTIVE'      => 'check parent article active status explicitly',
    'D3_EXTSEARCH_MAIN_VARIANTUSAGE_DESC'             => 'When displaying the parents article instead of the variant please note that the parents article must also be active and selectable. An additional check on it deliberately does not take place, because this would falsify the search result.',
    'D3_EXTSEARCH_MAIN_VARIANTSEARCH_DESC'            => 'Instead of searching for regular articles as usual, the shop also finds individual variant articles with this option. Please also enter \'oxvarselect\' in the field list and regenerate the search index.',
    'D3_EXTSEARCH_MAIN_VARIANTCHECKPARENTACTIVE_DESC' => 'Only used if variants are shown as hits. Normally, there should be no active variants to an inactive parent. If, for some reason, this constellation still occurs in your store, you can use this option to enable explicit checking for active parent items. Note that this option requires a lot of processing power. Alternatively, make the variant articles better inactive.',
    'D3_EXTSEARCH_MAIN_OWNFORMFIELDS'                 => 'check for individual filter form fields',
    'D3_EXTSEARCH_MAIN_OWNFORMFIELDS_DESC'            => 'Extend the search form with further filter options. In order to use these as well, this checkbox must be set. Detailed explanations of further search fields can be found in the documentation folder of the module.',
    'D3_EXTSEARCH_MAIN_LOGSETTINGS'                   => 'Statistic',
    'D3_EXTSEARCH_MAIN_LOGHITLESS'                    => 'log resultless searches in statistic',
    'D3_EXTSEARCH_MAIN_LOGHITLESS_DESC'               => 'If the customer starts a search query that can not provide results, the search terms are recorded for you. You will find the list under the \'Logging\' tab and can also optimize your products for these terms.',
    'D3_EXTSEARCH_MAIN_LOGFORSEARCH'                  => 'log all search queries in statistic',
    'D3_EXTSEARCH_MAIN_LOGFORSEARCH_DESC'             => 'logs all searches for the in-module statistics. This setting can also be set without other shop functions being logged. If the shop-wide logging is activated, the search queries are generally written.',
    'D3_EXTSEARCH_MAIN_PHONETICS'                     => 'Phonetic Search (search for similar sound)',
    'D3_EXTSEARCH_MAIN_SIMILARSEARCH'                 => 'if there is no search result, shop search for similar-sounding articles (e.g.: search: <i>Pflan<b>s</b>e</i>, result: <i>Pflan<b>z</b>e</i>)',
    'D3_EXTSEARCH_MAIN_SIMILARSEARCH_DESC'            => 'Here you activate (or deactivate) the phonetic search. For example, this will catch you from typing errors in the search query, and the customer will most likely find your desired articles. If at the same time the search for meaning (semantic) is activated, it is first tried to find matching matches. If this fails, hits are determined by the sound search.',
    'D3_EXTSEARCH_MAIN_PHONETICLANG'                  => 'for similar search used language',
    'D3_EXTSEARCH_MAIN_PHONETICLANG_DESC'             => 'Since the different human languages differ in their pronunciation and in the word or letter composition, a language-dependent index generation process is necessary for an optimal search result. If you mainly use a language other than the ones shown in your shop, please ask us if a module for your language is also available.',
    'D3_EXTSEARCH_MAIN_SIMILAREXTLIST_1'              => 'shop show additional similar-sounding articles, if regular search contains max.',
    'D3_EXTSEARCH_MAIN_SIMILAREXTLIST_2'              => 'results',
    'D3_EXTSEARCH_MAIN_SIMILAREXTLIST_DESC'           => 'If the search scores only a few hits, you can also provide the customer with similar items. These similar items are shown in the result list after the actual matches. The customer will be informed with a message about the filled-in list. Please use this setting wisely, as the additional hits could confuse the customers.',
    'D3_EXTSEARCH_MAIN_MINPHONLENGTH'                 => 'result precision on short search terms',
    'D3_EXTSEARCH_MAIN_MINPHONLENGTH_LESS'            => 'less precision',
    'D3_EXTSEARCH_MAIN_MINPHONLENGTH_REG'             => 'normal precision',
    'D3_EXTSEARCH_MAIN_MINPHONLENGTH_MORE'            => 'more precision',
    'D3_EXTSEARCH_MAIN_MINPHONLENGTH_DESC'            => 'For a meaningful hit list a sufficiently long search term is necessary. The more accurate you set this setting, the more accurate the hits.',
    'D3_EXTSEARCH_MAIN_SEMANTICS'                     => 'Semantic Search (search for similar type)',
    'D3_EXTSEARCH_MAIN_SEMANTICSEARCH'                => 'shop search for articles with similar sense (e.g.: search: <i>Gew&auml;chs</i>, result: <i>Pflanze</i>)',
    'D3_EXTSEARCH_MAIN_SEMANTICSEARCH_MISSING'        => 'shop search for articles with similar sense (e.g.: search: <i>Gew&auml;chs</i>, result: <i>Pflanze</i>)<br><b>Semantic lexicon isn\'t installed!</b>',
    'D3_EXTSEARCH_MAIN_SEMANTICSEARCH_DESC'           => 'Check this box to enable a same meaning search in the shop. By e.g. regional differences may cause your customers to label an item differently, but they may mean your product. If the customer now types in his request, he or she will be shown the terms that better describe the desired product in your shop. <br> The same meaning search is used for article content and category names.',
    'D3_EXTSEARCH_MAIN_SEMANTICUSEPHONETIC'           => 'if the search term contains spelling errors, in addition to the search for meaning, the correct spelling is tried; however, may produce strongly deviant hits; requires activated phonetic search',
    'D3_EXTSEARCH_MAIN_SEMANTICUSEPHONETIC_DESC'      => 'This setting also allows the same meaning search for the phonetic search, if no similar words are found. However, since the desired meaning is not clear, under certain circumstances strongly deviating hits are shown. We recommend using this setting only to a limited extent.',
    'D3_EXTSEARCH_MAIN_SAVE'                          => 'save',
    'D3_EXTSEARCH_MAIN_INDEX'                         => 'Search Index',
    'D3_EXTSEARCH_MAIN_INDEXARTCNT'                   => 'articles per work up run for index',
    'D3_EXTSEARCH_MAIN_INDEXARTCNT_DESC'              => 'The web server aborts scripts after a certain period of time for security reasons. In order to be able to finish the generation of the search index nevertheless, this script processes only a certain number of articles and then restarts. Define here how many articles should be processed in one go. If the generation terminates with an error, reduce the number. The lower the number, the longer the script needs.',
    'D3_EXTSEARCH_MAIN_INDEXERR'                      => 'The required index for the fault-tolerant search is incomplete. Click here to regenerate the list:',
    'D3_EXTSEARCH_MAIN_INDEXNOERR'                    => 'The required index for the fault-tolerant search seems to be complete. At the moment, no action is necessary if you have not changed the language or have imported articles. <br> The index must be created separately for each language of the shop.',
    'D3_EXTSEARCH_MAIN_GENINDEXCMPL'                  => 'Generate search index completely',
    'D3_EXTSEARCH_MAIN_GENINDEXCMPL_DESC'             => 'Generates the search index for all existing articles in the shop. This may take longer.',
    'D3_EXTSEARCH_MAIN_GENINDEXNEW'                   => 'Include new articles in search index',
    'D3_EXTSEARCH_MAIN_GENINDEXNEW_DESC'              => 'Click the adjoining button to include all items that have been modified or added since the last indexing in the search index. All previous articles are ignored.',
    'D3_EXTSEARCH_MAIN_GENSEMANTICINDEX'              => 'Reindex lexicon for same meaning search',
    'D3_EXTSEARCH_MAIN_GENSEMANTICINDEX_DESC'         => 'For the connection of same meaning search and phonetic search also the lexicon needs the phonetic index. With this button you start the reindexing of the lexicon. Normally this is not necessary.',
    'D3_EXTSEARCH_MAIN_SHOW_POPUP'                    => 'show popup while searching',
    'D3_EXTSEARCH_MAIN_CATEGORY'                      => 'Search in category titles',
    'D3_EXTSEARCH_MAIN_CATEGORY_SEARCH'               => 'search in category titles too and show containing articles',
    'D3_EXTSEARCH_MAIN_CATEGORY_ANDOR_DESC'           => 'This setting is only used for searching in category names. There is a separate setting for the article search.',
    'D3_EXTSEARCH_MAIN_CATEGORY_ARTHANDLING'          => 'Show category yourself or their products',
    'D3_EXTSEARCH_MAIN_CATEGORY_ARTINCAT'             => 'Show articles from category',
    'D3_EXTSEARCH_MAIN_CATEGORY_CATINLIST'            => 'Show category for selection',
    'D3_EXTSEARCH_MAIN_CATEGORY_PRIORITY'             => 'relevance at category results',
    'D3_EXTSEARCH_MAIN_CATEGORY_PRIORITY_DESC'        => 'Category hits get this relevance when relevance sorting is enabled. Here, this number is related to the field relevance (see separate setting).',
    'D3_EXTSEARCH_MAIN_MANUFACTURER'                  => 'Search in brand and vendor titles',
    'D3_EXTSEARCH_MAIN_MANUFACTURER_SEARCH'           => 'search in brand and vendor titles too and show assigned articles',
    'D3_EXTSEARCH_MAIN_MANUFACTURER_ANDOR_DESC'       => 'This setting is only used for the search in brand and vendor names. There is a separate setting for the article search.',
    'D3_EXTSEARCH_MAIN_MANUFACTURER_PRIORITY'         => 'relevance at brand / vendor results',
    'D3_EXTSEARCH_MAIN_MANUFACTURER_PRIORITY_DESC'    => 'Brand / vendor hits receive this relevance when relevance sorting is enabled. Here, this number is related to the field relevance (see separate setting).',
    'D3_EXTSEARCH_MAIN_ADMINPANEL'                    => 'Admin Panel',
    'D3_EXTSEARCH_MAIN_ADMINSHOWVARIANTS'             => 'in searchresults show variants in article list too',
    'D3_EXTSEARCH_MAIN_USEARTNUMSEARCH'               => 'perform a specialized artnum search',
    'D3_EXTSEARCH_MAIN_USEARTNUMSEARCH_DESC'          => 'With this setting, articles that have the search term as article number are searched for before the actual search.',
    'D3_EXTSEARCH_MAIN_DONTUSEOWNDBVIEWS'             => 'Database queries <b> do not </b> use the module-specific view tables',
    'D3_EXTSEARCH_MAIN_DONTUSEOWNDBVIEWS_DESC'        => 'For performance reasons, the search does not use the system-specific view tables, but comes with optimized versions of it. Depending on the size of the database, their use can speed the speed of database queries up to a factor of 100. If you do <b>not</b> want to use the specialized view tables, check this box. The queries are then routed through the on-look view tables. <br> Note that disabling this option requires the view tables to be updated again.',
    'D3_EXTSEARCH_MAIN_GENERATOR_INCONSISTENTTABLE'   => 'The database article table is inconsistent to longtext table. Please fix it before executing this generator.<br><br>For further informations, check out our FAQ at <a href="%1$s" target="_new">%1$s</a>.',
    'D3_EXTSEARCH_MAIN_GENERATOR_FINISHED'            => 'Finished.',
    'D3_EXTSEARCH_MAIN_GENERATOR_NOTE'                => 'Notice',
    'D3_EXTSEARCH_MAIN_GENERATOR_PROCESSED'           => '%1$s article(s) processed<br>Finished!',
    'D3_EXTSEARCH_MAIN_GENERATOR_TERMPROCESSED'       => '%1$s term(s) processed<br>Finished!',
    'D3_EXTSEARCH_MAIN_GENERATOR_PROCESSING'          => 'Processing %1$s&#37;',
    'D3_EXTSEARCH_MAIN_GENERATOR_PROCESSING1'         => 'Processing: %1$s / %2$s article(s)',
    'D3_EXTSEARCH_MAIN_GENERATOR_PROCESSING3'         => 'Processing: %1$s / %2$s term(s)',
    'D3_EXTSEARCH_MAIN_GENERATOR_PROCESSING2'         => '%1$s&#37; finished',
    'D3_EXTSEARCH_MAIN_GENERATOR_WAIT'                => 'Please wait...',
    'D3_EXTSEARCH_MAIN_GENERATOR_CLOSEWND'            => 'close window',

    'D3_EXTSEARCH_NAVI_MAINSETTINGS'                  => 'Common Settings',
    'D3_EXTSEARCH_NAVI_DISPTYPE'                      => 'Type of filter display',
    'D3_EXTSEARCH_NAVI_DISPTYPE_LINKLIST'             => 'as link list',
    'D3_EXTSEARCH_NAVI_DISPTYPE_DROPDOWN'             => 'as dropdown list (requires java script)',
    'D3_EXTSEARCH_NAVI_DISPTYPE_DESC'                 => 'Here you set the display form of the category, supplier and brand lists. The drop-down lists save space in the display, but can be confusing for many entries. In addition, they need JavaScript from the customer. Alternatively, link lists are recommended, which can be restricted in their length. <br> Both forms of display can be edited in the template.',
    'D3_EXTSEARCH_NAVI_EMPTYSEARCH'                   => 'allow search without a term',
    'D3_EXTSEARCH_NAVI_EMPTYSEARCH_DESC'              => 'It may be useful to allow searches without a search term. It may be that the resulting hits are filtered by an additional setting or you want to build an extensive search form, which may not contain a freely definable search term.',
    'D3_EXTSEARCH_NAVI_CATFILTER'                     => 'Category Filter',
    'D3_EXTSEARCH_NAVI_CATLIST'                       => 'show category list',
    'D3_EXTSEARCH_NAVI_CATLIST_DESC'                  => 'Check the box to show your customer a selection of the affected categories for a comprehensive hit list. This allows him to restrict his search result targeted and improve it. The category name and the number of articles in the hit list are displayed.',
    'D3_EXTSEARCH_NAVI_CATLIST_SORT'                  => 'sort by',
    'D3_EXTSEARCH_NAVI_CATLIST_SORT_COUNT'            => 'count of related articles',
    'D3_EXTSEARCH_NAVI_CATLIST_SORT_DATA'             => 'defined sort',
    'D3_EXTSEARCH_NAVI_CATLIST_SORT_DESC'             => 'Define the criterion according to which the category list should be sorted. However, this has no influence on the presentation.',
    'D3_EXTSEARCH_NAVI_VENDORFILTER'                  => 'Vendor Filter',
    'D3_EXTSEARCH_NAVI_VENDORLIST'                    => 'show vendor list',
    'D3_EXTSEARCH_NAVI_VENDORLIST_DESC'               => 'Just as for the categories, there is also the option of filtering the hit list once again for the vendors. You switch this on here. This option is only available if you have generally activated the vendors in the shop and also allow a search for it. (\'Load and display vendor list\')',
    'D3_EXTSEARCH_NAVI_VENDORLIST_SORT'               => 'sort by',
    'D3_EXTSEARCH_NAVI_VENDORLIST_SORT_COUNT'         => 'count of related articles',
    'D3_EXTSEARCH_NAVI_VENDORLIST_SORT_ALPHA'         => 'alphabetical',
    'D3_EXTSEARCH_NAVI_VENDORLIST_SORT_DESC'          => 'Determine the display order in which the vendors should be listed.',
    'D3_EXTSEARCH_NAVI_MANUFACTURERFILTER'            => 'Brand Filter',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST'              => 'show brand list',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST_DESC'         => 'Just as for the categories, there is also the option of filtering the hit list again by manufacturer. You switch this on here. This option is only available if you have generally activated the manufacturers in the shop and also allow a search for them. (\'Load and display manufacturer list\')',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST_SORT'         => 'sort by',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST_SORT_COUNT'   => 'count of related articles',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST_SORT_ALPHA'   => 'alphabetical',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST_SORT_DESC'    => 'Determine the display order in which the manufacturers should be listed.',
    'D3_EXTSEARCH_NAVI_REDIRECTS'                     => 'Redirects',
    'D3_EXTSEARCH_NAVI_UNIQUEHIT'                     => 'at 1 article hit, shop goes directly to the detail page of the article',
    'D3_EXTSEARCH_NAVI_UNIQUEHIT_DESC'                => 'If your customer has searched so precisely that he has the desired information as the only one in the hit list, you can spare him the detour via the hit list and immediately supply him with the detail page of the article found.',
    'D3_EXTSEARCH_NAVI_UNIQUECONTENTHIT'              => 'at 1 CMS / text hit, shop changes directly to the CMS page',
    'D3_EXTSEARCH_NAVI_UNIQUECONTENTHIT_DESC'         => 'If the search result contains no articles, but a single CMS text, it will be redirected directly to the appropriate CMS page. The user leaves the search function of the shop, his search settings are then no longer available.',
    'D3_EXTSEARCH_NAVI_UNIQUEVENDORHIT'               => 'at 1 vendor hit, shop goes directly to the vendor page of the shop',
    'D3_EXTSEARCH_NAVI_UNIQUEVENDORHIT_DESC'          => 'If the search result does not contain any articles, but only one vendor, it will be forwarded directly to the appropriate vendor page of your shop. This option requires "Search by manufacturer and vendor name". The user leaves the search function of the shop, his search settings are then no longer available.',
    'D3_EXTSEARCH_NAVI_UNIQUEMANUFACTURERHIT'         => 'at 1 manufacturer, shop goes directly to the manufacturer page of the shop',
    'D3_EXTSEARCH_NAVI_UNIQUEMANUFACTURERHIT_DESC'    => 'If the search result contains no articles, but a single manufacturer, it will be forwarded directly to the appropriate manufacturer page of your shop. This option requires "Search by manufacturer and vendor name". The user leaves the search function of the shop, his search settings are then no longer available.',
    'D3_EXTSEARCH_NAVI_CONTENTS'                      => 'Information pages / CMS Texts',
    'D3_EXTSEARCH_NAVI_CONTENTLIST'                   => 'search in CMS pages',
    'D3_EXTSEARCH_NAVI_CONTENTLIST_DESC'              => 'In addition to articles, you can also search for correspondingly marked texts. To do this, place the appropriate check mark in the respective CMS blocks ("Customer Information> CMS Pages"). The texts are shown in the regular hit list. <br> <br> This option is also necessary if texts should also be shown in the suggest matches. Then set the corresponding option also in the tab "Suggest Search".',
    'D3_EXTSEARCH_NAVI_ATTRIBUTEFILTER'               => 'Attribute Filter',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST'                 => 'show attribute list',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_DESC'            => 'Set this option, if attributes can used for filtering. <br>Every attribute can excluded from usage on its setting page ("Administer Products > Attributes").',
    'D3_EXTSEARCH_NAVI_ATTRIBUTES_COMBINE'            => 'multiple attribute selection will combined via "OR"',
    'D3_EXTSEARCH_NAVI_ATTRIBUTES_COMBINE_DESC'       => 'Activate this option if, for example, you also want to show articles that have only one of the properties when the selected color and material have been selected. Without this option, only items that have both properties at the same time will be shown.',
    'D3_EXTSEARCH_NAVI_ATTRIBUTES_SORT'               => 'attributes sort by',
    'D3_EXTSEARCH_NAVI_ATTRIBUTES_SORT_POS'           => 'defined attribute position',
    'D3_EXTSEARCH_NAVI_ATTRIBUTES_SORT_TITLE'         => 'attribute title',
    'D3_EXTSEARCH_NAVI_ATTRIBUTES_SORT_DESC'          => 'Here you define the order of the displayed attributes.',
    'D3_EXTSEARCH_NAVI_ATTRIBUTEVALUES_COMBINE'       => 'multiple attribute value selections ("multi selection") will combined via "AND"',
    'D3_EXTSEARCH_NAVI_ATTRIBUTEVALUES_COMBINE_DESC'  => 'Activate this option, for example, if the selected color "red" and "green" only show items that have both colors at the same time. Without this option, articles with only one of the two properties will also be shown.',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_SORT'            => 'attribute values sort by',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_SORT_COUNT'      => 'count of related articles',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_SORT_POS'        => 'defined attribute list position',
    'D3_EXTSEARCH_NAVI_NOATTRIBUTEARTS'               => 'allow filter for articles, wich aren\'t assigned to this attribute',
    'D3_EXTSEARCH_NAVI_NOATTRIBUTEARTS_DESC'          => 'With this option, the attribute filters offer the option of filtering for items that are e.g. expressly assigned to no color or material.',
    'D3_EXTSEARCH_NAVI_SHOWNOTSELECTABLEATTRIBUTES'   => 'don\'t hide not selectable attribute values',
    'D3_EXTSEARCH_NAVI_SHOWNOTSELECTABLEATTRIBUTES_DESC' => 'Article filtering through attributes usually hides other attributes that can not be selected. For optical reasons, it may still be necessary to display them. With this option, these attribute values are listed by information, but they are greyed out. <br> Note that an additional data query is performed to determine these attributes. Depending on the item attribute structure, this may require extra loading time.',
    'D3_EXTSEARCH_NAVI_CONTENTSEARCHINLONGTEXT'       => 'search in CMS longtexts too',
    'D3_EXTSEARCH_NAVI_CONTENTLONG_DESC'              => 'Define whether the CMS blocks should also be searched in the long description texts.',
    'D3_EXTSEARCH_NAVI_SMALLLISTITEMS'                => 'Limit category, vendor, manufacturer and text lists <br> (customer can show all results on request, only works with "link lists")',
    'D3_EXTSEARCH_NAVI_SMALLLISTITEMS_2'              => ' entries',
    'D3_EXTSEARCH_NAVI_SMALLLISTITEMS_DESC'           => 'For many search hits, the list of categories, manufacturers, vendors and texts can be very long. The article hits may slip out of the display area. Limit the number of categories and manufacturers displayed to keep these lists short. If these lists are then actually shortened, your customer will have a button available to display these lists completely on request.',
    'D3_EXTSEARCH_NAVI_ALISTFILTER'                   => 'show filters in article lists too (e.g. category, brand, vendor)',
    'D3_EXTSEARCH_NAVI_ALISTFILTER_DESC'              => 'Article lists can also be restricted with filters. Filtering is possible in category views, manufacturer and vendor lists. Here you have category, manufacturer, supplier, attribute and price filters available. Options are the settings for the search. <br> If this entry is not selectable, this option is probably not included in your module license. Have your license extended for this.',
    'D3_EXTSEARCH_NAVI_PRICELIST'                     => 'show price steps',
    'D3_EXTSEARCH_NAVI_PRICEFILTER'                   => 'Price Filter',
    'D3_EXTSEARCH_NAVI_PRICELIST_DESC'                => 'All found articles are divided into price categories and offered as further filter criteria. Thus, the customer can choose a certain price range for his desired items. Discounts are not included in the category prices. Found articles are less expensive than the search request.',
    'D3_EXTSEARCH_NAVI_PRICELIST_ITEMS'               => 'maximum count of price steps',
    'D3_EXTSEARCH_NAVI_PRICELIST_ITEMS_DESC'          => 'So many price ranges are displayed at the maximum. Normally, however, this can be less, since empty price ranges (ie without contained articles) are filtered out.',
    'D3_EXTSEARCH_NAVI_PRICELIST_ROUNDED'             => 'price limits will rounded',
    'D3_EXTSEARCH_NAVI_PRICELIST_ROUNDED_DESC'        => 'The smallest price range starts at the lowest possible price, the largest price range extends to the highest price. The boundaries in between are calculated. However, these can sometimes be at odd amounts. With the option, the prices of the margins are rounded, but the margins are less meaningful.',
    'D3_EXTSEARCH_NAVI_PRICELIST_DISPLAY'             => 'price steps display type',
    'D3_EXTSEARCH_NAVI_PRICELIST_DISPLAY_DESC'        => 'The use of price ranges via sliders is not possible in mobile templates for reasons of usability. There, the price ranges are still shown as DropDown.',
    'D3_EXTSEARCH_NAVI_PRICELIST_DISPLAY_LISTTYPE'    => 'as dropdown',
    'D3_EXTSEARCH_NAVI_PRICELIST_DISPLAY_SLIDER'      => 'as jQuery slider',
    'D3_EXTSEARCH_NAVI_PRICELIST_REQU'                => '* jQuery slider requires installed jQuery framework in actual version (tried with version 1.4.2) with components "jQueryUI Core", "jQueryUI Widget", "jQueryUI Mouse" and "jQueryUI Slider".',
    'D3_EXTSEARCH_NAVI_HIGHLIGHT'                     => 'highlight found contents in search results',
    'D3_EXTSEARCH_NAVI_HIGHLIGHT_DESC'                => 'Sometimes the term you are looking for appears in the middle of descriptions. Use this option to visually highlight the term. <br> <br> To do so, set what the highlighting should look like in the template \'d3_ext_search_highlight.tpl\'. In \'inc/product.tpl\', replace all variables that should contain accents with the Smarty call \[\{d3_extsearch_highlight text=$variable name\}\], replacing $ variable-name with the actual text variable.',
    'D3_EXTSEARCH_NAVI_INDEXFILTER'                   => 'Index Letters',
    'D3_EXTSEARCH_NAVI_SHOWINDEX'                     => 'show index letters',
    'D3_EXTSEARCH_NAVI_SHOWINDEX_DESC'                => 'The letter index gives your customers the option of restricting the search hits further to the first letter. <br> <br> You can edit the letter list itself in the template \'d3_inc_ext_search.tpl\'.',
    'D3_EXTSEARCH_NAVI_FILTERFIELDNAME'               => 'used field name for index letter',
    'D3_EXTSEARCH_NAVI_FILTERFIELDNAME_DESC'          => 'All fields from the table oxarticles (without language addition) are possible here.',
    'D3_EXTSEARCH_NAVI_OWNFORMFIELDS'                 => 'individual filters',
    'D3_EXTSEARCH_NAVI_SAVE'                          => 'save',

    'D3_EXTSEARCH_QUICK'                              => 'suggest results',
    'D3_EXTSEARCH_QUICK_ACTIVE'                       => 'Suggestions are provided when the search term is entered (only displayed to users with JavaScript enabled)',
    'D3_EXTSEARCH_QUICK_ACTIVE_DESC'                  => '<img src="../modules/d3/extsearch/out/admin/img/d3_extsearch_quicksearch.jpg"><br>Give your customer the opportunity to find items even faster. The suggest search already represents the first hits in a separate frame while entering the search term. <br> In mobile views, the quick hit list can not be shown for reasons of operability.',
    'D3_EXTSEARCH_QUICK_FULLOBJECTS'                  => 'Suggest search loads complete objects, instead of performance-optimized allocation',
    'D3_EXTSEARCH_QUICK_FULLOBJECTS_DESC'             => 'For the usual representation of the suggest search, a performance-optimized assignment of the result data is sufficient. For the display of certain information (e.g., calculated prices, etc.), it is necessary to load the complete objects. However, this reduces the charging speed.',
    'D3_EXTSEARCH_QUICK_COUNT'                        => 'maximum number of items to be loaded in the suggest search',
    'D3_EXTSEARCH_QUICK_COUNT_DESC'                   => 'For performance reasons, the suggest search hits are only shown from a maximum number. If more hits are found, the article list does not blend in, instead a hint is shown. Increase the value if you do not get suggest hits for common search terms. But please check the load of your server / account afterwards. The default value is 200.',
    'D3_EXTSEARCH_QUICK_LOADCATEGORIES'               => 'In addition, search for appropriately named categories',
    'D3_EXTSEARCH_QUICK_LOADCATEGORIES_DESC'          => 'In addition to articles, categories are also searched in the suggest search. Please note that this option consumes additional resources, which slow down the suggest search.',
    'D3_EXTSEARCH_QUICK_LOADMANUFACTURERS'            => 'In addition, also search for appropriately named manufacturers',
    'D3_EXTSEARCH_QUICK_LOADMANUFACTURERS_DESC'       => 'In addition to articles, the suggest Search also searches for manufacturers. Please note that this option consumes additional resources, which slow down the suggest search.',
    'D3_EXTSEARCH_QUICK_LOADVENDORS'                  => 'In addition, also search for appropriately named vendors',
    'D3_EXTSEARCH_QUICK_LOADVENDORS_DESC'             => 'In addition to articles, vendors are also searched in the suggest search. Please note that this option consumes additional resources, which slow down the suggest search.',
    'D3_EXTSEARCH_QUICK_LOADCONTENT'                  => 'In addition, also search for appropriately named texts',
    'D3_EXTSEARCH_QUICK_LOADCONTENT_DESC'             => 'Besides articles, texts are also searched in the suggest search. Please note that this option consumes additional resources, which slow down the suggest search. <br> <br> To use this option, it is necessary that the text search is also activated for the regular hit list ("Basic settings" tab).',
    'D3_EXTSEARCH_QUICK_CMPLOBJ'                      => 'before Oxid 4.3.0: load entire article object, otherwise only ID, title and icon. <br> Activate only when needed, consumes more resources. ',
    'D3_EXTSEARCH_QUICK_CMPLOBJ_DESC'                 => 'The presentation of the suggest matches can be adjusted graphically by you in a template to your shop. You may need additional data for your desired display except the article name and link to the article. Thus, for example, also thumbnails, the price or a shopping cart button. For this you need information that is not available in the standard version. Set this checkbox to make all article data available. <br> <br> From Shop version 4.3.0 it is absolutely necessary to load the complete article object. This setting is then ignored.',
    'D3_EXTSEARCH_QUICK_LOADVARIANTS'                 => 'Load variant articles and show them in the suggest search <br> Enter additionally \'oxvarselect\' in the search fields.',
    'D3_EXTSEARCH_QUICK_LOADVARIANTS_DESC'            => 'Normally the shop search does not search for product variants. However, if you have many variant articles in your shop, it may make sense to unlock the search.',
    'D3_EXTSEARCH_QUICK_SAVE'                         => 'save',
    'D3_EXTSEARCH_QUICK_TPLNOTICE'                    => 'Note: To graphically customize the suggest result window, expand the template blocks in \'d3_ext_search_suggestsearch.tpl\'.',
    'D3_EXTSEARCH_QUICK_IAS'                          => 'interactive search (selection search)',
    'D3_EXTSEARCH_QUICK_SHOWIAS'                      => 'show interactive search (if text part is selected)',
    'D3_EXTSEARCH_QUICK_SHOWIAS_DESC'                 => 'If you mark a word in the shop, a small form will be displayed near you, with the help of which you can immediately search for the highlighted word. If you click elsewhere in the shop, the window disappears.',

    'D3_EXTSEARCH_STAT_TYPE'                          => 'evaluation:',
    'D3_EXTSEARCH_STAT_NOHITS'                        => 'no evaluations available',
    'D3_EXTSEARCH_STAT_NOREPORTBASE'                  => 'Your shop doesn\'t support this statistics.',
    'D3_EXTSEARCH_STAT_NOREPORTBASE_DESC'             => 'To use statistics, the OXID class \'OeStatistics_Report_Base\' is required. In OXID eShop, this script is provided by a separate "Statistics" module. Therefore, the graphical evaluation in your shop can unfortunately not be used without its installation.',
    'D3_EXTSEARCH_STAT_TYPEHITLESS'                   => 'Search queries without hits',
    'D3_EXTSEARCH_STAT_TYPEMOSTHITS'                  => 'Search queries with the most hits',
    'D3_EXTSEARCH_STAT_TYPEMOSTSEARCHES'              => 'most common search terms',
    'D3_EXTSEARCH_STAT_LANG'                          => 'language:',
    'D3_EXTSEARCH_STAT_TIME'                          => 'period:',
    'D3_EXTSEARCH_STAT_GENERATESTAT'                  => 'Create evaluation',
    'D3_EXTSEARCH_STAT_SEARCHWORD'                    => 'search term',
    'D3_EXTSEARCH_STAT_HITS'                          => 'hits',
    'D3_EXTSEARCH_STAT_SEARCHES'                      => 'requests',
    'D3_EXTSEARCH_STAT_TYPES_CATEGORY'                => 'category',
    'D3_EXTSEARCH_STAT_TYPES_PRICE'                   => 'price',
    'D3_EXTSEARCH_STAT_TYPES_VENDOR'                  => 'vendor',
    'D3_EXTSEARCH_STAT_TYPES_MANUFACTURER'            => 'brand',
    'D3_EXTSEARCH_STAT_TYPES_OWNLIKE'                 => 'own search field (LIKE)',
    'D3_EXTSEARCH_STAT_TYPES_OWNIS'                   => 'own search field (IS)',
    'D3_EXTSEARCH_STAT_TYPES_OWNVALUE'                => '%s => "%s"',
    'D3_EXTSEARCH_STAT_TYPES_ATTRIBUTE'               => 'attributes',
    'D3_EXTSEARCH_STAT_TYPES_INDEXLETTER'             => 'index letter',
    'D3_EXTSEARCH_STAT_TYPES_UNKNOWN'                 => 'unknown filter',
    'D3_EXTSEARCH_STAT_STATDESC_HITLESS'              => 'hitless searches in %s to "%s" ',
    'D3_EXTSEARCH_STAT_STATDESC_MOSTSEARCHES'         => 'searches in %s to "%s" ',
    'D3_EXTSEARCH_STAT_NOITEMS'                       => 'there are no items for your search',
    'D3_EXTSEARCH_STAT_NOITEMS_DESC'                  => 'If you have expected data here, please check whether statistics collection is activated appropriately in the module settings.',
    'D3_EXTSEARCH_STAT_SELECTFILTER'                  => 'Set the desired filter and send your selection to get results.',

    'D3_EXTSEARCH_PLUGIN_SETTINGS'                    => 'settings',
    'D3_EXTSEARCH_PLUGIN_SEARCHACTIVE'                => 'offer the user in the browser to install the search plugin',
    'D3_EXTSEARCH_PLUGIN_SEARCHACTIVE_DESC'           => 'In the Internet Explorer version 7 and also in Firefox version 2 or higher, you will find a way to start the most important search engines from anywhere on the Internet in the upper right corner. Offer your customers to add your shop to this list too. So it is enough to select your shop in the drop-down box and enter the search term. Immediately your shop will be shown with the search hits. As text your Shoptitel is used, an icon can be defined below.',
    'D3_EXTSEARCH_PLUGIN_INSTALLLINK'                 => 'show an installation link in the shop search',
    'D3_EXTSEARCH_PLUGIN_INSTALLLINK_DESC'            => 'If your customer can add your shop to the search engine list, this is indicated in the browser by a colored border. However, this is not very noticeable, many users missed this out. It\'s better to add an additional link in the search results to indicate this feature.',
    'D3_EXTSEARCH_PLUGIN_SEARCHICON'                  => 'Icon for browser plugin',
    'D3_EXTSEARCH_PLUGIN_CHOOSEICON'                  => 'Please choose an icon.',
    'D3_EXTSEARCH_PLUGIN_SEARCHICON_DESC'             => 'Define here the icon which should be attached in the browser plugin. The icon must have a size of 16 x 16 pixels and be available in PNG or JPG format.',
    'D3_EXTSEARCH_PLUGIN_SAVE'                        => 'save',
    'D3_EXTSEARCH_PLUGIN_GENERATE'                    => 'generation',
    'D3_EXTSEARCH_PLUGIN_GENERATE_DESC'               => 'If you have changed your shop title, set a new icon or even moved your shop to a new address, it is necessary to update the search plugin. Please also advise your customers to update the plugin. It does not renew itself automatically.',
    'D3_EXTSEARCH_PLUGIN_STARTGENERATING'             => 'start Creation',
    'D3_EXTSEARCH_PLUGIN_GENERATEFILE'                => 'Create installation file:',
    'D3_EXTSEARCH_PLUGIN_GENERATENOTICE'              => 'With the creation of the installation file you have completed all necessary steps. If your customer starts the integration, this file is automatically read from your server.',
    'D3_EXTSEARCH_PLUGIN_CREATE_SUCC'                 => 'Plugin file was generated successfully.',
    'D3_EXTSEARCH_PLUGIN_CREATE_NSUCC'                => 'Plugin file could not be created.',

    'D3_EXTSEARCH REPORT_MOSTSEARCHES'                => 'Search terms (only available in search module)',
    'D3_EXTSEARCH_STATISTIC_MOSTSEARCHES'             => 'most common search terms',
    'D3_EXTSEARCH_STATISTIC_MOST_DESC'                => 'So often the chosen term was searched',
    'D3_EXTSEARCH_STATISTIC_FURTHERFILTERS'           => '(limited by further filters)',
    'D3_EXTSEARCH_STATISTIC_GRAPH'                    => 'graphical analysis',

    'D3_EXTSEARCH_CONTENT_SEARCHABLE'                 => '<img src="../modules/d3/modcfg/public/d3logo.php" alt="D³" title="D³ Data Development"> CMS is searchable',
    'D3_EXTSEARCH_PUSH'                               => '<img src="../modules/d3/modcfg/public/d3logo.php" alt="D³" title="D³ Data Development"> importance of these article in the whole assortment',
    'D3_EXTSEARCH_PUSH_1'                             => 'normal',
    'D3_EXTSEARCH_PUSH_2'                             => 'important',
    'D3_EXTSEARCH_PUSH_3'                             => 'very important',
    'D3_EXTSEARCH_PUSH_DESC'                          => 'D³ Modul "extended Suche": The importance defines the first order of the articles in the search (when using the "extended search"). In combination with field relevance, importance functions as a factor. For example, particularly important articles have the 3 times relevance of normally weighted articles. Note this also when assigning the field relevance.',

    'D3_EXTSEARCH_ATTRIBUTE_NOTUSE4FILTER'            => '<img src="../modules/d3/modcfg/public/d3logo.php" alt="D³" title="D³ Data Development"> Attribute will NOT used in search filters',
    'D3_EXTSEARCH_CATEGORY_NOTUSE4FILTER'             => '<img src="../modules/d3/modcfg/public/d3logo.php" alt="D³" title="D³ Data Development"> Category will NOT used in search filters and for category results',

    'D3_EXTSEARCH_SYNED_NOLEXICON'                    => 'The semantic lexicon isn\'t installed! Please check manual for further informations.',
    'D3_EXTSEARCH_SYNED_WORD'                         => 'word',
    'D3_EXTSEARCH_SYNED_WORD_DESC'                    => 'Search for a specific term, enter it here and submit.',
    'D3_EXTSEARCH_SYNED_ALTWORD'                      => 'same meaning words',
    'D3_EXTSEARCH_SYNED_SYNSETID'                     => 'Synonym ID',
    'D3_EXTSEARCH_SYNED_SYNSETID_DESC'                => 'Search for a specific synonym ID, enter it here and submit.',
    'D3_EXTSEARCH_SYNED_SAVENEWSYN'                   => 'save new synonym',
    'D3_EXTSEARCH_SYNED_SAVENEWSYN_DESC'              => 'Define another term for the chosen meaning here.',
    'D3_EXTSEARCH_SYNED_DELETESYN'                    => 'Should the synonym really be deleted?',

    'D3_EXTSEARCH_SYNED_MAIN_NEWWORD'                 => 'New term / phrase',

    'D3_EXTSEARCH_SYNED_MAIN_WORD'                    => 'term / phrase:',
    'D3_EXTSEARCH_SYNED_MAIN_WORD_DESC'               => 'If you would like to create suitable terms for a new word meaning, note the first term here. Insert the term here only if the word meaning does not yet exist in the lexicon. Otherwise, enter the new term in the appropriate meaning in the "Edit synonyms" tab.',
    'D3_EXTSEARCH_SYNED_MAIN_COMMENT'                 => 'comment:',
    'D3_EXTSEARCH_SYNED_MAIN_COMMENT_DESC'            => 'The comment serves exclusively to make further internal explanations to the term. It is not used for the search.',
    'D3_EXTSEARCH_SYNED_MAIN_SYNSETID'                => 'Synonym ID:',
    'D3_EXTSEARCH_SYNED_MAIN_SYNSETID_DESC'           => 'In a uniform synonym ID, all terms with the same meaning are stored. New entries will automatically be assigned a new ID. If a term has been mistakenly assigned the wrong meaning, choose the synonym ID from the appropriate meaning and change it to your term.',
    'D3_EXTSEARCH_SYNED_MAIN_LANGUAGE'                => 'language:',
    'D3_EXTSEARCH_SYNED_MAIN_LANGUAGE_DESC'           => 'Determine from this, from which language the selected term originates and in which this is to be used. Only the languages activated in the shop are available.',
    'D3_EXTSEARCH_SYNED_MAIN_LANGUAGE_DISABLED'       => '(disabled)',

    'D3_EXTSEARCH_SYNED_MANAGE_DESC'                  => 'The synonyms shown here are alternative terms for the meaning chosen above.',
    'D3_EXTSEARCH_SYNED_MANAGE_EDIT'                  => 'edit',
    'D3_EXTSEARCH_SYNED_MANAGE_EDIT_DESC'             => 'If you want to add additional details to the term or assign it to a different meaning, click on the symbol. The admin area changes to the editing area for exactly the term.',
    'D3_EXTSEARCH_SYNED_MANAGE_SYNONYM'               => 'Synonym',

    'D3_EXTSEARCH_UPDATE_GENPHONETIC'                 => '"extended search": The module update made changes in the database structure for the similarity search. Therefore, after completing this installation, update the search index in the admin area of the module.',

    'GENERAL_ARTICLE_D3_PHONETIC'                     => 'extSearch - phonetic index', // Multilang-Fields for importer
    // Multilang-Fields for importer
    'GENERAL_ARTICLE_D3_SEARCHINDEXDATE'              => 'extSearch - date of last search index generating',
    // Multilang-Fields for importer
    'GENERAL_ARTICLE_D3PUSH'                          => 'extSearch - product importance',
    // Multilang-Fields for importer
    'GENERAL_ARTICLE_OXVARSELECT'                     => 'variant title',

);
