<?php

/**
 * This Software is the property of Data Development and is protected
 * by copyright law - it is NOT Freeware.
 *
 * Any unauthorized use of this software without a valid license
 * is a violation of the license agreement and will be prosecuted by
 * civil and criminal law.
 *
 * http://www.shopmodule.com
 *
 * @copyright (C) D3 Data Development (Inh. Thomas Dartsch)
 * @author    D3 Data Development - Daniel Seifert <support@shopmodule.com>
 * @link      http://www.oxidmodule.com
 */

$sLangName = "Deutsch";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(

//Navigation
    'charset'                                         => 'UTF-8',
    'd3mxextsearch'                                   => '<i class="fa fa-search-plus"></i> Erweiterte Suche',
    'd3mxextsearch_settings'                          => 'Einstellungen',
    'd3mxextsearch_statistic'                         => 'Statistik',
    'd3mxextsearch_syneditor'                         => 'Synonym-Editor',
    'd3tbclextsearch_syneditor_main'                  => 'Stamm',
    'd3tbclextsearch_syneditor_manage'                => 'Synonyme bearbeiten',
    'd3tbclextsearch_syneditor_family'                => 'Wortverwandtschaften',
    'd3tbclextsearch_syneditor_synset'                => 'Synonymgruppe bearbeiten',
    'd3tbclextsearch_settings_results'                => 'Grundeinstellungen',
    'd3tbclextsearch_settings_navigation'             => 'Filter + Anzeige',
    'd3tbclextsearch_settings_quick'                  => 'Schnelltreffer',
    'd3tbclextsearch_settings_browser'                => 'Browser-Plugin',
    'd3tbclextsearch_settings_content'                => 'Content-Suche',
    'd3tbclextsearch_settings_statistik'              => 'Statistik',

    'D3_EXTSEARCH_LIST_SETTLANG'                      => 'Einstellungen für Sprache',
    'D3_EXTSEARCH_HELPLINK'                           => 'Fragen-zu-speziellen-Modulen/Erweiterte-Suche/',
    'D3_EXTSEARCH_HELPLINK_CONFIG'                    => '',

    'D3_EXTSEARCH_TRANSL'                             => 'Erweiterte Suche',

    'D3_EXTSEARCH_CONFIGVARS_SADDTITLE'               => 'Modul-Edition:',
    'D3_EXTSEARCH_CONFIGVARS_BLUSEFILTERINARTICLELISTS' => 'Filter in Artikellisten verfügbar:',
    'D3_EXTSEARCH_CONFIGVARS_FEATUREBIT1'             => 'Filter in Artikellisten verfügbar:',

    'D3_EXTSEARCH_MAIN_DEBUGACTIVE_DESC'              => 'Der Debugmodus gibt die verwendeten Datenbankabfragen zur einfacheren Programmierung und Fehlersuche im Frontend aus. Deaktivieren Sie diesen bitte unbedingt für den Livebetrieb, da mit aktiviertem Debugmodus das Datenbank-Caching nicht verwendet wird.',
    'D3_EXTSEARCH_MAIN_MAINSETTINGS'                  => 'allgemeine Einstellungen',
    'D3_EXTSEARCH_MAIN_FIELDLIST'                     => 'diese Felder für die Ähnlichkeitssuche und die Schnellsuche verwenden<br>Relevanz => Feldname (Bsp.: 50 => oxtitle)',
    'D3_EXTSEARCH_MAIN_SORTDEBUG'                     => 'Ergebnis-Feld-Analyse',
    'D3_EXTSEARCH_MAIN_SORTDEBUG_DESC'                => 'Geben Sie Ihren Suchbegriff ein. <br>In der Tabelle werden zum Artikel auch die Relevanzwerte zu jedem Feld ausgegeben, in welchem der Treffer gefunden wurde. Die Relevanzwerte "..._IN_" definieren Sie in den Einstellungen der "erweiterten Suche". "D3PUSH" ist die Wichtigkeit des Artikels. Die Relevanz jedes Artikels in der Trefferliste ("d3Priority") ergibt sich aus der folgenden Formel: <blockquote>((Summe aus allen "_IN_"-Feldern) x D3PUSH) + D3PUSH</blockquote>..._PART_IN_... - in diesen Feldern ist der Suchbegriff mindestens Teil eines Wortes<br>..._WORD_IN_... - in diesen Felder kommt der Suchbegriff als frei stehendes Wort vor',
    'D3_EXTSEARCH_MAIN_SORTDEBUG_START'               => 'Suche starten',
    'D3_EXTSEARCH_MAIN_NOFIELDSDEFINED'               => '<b>Keine Felder definiert.</b><br>Standard: \'oxtitle\', \'oxsearchkeys\' und \'oxartnum\'',
    'D3_EXTSEARCH_MAIN_FIELDLIST_DESC'                => 'Tragen Sie hier die Artikel-Tabellenfelder ein, die bei der Suche verwendet werden. Die Feldbezeichnungen entnehmen Sie bitte der Shopdatenbank. Ändern Sie diese Eintragungen, muß der Suchindex noch einmal neu erzeugt werden.<br><br>Vor den Feldnamen tragen Sie mit => getrennt die Relevanz des jeweiligen Feldes ein. Je höher die Relevanz, umso höher wird ein Artikel gezeigt, wenn der Suchbegriff in diesem Feld vorkommt (separat zu aktivieren). Wird der Suchbegriff in mehreren Feldern gefunden, addiert sich die Relevanz. Ist keine Relevanz angegeben, erhält das Feld automatisch den Wert 10.',
    'SHOP_CONFIG_SEARCHFIELDS'                        => 'Felder, in denen gesucht wird<br>"erweiterte Suche" verwendet eigene Einstellungen / Bearbeiten in <input type="button" onclick="document.getElementById(\'myedit\').target = \'basefrm\'; document.getElementById(\'myedit\').fnc.value=\'\';document.getElementById(\'myedit\').cl.value=\'d3_cfg_extsearch_main\';document.getElementById(\'myedit\').submit();" value="erweiterte Suche">',
    'SHOP_CONFIG_SEARCHUSEAND'                        => 'Wenn mehrere Suchbegriffe eingegeben werden, müssen alle Suchbegriffe in einem Suchergebnis vorkommen (AND). (Wenn die Option nicht aktiv ist, muss nur ein Suchbegriff vorkommen (OR).)',
    'D3_EXTSEARCH_MAIN_PUTINLEAVEOUT'                 => 'Auslassungen oder Einfügungen erlauben',
    'D3_EXTSEARCH_MAIN_PUTINLEAVEOUT_DESC'            => 'Mit dieser Option wird auch nach Artikeln gesucht, in deren Texten ein Buchstabe mehr (eingeschoben) oder weniger (ausgelassen) vorkommt. Jedoch kann sich dadurch auch die Trefferzahl erhöhen und das Ergebnis aufweichen. Auf Singular <-> Plural-Treffer hat diese Einstellung keinen Einfluß.',
    'D3_EXTSEARCH_MAIN_MULIPLEWORDS'                  => 'Verwendung mehrerer Suchworte',
    'D3_EXTSEARCH_MAIN_MULIPLEWORDS_DESC'             => 'Ist es sinnvoll, daß auch bei mehreren Suchworten diese nur im Zusammenhang gesucht werden, können Sie dies hier aktivieren. Andernfalls kann jedes der Suchworte separat und ohne eine Verbindung in den Ergebnissen vorkommen. Im Syntaxmodus kann der Nutzer den Modus selbst bestimmen, in dem er zusammenhängende Worte in Anführungszeichen setzt und/oder mit Plus- oder Minus-Zeichen einschränkt bzw. ausweitet.',
    'D3_EXTSEARCH_MAIN_MULIPLEWORDS_SINGLE'           => 'jedes Wort wird separat gesucht',
    'D3_EXTSEARCH_MAIN_MULIPLEWORDS_WHOLE'            => 'wird nur als zusammenhängender Begriff gesucht',
    'D3_EXTSEARCH_MAIN_MULIPLEWORDS_SYNTAX'           => 'vom Nutzer über Suchsyntax steuerbar',
    'D3_EXTSEARCH_MAIN_SORTING'                       => 'Artikelsortierung',
    'D3_EXTSEARCH_MAIN_ORDERBYPRIORITY'               => 'Treffer nach Relevanz sortieren',
    'D3_EXTSEARCH_MAIN_ORDERBYPRIORITY_DESC'          => 'Die Relevanz definiert, wie gut ein gefundener Artikel zum Suchbegriff passt. (Daher ist die Relevanzsortierung auch nur in der Suche verfügbar. In Kategorien steht diese nicht zur Verfügung.)<br>Hat der Kunde keine eigene Sortierung gewählt, werden die Suchtreffer nach Feldrelevanz sortiert. Die Relevanz legen Sie an den für die Suche definierten Datenbankfeldern fest. Die Summe der Relevanz der Felder, die den Suchbegriff enthalten, wird dann als Sortierkriterium verwendet. In Verbindung mit der Wichtigkeit der Artikel (separat zu aktivieren) kann sich die Relevanz vervielfachen.<br><br>Formel: <br>Sortierung = Relevanzsumme * Wichtigkeit + Wichtigkeit',
    'D3_EXTSEARCH_MAIN_ORDERBYPUSH'                   => 'Treffer nach Wichtigkeit sortieren',
    'D3_EXTSEARCH_MAIN_ORDERBYPUSH_DESC'              => 'Die Wichtigkeit definiert die Empfehlungsposition eines Artikels innerhalb Ihres gesamten Sortimentes.<br>Hat der Kunde keine eigene Sortierung gewählt, werden die Suchtreffer nach Wichtigkeit sortiert. Die Wichtigkeit legen Sie am jeweiligen Artikel fest. Ohne aktivierte Feldrelevanz ist die Wichtigkeit einziges Sortierkriterium. In Verbindung mit Feldrelevanz wirkt die Wichtigkeit als Multiplikator. Treffer in niedrig priorisierten Feldern bei wichtigen Artikeln können diese damit vor unwichtige Artikel mit hohen Feldrelevanz setzen und die Reihenfolge so ggf. umkehren.<br><br>Formel: <br>Sortierung = Relevanzsumme * Wichtigkeit + Wichtigkeit',
    'D3_EXTSEARCH_MAIN_ORDERBYALTERNATIVE'            => 'alternative Sortierung bei identischem Relevanzsortierwert',
    'D3_EXTSEARCH_MAIN_ORDERBYALTERNATIVE_DESC'       => 'Die Sortierreihenfolge wird auf Basis der hier gesetzten Einstellungen für jeden Artikel berechnet. Haben mehrere Artikel einen identischen Sortierwert, können diese untereinander nach einem weiteren Kriterium sortiert werden. Als Angabe ist hier der Name eines Feldes der Artikel-Tabelle zugelassen (ohne Sprach-Zusatz). Mit asc und desc stellen Sie ein, ob auf- oder absteigend sortiert wird.',
    'D3_EXTSEARCH_MAIN_VARIANTSETTINGS'               => 'Variantensuche',
    'D3_EXTSEARCH_MAIN_VARIANTSEARCH'                 => 'Shop sucht auch nach Variantenartikeln',
    'D3_EXTSEARCH_MAIN_VARIANTUSAGE'                  => 'wird eine Artikelvariante gefunden, wird ...',
    'D3_EXTSEARCH_MAIN_VARIANTUSAGE_SHOWPARENT'       => '... deren Vaterartikel in der Trefferliste gezeigt',
    'D3_EXTSEARCH_MAIN_VARIANTUSAGE_SHOWVARIANT'      => '... die Variante selbst in der Trefferliste gezeigt',
    'D3_EXTSEARCH_MAIN_VARIANTCHECKPARENTACTIVE'      => 'Aktivstatus des Elternartikel ausdrücklich prüfen',
    'D3_EXTSEARCH_MAIN_VARIANTUSAGE_DESC'             => 'Beachten Sie bei der Anzeige des Vaterartikels anstatt der Variante bitte darauf, dass die Vaterartikel auch aktiv und auswählbar sein müssen. Eine zusätzliche Prüfung darauf findet absichtlich nicht statt, da diese das Suchergebnis verfälschen würde.',
    'D3_EXTSEARCH_MAIN_VARIANTSEARCH_DESC'            => 'Statt wie üblich nur nach regulären Artikeln zu suchen, findet der Shop mit dieser Option auch einzelne Variantenartikel. Tragen Sie bitte zusätzlich in der Feldliste des Moduls und im Shop unter \'Stammdaten -> Grundeinstellungen -> Einstell. -> Suche\' den Feldname \'oxvarselect\' ein und generieren Sie den Suchindex neu.',
    'D3_EXTSEARCH_MAIN_VARIANTCHECKPARENTACTIVE_DESC' => 'Wird nur verwendet, wenn Varianten als Treffer gezeigt werden. Im Normalfall sollte es zu einem inaktiven Elternartikel keine aktiven Varianten geben. Kommt diese Konstellation in Ihrem Shop aus einem bestimmten Grund dennoch vor, können Sie mit dieser Option die explizite Prüfung auf aktive Elternartikel aktivieren. Beachten Sie, dass diese Option viel Rechenleistung benötigt. Schalten Sie alternativ die Variantenartikel besser inaktiv.',
    'D3_EXTSEARCH_MAIN_OWNFORMFIELDS'                 => 'individuelle Filterfelder nutzen',
    'D3_EXTSEARCH_MAIN_OWNFORMFIELDS_DESC'            => 'Erweitern Sie das Suchformular mit weiteren Filtermöglichkeiten. Um diese auch zu verwenden, muß dieser Haken gesetzt sein. Detailierte Erklärungen zu weiteren Suchfeldern finden Sie im Dokumentations-Ordner des Moduls.',
    'D3_EXTSEARCH_MAIN_LOGSETTINGS'                   => 'Statistik',
    'D3_EXTSEARCH_MAIN_LOGHITLESS'                    => 'ergebnislose Suchaktionen für Statistik mitschreiben',
    'D3_EXTSEARCH_MAIN_LOGHITLESS_DESC'               => 'Startet der Kunde eine Suchanfrage, die keine Ergnisse liefern kann, werden die Suchbegriffe für Sie aufgezeichnet. Sie finden die Aufstellung dann unter der Registerkarte \'Logging\' und können Ihre Produkte ggf. auch für diese Begriffe optimieren.',
    'D3_EXTSEARCH_MAIN_LOGFORSEARCH'                  => 'alle Suchanfragen für Statistik mitschreiben (auch ohne shopweites Logging)',
    'D3_EXTSEARCH_MAIN_LOGFORSEARCH_DESC'             => 'Schreibt alle Suchanfragen für die modulinterne Statistik mit. Diese Einstellung kann auch gesetzt werden, ohne daß andere Shopfunktionen mitgeschrieben werden. Ist das shopweite Logging aktiviert, werden die Suchanfragen generell mitgeschrieben.',
    'D3_EXTSEARCH_MAIN_PHONETICS'                     => 'phonetische Suche (nach Klang)',
    'D3_EXTSEARCH_MAIN_SIMILARSEARCH'                 => 'wenn kein Suchergebnis, Shop sucht nach ähnlichen klingenden Artikel (Bsp.: Suche: <i>Pflan<b>s</b>e</i>, Treffer: <i>Pflan<b>z</b>e</i>)',
    'D3_EXTSEARCH_MAIN_SIMILARSEARCH_DESC'            => 'Hier aktivieren (oder deaktivieren) Sie die phonetische Suche. Damit fangen Sie zum Beispiel Schreibfehler in der Suchabfrage ab und der Kunde findet seine gewünschten Artikel trotzdem mit großer Wahrscheinlichkeit. Ist gleichzeitig die Suche nach Sinn (Semantic) aktiviert, wird zuerst versucht, sinngleiche Treffer zu finden. Schlägt dies fehl, werden Treffer über die Klangsuche ermittelt.',
    'D3_EXTSEARCH_MAIN_PHONETICLANG'                  => 'für die Ähnlichkeitssuche verwendete Sprache',
    'D3_EXTSEARCH_MAIN_PHONETICLANG_DESC'             => 'Da sich die verschiedenen menschlichen Sprachen in Ihrer Aussprache und in der Wort- bzw. Buchstabenzusammensetzung unterscheiden, ist für ein optimales Suchergebnis ein sprachenabhängiges Verfahren zur Indexgenerierung nötig. Sollten Sie in Ihrem Shop hauptsächlich eine andere Sprache als die nebenstehend Angezeigte verwenden, fragen Sie bei uns nach, ob auch ein Modul für Ihre Sprache zur Verfügung steht.',
    'D3_EXTSEARCH_MAIN_SIMILAREXTLIST_1'              => 'Shop zeigt zusätzlich ähnliche klingende Treffer, wenn reguläre Suche maximal',
    'D3_EXTSEARCH_MAIN_SIMILAREXTLIST_2'              => 'Treffer',
    'D3_EXTSEARCH_MAIN_SIMILAREXTLIST_DESC'           => 'Wenn die Suche nur wenige Treffer erzielt, kann man dem Kunden so auch ähnliche Artikel liefern. Diese ähnlichen Artikel werden in der Ergebnisliste nach den tatsächlichen Treffern gezeigt. Der Kunde wird mit einer Meldung über die aufgefüllte Liste informiert. Setzen Sie diese Einstellung bitte jedoch mit Bedacht ein, da die zusätzlichen Treffer die Kunden verwirren könnten.',
    'D3_EXTSEARCH_MAIN_MINPHONLENGTH'                 => 'Treffergenauigkeit bei kurzen Suchworten',
    'D3_EXTSEARCH_MAIN_MINPHONLENGTH_LESS'            => 'weniger Genauigkeit',
    'D3_EXTSEARCH_MAIN_MINPHONLENGTH_REG'             => 'normale Genauigkeit',
    'D3_EXTSEARCH_MAIN_MINPHONLENGTH_MORE'            => 'mehr Genauigkeit',
    'D3_EXTSEARCH_MAIN_MINPHONLENGTH_DESC'            => 'Für eine sinnvolle Trefferliste ist ein ausreichend langes Suchwort nötig. Je \'genauer\' Sie diese Einstellung setzen, umso präziser sind die Treffer.',
    'D3_EXTSEARCH_MAIN_SEMANTICS'                     => 'semantische Suche (nach Sinn)',
    'D3_EXTSEARCH_MAIN_SEMANTICSEARCH'                => 'Shop sucht nach Artikeln mit ähnlichem Sinn (Bsp.: Suche: <i>Gew&auml;chs</i>, Treffer: <i>Pflanze</i>)',
    'D3_EXTSEARCH_MAIN_SEMANTICSEARCH_MISSING'        => 'Shop sucht nach Artikeln mit ähnlichem Sinn (Bsp.: Suche: <i>Gew&auml;chs</i>, Treffer: <i>Pflanze</i>)<br><b>Lexikon ist nicht installiert!</b>',
    'D3_EXTSEARCH_MAIN_SEMANTICSEARCH_DESC'           => 'Setzen Sie diesen Haken, um eine sinngleiche Suche im Shop zu ermöglichen. Durch z.B. regionale Unterschiede kann es vorkommen, daß Ihre Kunden einen Artikel zwar anders bezeichnen, jedoch Ihr Produkt meinen. Gibt der Kunde nun seinen Wunsch ein, bekommt er gegebenenfalls die Begriffe gezeigt, die in Ihrem Shop das gewünschte Produkt besser beschreiben.<br>Die sinngleiche Suche wird für Artikelinhalte und Kategorienamen verwendet.',
    'D3_EXTSEARCH_MAIN_SEMANTICUSEPHONETIC'           => 'enthält das Suchwort Schreibfehler, wird zusätzlich zur Sinnsuche versucht, die richtige Schreibweise zu ermitteln; erzeugt jedoch ggf. stark abweichende Treffer; erfordert aktivierte phonetische Suche',
    'D3_EXTSEARCH_MAIN_SEMANTICUSEPHONETIC_DESC'      => 'Diese Einstellung erlaubt zur sinngleichen Suche auch die phonetische Suche, wenn keine sinngleichen Worte gefunden werden. Da hier jedoch der gewünschte Sinn nicht eindeutig klar ist, werden unter Umständen stark abweichende Treffer gezeigt. Wir empfehlen die Verwendung dieser Einstellung nur eingeschränkt.',
    'D3_EXTSEARCH_MAIN_SAVE'                          => 'Speichern',
    'D3_EXTSEARCH_MAIN_INDEX'                         => 'Suchindex',
    'D3_EXTSEARCH_MAIN_INDEXARTCNT'                   => 'Artikel pro Durchlauf für Index aufarbeiten',
    'D3_EXTSEARCH_MAIN_INDEXARTCNT_DESC'              => 'Der Webserver bricht Scripte nach einer gewissen Laufzeit aus Sicherheitsgründen ab. Um die Generierung des Suchindexes dennoch fertigstellen zu können, verarbeitet dieses Script nur eine gewisse Anzahl Artikel und startet sich dann neu. Legen Sie hier fest, wie viele Artikel in einem Durchlauf bearbeitet werden sollen. Bricht die Generierung mit einem Fehler ab, reduzieren Sie die Zahl. Je niedriger die Anzahl, um so länger benötigt jedoch das Script.',
    'D3_EXTSEARCH_MAIN_INDEXERR'                      => 'Der benötigte Index für die fehlertolerante Suche ist lückenhaft. Klicken Sie hier, um die Liste neu zu generieren:',
    'D3_EXTSEARCH_MAIN_INDEXNOERR'                    => 'Der benötigte Index für die fehlertolerante Suche scheint vollständig. Im Moment ist keine Aktion nötig, wenn Sie die Sprache nicht geändert haben oder Artikel importiert haben.<br>Der Index muß für jede Sprache des Shop separat erstellt werden.',
    'D3_EXTSEARCH_MAIN_GENINDEXCMPL'                  => 'Suchindex komplett neu generieren',
    'D3_EXTSEARCH_MAIN_GENINDEXCMPL_DESC'             => 'Generiert für alle im Shop vorhandenen Artikel den Suchindex neu. Dies kann unter Umständen länger dauern.',
    'D3_EXTSEARCH_MAIN_GENINDEXNEW'                   => 'neue Artikel in Suchindex aufnehmen',
    'D3_EXTSEARCH_MAIN_GENINDEXNEW_DESC'              => 'Klicken Sie auf die nebenstehende Schaltfläche, um alle Artikel, die seit der letzten Indizierung geändert oder hinzugefügt wurden, in den Suchindex aufzunehmen. Alle bisherigen Artikel werden dabei ignoriert.',
    'D3_EXTSEARCH_MAIN_GENSEMANTICINDEX'              => 'Lexikon für sinngleiche Suche neu indizieren',
    'D3_EXTSEARCH_MAIN_GENSEMANTICINDEX_DESC'         => 'Für die Verbindung von sinngleicher Suche und phonetischer Suche benötigt auch das Lexikon den phonetischen Index. Mit dieser Schaltfläche starten Sie die Neuindizierung des Lexikons. Im Normalfall ist dies jedoch nicht notwendig.',
    'D3_EXTSEARCH_MAIN_SHOW_POPUP'                    => 'PopUp während des Suchvorgangs zeigen',
    'D3_EXTSEARCH_MAIN_CATEGORY'                      => 'Suche in Kategoriennamen',
    'D3_EXTSEARCH_MAIN_CATEGORY_SEARCH'               => 'auch in Kategorienamen suchen und enthaltene Artikel finden',
    'D3_EXTSEARCH_MAIN_CATEGORY_ANDOR_DESC'           => 'Diese Einstellung wird nur für die Suche in Kategorienamen verwendet. Für die Artikelsuche gibt es eine eigene Einstellung.',
    'D3_EXTSEARCH_MAIN_CATEGORY_ARTHANDLING'          => 'Kategorie selbst oder deren Artikel anzeigen',
    'D3_EXTSEARCH_MAIN_CATEGORY_ARTINCAT'             => 'Artikel aus Kategorie anzeigen',
    'D3_EXTSEARCH_MAIN_CATEGORY_CATINLIST'            => 'Kategorie zur Auswahl anzeigen',
    'D3_EXTSEARCH_MAIN_CATEGORY_PRIORITY'             => 'Relevanz bei Kategorietreffern',
    'D3_EXTSEARCH_MAIN_CATEGORY_PRIORITY_DESC'        => 'Kategorietreffer erhalten diese Relevanz, wenn die Relevanzsortierung aktiviert ist. Hierbei steht diese Zahl im Zusammenhang mit der Feldrelevanz (siehe separate Einstellung).',
    'D3_EXTSEARCH_MAIN_MANUFACTURER'                  => 'Suche in Marken- und Lieferantennamen',
    'D3_EXTSEARCH_MAIN_MANUFACTURER_SEARCH'           => 'auch in Marken- und Lieferantennamen suchen und enthaltene Artikel finden',
    'D3_EXTSEARCH_MAIN_MANUFACTURER_ANDOR_DESC'       => 'Diese Einstellung wird nur für die Suche in Marken- und Lieferantennamen verwendet. Für die Artikelsuche gibt es eine eigene Einstellung.',
    'D3_EXTSEARCH_MAIN_MANUFACTURER_PRIORITY'         => 'Relevanz bei Marken-/Lieferantentreffern',
    'D3_EXTSEARCH_MAIN_MANUFACTURER_PRIORITY_DESC'    => 'Marken-/Lieferantentreffer erhalten diese Relevanz, wenn die Relevanzsortierung aktiviert ist. Hierbei steht diese Zahl im Zusammenhang mit der Feldrelevanz (siehe separate Einstellung).',
    'D3_EXTSEARCH_MAIN_ADMINPANEL'                    => 'Adminbereich',
    'D3_EXTSEARCH_MAIN_ADMINSHOWVARIANTS'             => 'zeige nach Suche auch Varianten in Artikelliste',
    'D3_EXTSEARCH_MAIN_USEARTNUMSEARCH'               => 'speziell nach Artikelnummern suchen',
    'D3_EXTSEARCH_MAIN_USEARTNUMSEARCH_DESC'          => 'mit dieser Einstellung wird vor dem eigentlichen Suchlauf gezielt nach Artikeln gesucht, die den Suchbegriff als Artikelnummer haben.',
    'D3_EXTSEARCH_MAIN_DONTUSEOWNDBVIEWS'             => 'Datenbankabfragen verwenden <b>nicht</b> die moduleigenen View-Tabellen',
    'D3_EXTSEARCH_MAIN_DONTUSEOWNDBVIEWS_DESC'        => 'Aus Performance-Gründen verwendet die Suche nicht die shopeigenen View-Tabellen, sondern bringt optimierte Versionen dessen mit. Je nach Größe des Datenbank kann deren Verwendung die Geschwindigkeit von Datenbankabfragen bis um den Faktor 100 beschleunigen. Sollen die spezialisierten View-Tabellen <b>nicht</b> verwendet werden, setzen Sie diesen Haken. Dann werden die Abfragen über die shopeigenen View-Tabellen geleitet.<br>Beachten Sie, dass bei deaktivierung dieser Option die View-Tabellen noch einmal aktualisiert werden müssen.',
    'D3_EXTSEARCH_MAIN_GENERATOR_INCONSISTENTTABLE'   => 'Die Artikel-Tabelle der Datenbank ist mit der Langtext-Tabelle nicht konsistent. Bitte bereinigen Sie dies vor der Ausführung des Generators. <br><br>Weitere Informationen finden Sie in der FAQ unter <a href="%1$s" target="_new">%1$s</a>.',
    'D3_EXTSEARCH_MAIN_GENERATOR_FINISHED'            => 'Beendet.',
    'D3_EXTSEARCH_MAIN_GENERATOR_NOTE'                => 'Hinweis',
    'D3_EXTSEARCH_MAIN_GENERATOR_PROCESSED'           => '%1$s Artikel bearbeitet<br>Generierung abgeschlossen!',
    'D3_EXTSEARCH_MAIN_GENERATOR_TERMPROCESSED'       => '%1$s Wort/Wörter bearbeitet<br>Generierung abgeschlossen!',
    'D3_EXTSEARCH_MAIN_GENERATOR_PROCESSING'          => 'Bearbeite %1$s&#37;',
    'D3_EXTSEARCH_MAIN_GENERATOR_PROCESSING1'         => 'Bearbeite %1$s / %2$s Artikel',
    'D3_EXTSEARCH_MAIN_GENERATOR_PROCESSING3'         => 'Bearbeite %1$s / %2$s Begriffe',
    'D3_EXTSEARCH_MAIN_GENERATOR_PROCESSING2'         => '%1$s&#37; bearbeitet',
    'D3_EXTSEARCH_MAIN_GENERATOR_WAIT'                => 'Bitte warten...',
    'D3_EXTSEARCH_MAIN_GENERATOR_CLOSEWND'            => 'Fenster schließen',

    'D3_EXTSEARCH_NAVI_MAINSETTINGS'                  => 'allgemeine Einstellungen',
    'D3_EXTSEARCH_NAVI_DISPTYPE'                      => 'Art der Filter-Anzeige',
    'D3_EXTSEARCH_NAVI_DISPTYPE_LINKLIST'             => 'als Linkliste',
    'D3_EXTSEARCH_NAVI_DISPTYPE_DROPDOWN'             => 'als DropDown-Liste (erfordert JavaScript)',
    'D3_EXTSEARCH_NAVI_DISPTYPE_DESC'                 => 'Stellen Sie hier die Anzeigeform der Kategorie-, Lieferanten- und Markenlisten ein. Die DropDown-Listen sparen in der Anzeige Platz, können jedoch bei vielen Einträgen unübersichtlich lang werden. Außerdem benötigen sie beim Kunden JavaScript. Alternativ empfehlen sich Linklisten, die in ihrer Länge auch eingeschränkt werden können.<br>Beide Anzeigeformen lassen sich im Template nachbearbeiten.',
    'D3_EXTSEARCH_NAVI_EMPTYSEARCH'                   => 'Suche ohne Suchbegriff zulassen',
    'D3_EXTSEARCH_NAVI_EMPTYSEARCH_DESC'              => 'Es kann durchaus sinnvoll sein, auch Suchvorgänge ohne einen Suchbegriff zuzulassen. Möglicherweise werden die dann erhaltenen Treffer erst durch eine zusätzliche Einstellung gefiltert oder Sie möchten ein umfangreiches Suchformular aufbauen, welches möglicherweise kein frei definierbares Suchwort enthält.',
    'D3_EXTSEARCH_NAVI_CATFILTER'                     => 'Kategoriefilter',
    'D3_EXTSEARCH_NAVI_CATLIST'                       => 'zeige Kategorienliste',
    'D3_EXTSEARCH_NAVI_CATLIST_DESC'                  => 'Setzen Sie den Haken, um Ihrem Kunden bei einer umfangreichen Trefferliste eine Auswahl der betroffenen Kategorien anzuzeigen. Damit kann er sein Suchergebnis gezielt einschränken und damit verbessern. Angezeigt wird der Kategoriename und die Anzahl der darin enthaltenen Artikel der Trefferliste.',
    'D3_EXTSEARCH_NAVI_CATLIST_SORT'                  => 'sortiert nach',
    'D3_EXTSEARCH_NAVI_CATLIST_SORT_COUNT'            => 'Anzahl der enthaltenen Artikel',
    'D3_EXTSEARCH_NAVI_CATLIST_SORT_DATA'             => 'eingestellter Sortierreihenfolge',
    'D3_EXTSEARCH_NAVI_CATLIST_SORT_DESC'             => 'Legen Sie hier fest, nach welchem Kriterium die Kategorieliste sortiert sein soll. Auf die Darstellung hat dies jedoch keinen Einfluß.',
    'D3_EXTSEARCH_NAVI_VENDORFILTER'                  => 'Lieferantenfilter',
    'D3_EXTSEARCH_NAVI_VENDORLIST'                    => 'zeige Lieferantenliste',
    'D3_EXTSEARCH_NAVI_VENDORLIST_DESC'               => 'Ebenso wie für die Kategorien gibt es auch die Möglichkeit, die Trefferliste noch einmal nach den Lieferanten zu filtern. Dies schalten Sie hier ein. Diese Option ist nur verfügbar, wenn Sie generell die Lieferantent im Shop aktiviert haben und auch eine Suche danach erlauben. (\'Lieferantenliste laden und anzeigen\')',
    'D3_EXTSEARCH_NAVI_VENDORLIST_SORT'               => 'sortiert nach',
    'D3_EXTSEARCH_NAVI_VENDORLIST_SORT_COUNT'         => 'Anzahl der enthaltenen Artikel',
    'D3_EXTSEARCH_NAVI_VENDORLIST_SORT_ALPHA'         => 'alphabetisch',
    'D3_EXTSEARCH_NAVI_VENDORLIST_SORT_DESC'          => 'Bestimmen Sie die Anzeigereihenfolge, in der die Lieferanten aufgelistet sein sollen.',
    'D3_EXTSEARCH_NAVI_MANUFACTURERFILTER'            => 'Markenfilter',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST'              => 'zeige Markenliste',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST_DESC'         => 'Ebenso wie für die Kategorien gibt es auch die Möglichkeit, die Trefferliste noch einmal nach den Marken zu filtern. Dies schalten Sie hier ein. Diese Option ist nur verfügbar, wenn Sie generell die Marken im Shop aktiviert haben und auch eine Suche danach erlauben. (\'Markenliste laden und anzeigen\')',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST_SORT'         => 'sortiert nach',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST_SORT_COUNT'   => 'Anzahl der enthaltenen Artikel',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST_SORT_ALPHA'   => 'alphabetisch',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST_SORT_DESC'    => 'Bestimmen Sie die Anzeigereihenfolge, in der die Marken aufgelistet sein sollen.',
    'D3_EXTSEARCH_NAVI_REDIRECTS'                     => 'Weiterleitungen',
    'D3_EXTSEARCH_NAVI_UNIQUEHIT'                     => 'bei 1 Artikeltreffer, Shop wechselt direkt zur Detailseite des Artikels',
    'D3_EXTSEARCH_NAVI_UNIQUEHIT_DESC'                => 'Hat Ihr Kunde so präzise gesucht, daß er die gewünschte Information als Einziges in der Trefferliste hat, können Sie ihm den Umweg über die Trefferliste ersparen und liefern ihm sofort die Detailseite des gefunden Artikels.',
    'D3_EXTSEARCH_NAVI_UNIQUECONTENTHIT'              => 'bei 1 CMS-/Texttreffer, Shop wechselt direkt zur CMS-Seite',
    'D3_EXTSEARCH_NAVI_UNIQUECONTENTHIT_DESC'         => 'Enthält das Suchergebniss keine Artikel, jedoch einen einzigen CMS-Text, wird direkt auf die passende CMS-Seite weitergeleitet. Der Benutzer verlässt damit die Suchfunktion des Shops, seine Sucheinstellungen sind dann nicht mehr verfügbar.',
    'D3_EXTSEARCH_NAVI_UNIQUEVENDORHIT'               => 'bei 1 Lieferantentreffer, Shop wechselt direkt zur Lieferanten-Seite des Shops',
    'D3_EXTSEARCH_NAVI_UNIQUEVENDORHIT_DESC'          => 'Enthält das Suchergebniss keine Artikel, jedoch einen einzigen Lieferant, wird direkt auf die passende Lieferanten-Seite Ihres Shops weitergeleitet. Diese Option erfordert die "Suche in Marken- und Lieferantennamen". Der Benutzer verlässt damit die Suchfunktion des Shops, seine Sucheinstellungen sind dann nicht mehr verfügbar.',
    'D3_EXTSEARCH_NAVI_UNIQUEMANUFACTURERHIT'         => 'bei 1 Markentreffer, Shop wechselt direkt zur Marken-Seite des Shops',
    'D3_EXTSEARCH_NAVI_UNIQUEMANUFACTURERHIT_DESC'    => 'Enthält das Suchergebniss keine Artikel, jedoch eine einzige Marke, wird direkt auf die passende Marken-Seite Ihres Shops weitergeleitet. Diese Option erfordert die "Suche in Marken- und Lieferantennamen". Der Benutzer verlässt damit die Suchfunktion des Shops, seine Sucheinstellungen sind dann nicht mehr verfügbar.',
    'D3_EXTSEARCH_NAVI_CONTENTS'                      => 'Informationsseiten / CMS-Texte',
    'D3_EXTSEARCH_NAVI_CONTENTLIST'                   => 'suche in CMS-Texten',
    'D3_EXTSEARCH_NAVI_CONTENTLIST_DESC'              => 'Neben Artikeln können Sie auch entsprechend markierte Texte suchen lassen. Setzen Sie dazu den entsprechenden Haken bei den jeweiligen CMS-Bausteinen ("Kundeninformationen > CMS-Seiten"). Die Texte werden in der regulären Trefferliste gezeigt. <br><br>Diese Option ist auch notwendig, wenn Texte zusätzlich in den Schnelltreffern gezeigt werden sollen. Setzen Sie die entsprechende Option dann auch im Tab "Schnelltreffer".',
    'D3_EXTSEARCH_NAVI_ATTRIBUTEFILTER'               => 'Attributfilter',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST'                 => 'zeige Attributsliste',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_DESC'            => 'Aktivieren Sie diese Option, wenn auch nach Attributen gefiltert werden soll.<br>Jedes Attribut kann in dessen Einstellungen ("Artikel verwalten > Attribute") von der Filterung ausgeschlossen werden, wenn dies nicht sinnvoll ist.',
    'D3_EXTSEARCH_NAVI_ATTRIBUTES_COMBINE'            => 'mehrfache Attributselektionen werden mit "ODER" verknüpft',
    'D3_EXTSEARCH_NAVI_ATTRIBUTES_COMBINE_DESC'       => 'Aktivieren Sie diese Option, wenn beispielsweise bei gewählter Farbe und gewähltem Material auch Artikel gezeigt werden sollen, die nur eine der Eigenschaften haben. Ohne diese Option werden nur Artikel gezeigt, die beide Eigenschaften gleichzeit besitzen.',
    'D3_EXTSEARCH_NAVI_ATTRIBUTES_SORT'               => 'Attribute sortiert nach',
    'D3_EXTSEARCH_NAVI_ATTRIBUTES_SORT_POS'           => 'eingestellter Attributsposition',
    'D3_EXTSEARCH_NAVI_ATTRIBUTES_SORT_TITLE'         => 'Attributstitel',
    'D3_EXTSEARCH_NAVI_ATTRIBUTES_SORT_DESC'          => 'Hier definieren Sie die Reihenfolge der angezeigten Attribute.',
    'D3_EXTSEARCH_NAVI_ATTRIBUTEVALUES_COMBINE'       => 'mehrfache Attributwertselektionen ("Mehrfachauswahl") werden mit "UND" verknüpft',
    'D3_EXTSEARCH_NAVI_ATTRIBUTEVALUES_COMBINE_DESC'  => 'Aktivieren Sie diese Option, wenn beispielsweise bei gewählter Farbe "rot" und "grün" nur Artikel gezeigt werden sollen, die beide Farben gleichzeitig haben. Ohne diese Option werden auch Artikel gezeigt, die nur eine der beiden Eigenschaften besitzen.',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_SORT'            => 'Attributswerte sortiert nach',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_SORT_COUNT'      => 'Anzahl der enthaltenen Artikel',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_SORT_POS'        => 'eingestellter Attributslistenposition',
    'D3_EXTSEARCH_NAVI_NOATTRIBUTEARTS'               => 'auch nach nicht dem jeweiligen Attribut zugeordneten Artikeln filtern',
    'D3_EXTSEARCH_NAVI_NOATTRIBUTEARTS_DESC'          => 'Die Attributsfilter bieten mit dieser Option die Wahlmöglichkeit, auch nach Artikeln zu filtern, die z.B. ausdrücklich keiner Farbe oder keinem Material zugeordnet sind.',
    'D3_EXTSEARCH_NAVI_SHOWNOTSELECTABLEATTRIBUTES'   => 'nicht wählbare Attributswerte werden nicht ausgeblendet',
    'D3_EXTSEARCH_NAVI_SHOWNOTSELECTABLEATTRIBUTES_DESC' => 'Bei der Artikelfilterung über Attribute werden andere, nicht mehr wählbare Attribute normalerweise ausgeblendet. Aus optischen Gründen kann es dennoch notwendig sein, diese anzuzeigen. Mit dieser Option werden diese Attributswerte informatorisch gelistet, sind jedoch ausgegraut.<br>Beachten Sie, dass zur Ermittlung dieser Attribute eine zusätzliche Datenabfrage ausgeführt wird. Je nach Artikel-Attributs-Struktur kann dies zusätzliche Ladezeit benötigen.',
    'D3_EXTSEARCH_NAVI_CONTENTSEARCHINLONGTEXT'       => 'in CMS-Texten auch Langtexte durchsuchen',
    'D3_EXTSEARCH_NAVI_CONTENTLONG_DESC'              => 'Legen Sie fest, ob auch in den Langtexten der CMS-Bausteine gesucht werden soll.',
    'D3_EXTSEARCH_NAVI_SMALLLISTITEMS'                => 'Kategorie-, Lieferanten-, Marken- und Textlisten begrenzen<br>(Kunde kann alle Treffer auf Wunsch anzeigen, funktioniert nur bei "Linklisten")',
    'D3_EXTSEARCH_NAVI_SMALLLISTITEMS_2'              => ' Einträge',
    'D3_EXTSEARCH_NAVI_SMALLLISTITEMS_DESC'           => 'Bei vielen Suchtreffern kann auch die Kategorie-, Marken-, Lieferanten- und Textliste sehr lang werden. Die Artikeltreffer rutschen so vielleicht nach unten aus dem Anzeigebereich heraus. Beschränken Sie die Anzahl der angezeigten Kategorien und Marken, um diese Listen kurz zu halten. Werden diese Listen dann tatsächlich gekürzt, steht Ihrem Kunden eine Schaltfläche zur Verfügung, um diese Listen auf Wunsch komplett anzuzeigen.',
    'D3_EXTSEARCH_NAVI_ALISTFILTER'                   => 'Filter werden auch in Artikellisten gezeigt',
    'D3_EXTSEARCH_NAVI_ALISTFILTER_DESC'              => 'Auch Artikellisten können mit Filtern eingeschränkt werden. Filterungen sind in Kategorieansichten, Hersteller- und Lieferantenlisten möglich. Als Filter stehen die Einschränkungen über Kategorien, Hersteller, Lieferanten, Attribute oder Preise zur Verfügung. Als Optionen werden die Einstellungen für die Suche verwendet.<br>Ist dieser Eintrag nicht wählbar, ist diese Option wahrscheinlich in Ihrer Modullizenz nicht enthalten. Lassen Sie Ihre Lizenz hierfür erweitern.',
    'D3_EXTSEARCH_NAVI_PRICELIST'                     => 'zeige Preiskategorien',
    'D3_EXTSEARCH_NAVI_PRICEFILTER'                   => 'Preisfilter',
    'D3_EXTSEARCH_NAVI_PRICELIST_DESC'                => 'Alle gefundenen Artikel werden in Preiskategorien aufgeteilt und diese als weitere Filterkriterien angeboten. So kann der Kunde eine gewisse Preisspanne für seine gewünschten Artikel wählen. Rabatte sind in den Kategoriepreisen nicht berücksichtig. Gefundene Artikel sind in dem Fall preiswerter, als die Suchanfrage vorgibt.',
    'D3_EXTSEARCH_NAVI_PRICELIST_ITEMS'               => 'maximale Anzahl der Preiskategorien',
    'D3_EXTSEARCH_NAVI_PRICELIST_ITEMS_DESC'          => 'So viele Preisspannen werden maximal angezeigt. Im Normalfall kann dies jedoch weniger sein, da leere Preisspannen (also ohne enthaltene Artikel) ausgefiltert werden.',
    'D3_EXTSEARCH_NAVI_PRICELIST_ROUNDED'             => 'Preisspannen werden gerundet',
    'D3_EXTSEARCH_NAVI_PRICELIST_ROUNDED_DESC'        => 'Die kleinste Preisspanne beginnt beim kleinstmöglichen Preis, die größte Preisspanne erstreckt sich bis zum höchten Preis. Die Grenzen dazwischen werden errechet. Diese können unter Umständen jedoch bei krummen Cent-Beträgen liegen. Mit der Option werden die Preise der Spannen gerundet, die Spannen sind jedoch dann weniger aussagekräftig.',
    'D3_EXTSEARCH_NAVI_PRICELIST_DISPLAY'             => 'Anzeige der Preisspannen',
    'D3_EXTSEARCH_NAVI_PRICELIST_DISPLAY_DESC'        => 'Die Benutzung der Preisspannen über Schieberegler ist aus Gründen der Bedienbarkeit nicht in mobilen Templates möglich. Dort werden die Preisspannen weiterhin als DropDown gezeigt.',
    'D3_EXTSEARCH_NAVI_PRICELIST_DISPLAY_LISTTYPE'    => 'als Dropdown',
    'D3_EXTSEARCH_NAVI_PRICELIST_DISPLAY_SLIDER'      => 'als jQuery-Schieberegler',
    'D3_EXTSEARCH_NAVI_PRICELIST_REQU'                => '* jQuery-Schieberegler erfordert installiertes jQuery-Framework in aktueller Version (getestet mit Version 1.4.2) mit Komponenten "jQueryUI Core", "jQueryUI Widget", "jQueryUI Mouse" und "jQueryUI Slider".',
    'D3_EXTSEARCH_NAVI_HIGHLIGHT'                     => 'gefundene Textstellen werden in Suchergebnissen hervorgehoben',
    'D3_EXTSEARCH_NAVI_HIGHLIGHT_DESC'                => 'Manchmal taucht der gesuchte Begriff erst mitten in Beschreibungen auf. Mit dieser Option heben Sie den Begriff optisch hervor.<br><br>Stellen Sie dazu im Template \'d3_ext_search_highlight.tpl\' ein, wie die Hervorhebung aussehen soll. Ersetzen Sie dann in \'inc/product.tpl\' alle Variablen, die Hervorhebungen enthalten sollen, gegen den Smarty-Aufruf \[\{ d3_extsearch_highlight text=$variablenname \}\], wobei $variablenname gegen die tatsächliche Textvariable ersetzt wird.',
    'D3_EXTSEARCH_NAVI_INDEXFILTER'                   => 'Buchstabenindex',
    'D3_EXTSEARCH_NAVI_SHOWINDEX'                     => 'zeige Buchstabenindex',
    'D3_EXTSEARCH_NAVI_SHOWINDEX_DESC'                => 'Der Buchstabenindex gibt Ihren Kunden die Möglichkeit, die Suchtreffer weiter nach dem Anfangsbuchstaben einzuschränken.<br><br>Die Buchstabenliste selbst können Sie im Template \'d3_inc_ext_search.tpl\' bearbeiten.',
    'D3_EXTSEARCH_NAVI_FILTERFIELDNAME'               => 'Feldname, nach dem gefiltert wird',
    'D3_EXTSEARCH_NAVI_FILTERFIELDNAME_DESC'          => 'Möglich sind hier alle Felder aus der Tabelle oxarticles (ohne Sprachzusatz).',
    'D3_EXTSEARCH_NAVI_OWNFORMFIELDS'                 => 'individuelle Filter',
    'D3_EXTSEARCH_NAVI_SAVE'                          => 'Speichern',

    'D3_EXTSEARCH_QUICK'                              => 'Schnelltreffer',
    'D3_EXTSEARCH_QUICK_ACTIVE'                       => 'bei Eingabe des Suchbegriffs werden Vorschläge geliefert (wird nur bei Nutzern mit aktiviertem JavaScript angezeigt)',
    'D3_EXTSEARCH_QUICK_ACTIVE_DESC'                  => '<img src="../modules/d3/extsearch/out/admin/img/d3_extsearch_quicksearch.jpg"><br>Geben Sie Ihrem Kunden die Möglichkeit, Artikel noch schneller zu finden. Die Schnellsuche stellt schon während der Eingabe des Suchbegriffs die ersten Treffer in einem eigenen Rahmen dar.<br>In mobilen Ansichten kann die Schnelltrefferliste aus Gründen der Bedienbarkeit nicht gezeigt werden.',
    'D3_EXTSEARCH_QUICK_FULLOBJECTS'                  => 'Schnellsuche lädt komplette Objekte, statt performanceoptimierter Zuweisung',
    'D3_EXTSEARCH_QUICK_FULLOBJECTS_DESC'             => 'Für die gewöhnliche Darstellung der Schnellsuche reicht eine performanceoptimierte Zuweisung der Ergebnisdaten. Für die Anzeige von bestimmten Informationen (z.B. berechnete Preise etc.) ist es erforderlich, die kompletten Objekte zu laden. Dies vermindert jedoch die Ladegeschwindigkeit.',
    'D3_EXTSEARCH_QUICK_COUNT'                        => 'maximale Anzahl der zu ladenden Artikel in der Schnellsuche',
    'D3_EXTSEARCH_QUICK_COUNT_DESC'                   => 'Aus Performancegründen werden die Schnellsuchtreffer nur bis zu dieser definierten Anzahl gezeigt. Werden mehr Treffer gefunden, blendet sich die Artikelliste nicht ein, statt dessen wird ein Hinweis gezeigt. Erhöhen Sie den Wert, wenn Sie für häufig vorkommende Suchbegriffe keine Schnelltreffer erhalten. Kontrollieren Sie aber bitte unbedingt danach die Last Ihres Servers / Accounts. Der Standardwert ist 200.',
    'D3_EXTSEARCH_QUICK_LOADCATEGORIES'               => 'zusätzlich auch nach entsprechend benannten Kategorien suchen',
    'D3_EXTSEARCH_QUICK_LOADCATEGORIES_DESC'          => 'Neben Artikeln werden in der Schnellsuche auch Kategorien gesucht. Beachten Sie bitte, dass diese Option zusätzliche Resourcen verbraucht, die die Schnellsuche langsamer werden lassen.',
    'D3_EXTSEARCH_QUICK_LOADMANUFACTURERS'            => 'zusätzlich auch nach entsprechend benannten Marken suchen',
    'D3_EXTSEARCH_QUICK_LOADMANUFACTURERS_DESC'       => 'Neben Artikeln werden in der Schnellsuche auch Marken gesucht. Beachten Sie bitte, dass diese Option zusätzliche Resourcen verbraucht, die die Schnellsuche langsamer werden lassen.',
    'D3_EXTSEARCH_QUICK_LOADVENDORS'                  => 'zusätzlich auch nach entsprechend benannten Lieferanten suchen',
    'D3_EXTSEARCH_QUICK_LOADVENDORS_DESC'             => 'Neben Artikeln werden in der Schnellsuche auch Lieferanten gesucht. Beachten Sie bitte, dass diese Option zusätzliche Resourcen verbraucht, die die Schnellsuche langsamer werden lassen.',
    'D3_EXTSEARCH_QUICK_LOADCONTENT'                  => 'zusätzlich auch nach entsprechend benannten Texten suchen',
    'D3_EXTSEARCH_QUICK_LOADCONTENT_DESC'             => 'Neben Artikeln werden in der Schnellsuche auch Texte gesucht. Beachten Sie bitte, dass diese Option zusätzliche Resourcen verbraucht, die die Schnellsuche langsamer werden lassen.<br><br>Für die Verwendung dieser Option ist es erforderlich, dass die Textsuche auch für die reguläre Trefferliste aktiviert ist (Tab "Grundeinstellungen").',
    'D3_EXTSEARCH_QUICK_CMPLOBJ'                      => 'vor Oxid 4.3.0: komplettes Artikel-Objekt laden, sonst nur ID, Titel und Icon.<br>Nur bei Bedarf aktivieren, verbraucht mehr Ressourcen. ',
    'D3_EXTSEARCH_QUICK_CMPLOBJ_DESC'                 => 'Die Darstellung der Schnelltreffer kann von Ihnen in einem Template grafisch an Ihren Shop angepaßt werden. Vielleicht benötigen Sie für Ihre gewünschte Darstellung noch weitere Daten außer dem Arikelnamen und dem Link zum Artikel. So lassen sich z.B. auch Miniaturbilder, der Preis oder auch gleich ein Warenkorbbutton einblenden. Dazu benötigen Sie jedoch Informationen, die so im Standard nicht verfügbar sind. Setzen Sie diesen Haken, um alle Artikeldaten verfügbar zu machen.<br><br>Ab Shopversion 4.3.0 ist es unbedingt notwendig, das komplette Artikelobjekt zu laden. Diese Einstellung wird dann ignoriert.',
    'D3_EXTSEARCH_QUICK_LOADVARIANTS'                 => 'Variantenartikel laden und in der Schnellsuche anzeigen<br>Tragen Sie dazu in den Suchfeldern zusätzlich \'oxvarselect\' ein.',
    'D3_EXTSEARCH_QUICK_LOADVARIANTS_DESC'            => 'Normalerweise sucht die Shopsuche nicht nach Artikelvarianten. Haben Sie jedoch viele Variantenartikel in Ihrem Shop, kann es sinnvoll sein, die Suche dafür freizuschalten.',
    'D3_EXTSEARCH_QUICK_SAVE'                         => 'Speichern',
    'D3_EXTSEARCH_QUICK_TPLNOTICE'                    => 'Hinweis: Um das Fenster der Schnellsuche grafisch anzupassen, erweitern Sie die Templateblöcke in \'d3_ext_search_suggestsearch.tpl\'.',
    'D3_EXTSEARCH_QUICK_IAS'                          => 'interaktive Suche (Markier-Suche)',
    'D3_EXTSEARCH_QUICK_SHOWIAS'                      => 'zeige interaktive Suche (Markier-Suche)',
    'D3_EXTSEARCH_QUICK_SHOWIAS_DESC'                 => 'Markieren Sie im Shop ein Wort, wird Ihnen in dessen Nähe ein kleines Formular eingeblendet, mit dessen Hilfe Sie sofort nach dem markierten Wort suchen können. Klicken Sie an eine andere Stelle im Shop, verschwindet das Fenster wieder.',

    'D3_EXTSEARCH_STAT_TYPE'                          => 'Auswertung:',
    'D3_EXTSEARCH_STAT_NOHITS'                        => 'keine Auswertungen vorhanden',
    'D3_EXTSEARCH_STAT_NOREPORTBASE'                  => 'Ihr Shop unterstützt diese Auswertungen leider nicht.',
    'D3_EXTSEARCH_STAT_NOREPORTBASE_DESC'             => 'Für die Verwendung der Statistik ist die OXID-Klasse "OeStatistics_Report_Base" erforderlich. Im OXID eShop wird dieses Script durch ein separat zu installierendes Modul "Statistiken" bereitgestellt. Daher kann die grafische Auswertung in Ihrem Shop ohne dessen Installation leider nicht genutzt werden.',
    'D3_EXTSEARCH_STAT_TYPEHITLESS'                   => 'Suchabfragen ohne Treffer',
    'D3_EXTSEARCH_STAT_TYPEMOSTHITS'                  => 'Suchabfragen mit den meisten Treffern',
    'D3_EXTSEARCH_STAT_TYPEMOSTSEARCHES'              => 'häufigste Suchbegriffe',
    'D3_EXTSEARCH_STAT_LANG'                          => 'Sprache:',
    'D3_EXTSEARCH_STAT_TIME'                          => 'Zeitraum:',
    'D3_EXTSEARCH_STAT_GENERATESTAT'                  => 'Auswertung erstellen',
    'D3_EXTSEARCH_STAT_SEARCHWORD'                    => 'Suchwort',
    'D3_EXTSEARCH_STAT_HITS'                          => 'Treffer',
    'D3_EXTSEARCH_STAT_SEARCHES'                      => 'Anfragen',
    'D3_EXTSEARCH_STAT_TYPES_CATEGORY'                => 'Kategorie',
    'D3_EXTSEARCH_STAT_TYPES_PRICE'                   => 'Preis',
    'D3_EXTSEARCH_STAT_TYPES_VENDOR'                  => 'Lieferant',
    'D3_EXTSEARCH_STAT_TYPES_MANUFACTURER'            => 'Marken',
    'D3_EXTSEARCH_STAT_TYPES_OWNLIKE'                 => 'eig. Suchfeld (LIKE)',
    'D3_EXTSEARCH_STAT_TYPES_OWNIS'                   => 'eig. Suchfeld (IS)',
    'D3_EXTSEARCH_STAT_TYPES_OWNVALUE'                => '%s => "%s"',
    'D3_EXTSEARCH_STAT_TYPES_ATTRIBUTE'               => 'Attribute',
    'D3_EXTSEARCH_STAT_TYPES_INDEXLETTER'             => 'Indexbuchstabe',
    'D3_EXTSEARCH_STAT_TYPES_UNKNOWN'                 => 'unbekannte Filterung',
    'D3_EXTSEARCH_STAT_STATDESC_HITLESS'              => 'ergebnislose Suchanfragen in %s nach "%s" ',
    'D3_EXTSEARCH_STAT_STATDESC_MOSTSEARCHES'         => 'Suchanfragen in %s nach "%s" ',
    'D3_EXTSEARCH_STAT_NOITEMS'                       => 'für die Einstellungen sind keine Einträge vorhanden',
    'D3_EXTSEARCH_STAT_NOITEMS_DESC'                  => 'Wenn Sie hier Daten erwartet haben, kontrollieren Sie bitte, ob die Statistikerfassung in den Moduleinstellungen passend aktiviert ist.',
    'D3_EXTSEARCH_STAT_SELECTFILTER'                  => 'Setzen Sie den gewünschten Filter und schicken Ihre Auswahl ab, um Ergebnisse zu erhalten.',

    'D3_EXTSEARCH_PLUGIN_SETTINGS'                    => 'Einstellungen',
    'D3_EXTSEARCH_PLUGIN_SEARCHACTIVE'                => 'dem Nutzer im Browser anbieten, das Such-Plugin zu installieren',
    'D3_EXTSEARCH_PLUGIN_SEARCHACTIVE_DESC'           => 'Im Internet Explorer ab Version 7 und auch im Firefox ab Version 2 finden Sie im rechten oberen Eck eine Möglichkeit, von jeder beliebigen Stelle im Internet aus die wichtigsten Suchmaschinen zu starten. Bieten Sie Ihren Kunden an, auch Ihren Shop in diese Liste hinzuzufügen. So reicht es, in der Drop-Down-Box Ihren Shop auszuwählen und den Suchbegriff einzugeben. Sofort wird Ihr Shop mit den Suchtreffern gezeigt. Als Text wird Ihr Shoptitel verwendet, ein Icon können Sie weiter unten festlegen.',
    'D3_EXTSEARCH_PLUGIN_INSTALLLINK'                 => 'einen Installationslink in der Shop-Suche anzeigen',
    'D3_EXTSEARCH_PLUGIN_INSTALLLINK_DESC'            => 'Kann Ihr Kunden Ihren Shop in die Suchmaschinenliste hinzufügen, wird dies im Browser durch eine farbige Umrandung angezigt. Dies ist jedoch nur wenig auffällig, viele Nutzer übersehen dies. Stellen Sie in den Suchergebnissen besser noch einen zusätzlichen Link dar, um auf diese Funktion hinzuweisen.',
    'D3_EXTSEARCH_PLUGIN_SEARCHICON'                  => 'Icon für Browserplugin',
    'D3_EXTSEARCH_PLUGIN_CHOOSEICON'                  => 'Bitte wählen Sie noch ein Icon.',
    'D3_EXTSEARCH_PLUGIN_SEARCHICON_DESC'             => 'Legen Sie hier das Icon fest, welches im Browser-Plugin angezigt werden soll. Das Icon muß ein Größe von 16 x 16 Pxeln haben und im PNG- oder JPG-Format vorliegen.',
    'D3_EXTSEARCH_PLUGIN_SAVE'                        => 'Speichern',
    'D3_EXTSEARCH_PLUGIN_GENERATE'                    => 'Generierung',
    'D3_EXTSEARCH_PLUGIN_GENERATE_DESC'               => 'Haben Sie Ihren Shoptitel geändert, ein neues Icon festgelegt oder sogar Ihren Shop auf eine neue Adresse umgezogen, ist es nötig, das Suchplugin zu aktualisieren. Weisen Sie bitte auch Ihre Kunden darauf hin, das Plugin zu aktualisieren. Es erneuert sich nicht automatisch.',
    'D3_EXTSEARCH_PLUGIN_STARTGENERATING'             => 'Erstellung durchführen',
    'D3_EXTSEARCH_PLUGIN_GENERATEFILE'                => 'Installations-Datei erstellen:',
    'D3_EXTSEARCH_PLUGIN_GENERATENOTICE'              => 'Mit der Erstellung der Installations-Datei haben Sie alle erforderlichen Schritte durchgeführt. Startet Ihr Kunde die Integration, wird diese Datei automatisch von Ihrem Server ausgelesen.',
    'D3_EXTSEARCH_PLUGIN_CREATE_SUCC'                 => 'Plugindatei wurde erfolgreich generiert.',
    'D3_EXTSEARCH_PLUGIN_CREATE_NSUCC'                => 'Plugindatei konnte nicht erstellt werden.',

    'D3_EXTSEARCH REPORT_MOSTSEARCHES'                => 'Suchbegriffe (nur im Suchmodul verfgb.)',
    'D3_EXTSEARCH_STATISTIC_MOSTSEARCHES'             => 'häufigste Suchbegriffe',
    'D3_EXTSEARCH_STATISTIC_MOST_DESC'                => 'So oft wurde der gewählte Begriff gesucht',
    'D3_EXTSEARCH_STATISTIC_FURTHERFILTERS'           => '(durch weitere Filter eingeschränkt)',
    'D3_EXTSEARCH_STATISTIC_GRAPH'                    => 'grafische Auswertung',

    'D3_EXTSEARCH_CONTENT_SEARCHABLE'                 => '<img src="../modules/d3/modcfg/public/d3logo.php" alt="D³" title="D³ Data Development"> CMS kann gesucht werden',
    'D3_EXTSEARCH_PUSH'                               => '<img src="../modules/d3/modcfg/public/d3logo.php" alt="D³" title="D³ Data Development"> Wichtigkeit des Artikels im Sortiment',
    'D3_EXTSEARCH_PUSH_1'                             => 'normal',
    'D3_EXTSEARCH_PUSH_2'                             => 'wichtiger',
    'D3_EXTSEARCH_PUSH_3'                             => 'besonders wichtig',
    'D3_EXTSEARCH_PUSH_DESC'                          => 'D³ Modul "erweiterte Suche": Die Wichtigkeit definiert die erste Reihenfolge der Artikel in der Suche (bei Verwendung der "erweiterten Suche"). In Verbindung mit Feldrelevanz funktioniert die Wichtigkeit als Faktor. Besonders wichtige Artikel haben zum Beispiel die 3 fache Relevanz von normal gewichteten Artikeln. Beachten Sie dies auch bei der Vergabe der Feldrelevanz.',

    'D3_EXTSEARCH_ATTRIBUTE_NOTUSE4FILTER'            => '<img src="../modules/d3/modcfg/public/d3logo.php" alt="D³" title="D³ Data Development"> Attribut wird in Suche für Filter NICHT verwendet',
    'D3_EXTSEARCH_CATEGORY_NOTUSE4FILTER'             => '<img src="../modules/d3/modcfg/public/d3logo.php" alt="D³" title="D³ Data Development"> Kategorie wird in Suche für Filter und Kategorieergebnisse NICHT verwendet',

    'D3_EXTSEARCH_SYNED_NOLEXICON'                    => 'Das semantische Lexikon ist nicht installiert! Weitere Informationen hierzu finden Sie im Modulhandbuch.',
    'D3_EXTSEARCH_SYNED_WORD'                         => 'Wort',
    'D3_EXTSEARCH_SYNED_WORD_DESC'                    => 'Suchen Sie nach einem bestimmten Begriff, geben Sie diesen hier ein und senden die Eingabe ab.',
    'D3_EXTSEARCH_SYNED_ALTWORD'                      => 'sinnähnliche Worte',
    'D3_EXTSEARCH_SYNED_SYNSETID'                     => 'Synonym-ID',
    'D3_EXTSEARCH_SYNED_SYNSETID_DESC'                => 'Suchen Sie nach einer bestimmten Synonym-ID, geben Sie diese hier ein und senden die Eingabe ab.',
    'D3_EXTSEARCH_SYNED_SAVENEWSYN'                   => 'neues Synonym speichern',
    'D3_EXTSEARCH_SYNED_SAVENEWSYN_DESC'              => 'Legen Sie hier einen weiteren Begriff für die gewählte Bedeutung ab.',
    'D3_EXTSEARCH_SYNED_DELETESYN'                    => 'Soll das Synonym wirklich gelöscht werden?',

    'D3_EXTSEARCH_SYNED_MAIN_NEWWORD'                 => 'Neues Wort / Wortgruppe',

    'D3_EXTSEARCH_SYNED_MAIN_WORD'                    => 'Wort / Wortgruppe:',
    'D3_EXTSEARCH_SYNED_MAIN_WORD_DESC'               => 'Möchten Sie für eine neue Wortbedeutung passende Begriffe anlegen, notieren Sie hier den ersten Begriff. Fügen Sie den Begriff hier nur ein, wenn die Wortbedeutung noch nicht im Lexikon existiert. Ansonsten tragen Sie den neuen Begriff in der passenden Bedeutung im Tab "Synonyme bearbeiten" nach.',
    'D3_EXTSEARCH_SYNED_MAIN_COMMENT'                 => 'Kommentar:',
    'D3_EXTSEARCH_SYNED_MAIN_COMMENT_DESC'            => 'Der Kommentar dient ausschließlich dazu, weitere interne Erklärungen zum Begriff ablegen zu können. Er wird für die Suche nicht verwendet.',
    'D3_EXTSEARCH_SYNED_MAIN_SYNSETID'                => 'Synonym-ID:',
    'D3_EXTSEARCH_SYNED_MAIN_SYNSETID_DESC'           => 'Unter einer einheitlichen Synonym-ID werden alle Begriffe mit gleicher Bedeutung abgelegt. Bei Neueinträgen wird automatisch eine neue ID vergeben. Wurde ein Begriff versehentlich der falschen Bedeutung zugewiesen, suchen Sie sich aus der passenden Bedeutung die Synonym-Id und ändern diese an Ihrem Begriff.',
    'D3_EXTSEARCH_SYNED_MAIN_LANGUAGE'                => 'Sprache:',
    'D3_EXTSEARCH_SYNED_MAIN_LANGUAGE_DESC'           => 'Bestimmen Sie hieran, aus welcher Sprache der ausgewählte Begriff stammt und in welcher dieser verwendet werden soll. Es stehen nur die im Shop aktivierten Sprachen zur Verfügung.',
    'D3_EXTSEARCH_SYNED_MAIN_LANGUAGE_DISABLED'       => '(deaktiviert)',

    'D3_EXTSEARCH_SYNED_MANAGE_DESC'                  => 'Die hier gezeigten Synonyme sind alternative Begriffe für die oben gewählte Bedeutung.',
    'D3_EXTSEARCH_SYNED_MANAGE_EDIT'                  => 'bearbeiten',
    'D3_EXTSEARCH_SYNED_MANAGE_EDIT_DESC'             => 'Möchten Sie zusätzliche Details zu dem Begriff hinterlegen oder diesen einer anderen Bedeutung zuordnen, klicken Sie auf das Symbol. Der Adminbereich wechselt zum Bearbeitungsbereich für genau den Begriff.',
    'D3_EXTSEARCH_SYNED_MANAGE_SYNONYM'               => 'Synonym',

    'D3_EXTSEARCH_UPDATE_GENPHONETIC'                 => '"erweiterte Suche": Das Modulupdate führte Änderungen in der Datenbankstruktur für die Ähnlichkeitssuche aus. Aktualisieren Sie deshalb nach Abschluss dieser Installation den Suchindex im Adminbereich des Moduls.',

    'GENERAL_ARTICLE_D3_PHONETIC'                     => 'erwSuche - phonetischer Index',
    // Multilang-Fields for importer
    'GENERAL_ARTICLE_D3_SEARCHINDEXDATE'              => 'erwSuche - Datum letzte Indizierung',
    // Multilang-Fields for importer
    'GENERAL_ARTICLE_D3PUSH'                          => 'erwSuche - Artikelwichtigkeit',
    // Multilang-Fields for importer
    'GENERAL_ARTICLE_OXVARSELECT'                     => 'Variantentitel',

);
