<?php

/**
 * This Software is the property of Data Development and is protected
 * by copyright law - it is NOT Freeware.
 *
 * Any unauthorized use of this software without a valid license
 * is a violation of the license agreement and will be prosecuted by
 * civil and criminal law.
 *
 * http://www.shopmodule.com
 *
 * @copyright (C) D3 Data Development (Inh. Thomas Dartsch)
 * @author    D3 Data Development - Daniel Seifert <support@shopmodule.com>
 * @link      http://www.oxidmodule.com
 */

$sLangName = "Deutsch";
// -------------------------------
// RESOURCE IDENTITFIER = STRING
// -------------------------------
$aLang = array(

//Navigation
    'charset'                                         => 'UTF-8',
    'd3mxextsearch'                                   => '<i class="fa fa-fw fa-search-plus"></i> Erweiterte Suche',
    'd3mxextsearch_settings'                          => 'Einstellungen',
    'd3mxextsearch_statistic'                         => 'Statistik',
    'd3mxextsearch_syneditor'                         => 'Synonym-Editor',
    'd3tbclextsearch_syneditor_main'                  => 'Stamm',
    'd3tbclextsearch_syneditor_manage'                => 'Synonyme bearbeiten',
    'd3tbclextsearch_syneditor_family'                => 'Wortverwandtschaften',
    'd3tbclextsearch_syneditor_synset'                => 'Synonymgruppe bearbeiten',
    'd3tbclextsearch_settings_results'                => 'Grundeinstellungen',
    'd3tbclextsearch_settings_navigation'             => 'Filter + Anzeige',
    'd3tbclextsearch_settings_quick'                  => 'Schnelltreffer',
    'd3tbclextsearch_settings_browser'                => 'Browser-Plugin',
    'd3tbclextsearch_settings_content'                => 'Content-Suche',
    'd3tbclextsearch_settings_statistik'              => 'Statistik',

    'D3_EXTSEARCH_LIST_SETTLANG'                      => 'Einstellungen für Sprache',
    'D3_EXTSEARCH_HELPLINK'                           => 'Fragen-zu-speziellen-Modulen/Erweiterte-Suche/',
    'D3_EXTSEARCH_HELPLINK_CONFIG'                    => '',

    'D3_EXTSEARCH_TRANSL'                             => 'Erweiterte Suche',

    'D3_EXTSEARCH_CONFIGVARS_SADDTITLE'               => 'Modul-Edition:',
    'D3_EXTSEARCH_CONFIGVARS_BLUSEFILTERINARTICLELISTS' => 'Filter in Artikellisten verfügbar:',
    'D3_EXTSEARCH_CONFIGVARS_FEATUREBIT1'             => 'Filter in Artikellisten verfügbar:',

    'D3_EXTSEARCH_MAIN_DEBUGACTIVE_DESC'              => 'Der Debugmodus gibt die verwendeten Datenbankabfragen zur einfacheren Programmierung und Fehlersuche in der Browser-Konsole und FirePHP-Konsole aus (Ajax-Requests können aus technischen Gründen nur in FirePHP ausgegeben werden). Zur Anzeige der Abfragen installieren Sie bitte das FirePHP-AddOn für Ihren Browser. Alternativ verwenden Sie den GET-Parameter "d3forcedebug=1" am Ajax-Request für erzwungene Debugausgaben. Deaktivieren Sie den Debugmodus bitte unbedingt für den Livebetrieb, da mit aktiviertem Debugmodus das Datenbank-Caching nicht verwendet wird.',
    'D3_EXTSEARCH_MAIN_MAINSETTINGS'                  => 'allgemeine Einstellungen',
    'D3_EXTSEARCH_MAIN_FIELDLIST'                     => 'diese Felder für die Ähnlichkeitssuche und die Schnellsuche verwenden<br>Relevanz => Feldname (Bsp.: 50 => oxtitle)',
    'D3_EXTSEARCH_MAIN_SORTDEBUG'                     => 'Ergebnis-Feld-Analyse',
    'D3_EXTSEARCH_MAIN_SORTDEBUG_DESC'                => 'Geben Sie Ihren Suchbegriff ein. <br>In der Tabelle werden zum Artikel auch die Relevanzwerte zu jedem Feld ausgegeben, in welchem der Treffer gefunden wurde. Die Relevanzwerte "... in / im ..." definieren Sie in den Einstellungen der "erweiterten Suche". "D3PUSH" ist die Wichtigkeit des Artikels. Die Relevanz jedes Artikels in der Trefferliste ("d3Priority") ergibt sich aus der folgenden Formel: <blockquote>((Summe aus allen "... in / im ..."-Feldern) x D3PUSH) + D3PUSH</blockquote>',
    'D3_EXTSEARCH_MAIN_SORTDEBUG_START'               => 'Suche starten',
    'D3_EXTSEARCH_MAIN_SORTDEBUG_WORD_IN_'            => '"%1$s" als komplettes Wort im Feld "%2$s"',
    'D3_EXTSEARCH_MAIN_SORTDEBUG_PART_IN_'            => '"%1$s" als Wortbestandteil im Feld "%2$s"',
    'D3_EXTSEARCH_MAIN_SORTDEBUG_article_IN_category' => 'Artikel in Kategorie',
    'D3_EXTSEARCH_MAIN_SORTDEBUG_article_IN_manufacturer' => 'Artikel in Hersteller oder Lieferant',
    'D3_EXTSEARCH_MAIN_NOFIELDSDEFINED'               => '<b>Keine Felder definiert.</b><br>Standard: \'oxtitle\', \'oxsearchkeys\' und \'oxartnum\'',
    'D3_EXTSEARCH_MAIN_FIELDLIST_DESC'                => 'Tragen Sie hier die Artikel-Tabellenfelder (aus Tabellen "oxarticles" oder "oxartextends") ein, in denen gesucht werden soll. Die Feldbezeichnungen entnehmen Sie bitte der Shopdatenbank. Die Standardeinträge sind oxtitle, oxsearchkeys, oxartnum. Damit wird regulär im Titel, den Suchbegriffen und der Artikelnummer gesucht. Tragen Sie jedes Feld in eine separate Zeile, gefolgt von einem Zeilenumbruch ein. Für weitere Optionen des Moduls kann es nötig sein, hier noch Einträge hinzuzufügen. Ändern Sie diese Eintragungen, muß der Suchindex noch einmal neu erzeugt werden.<br><br>Neben den Feldern können Sie hier auch angeben, wie wichtig das jeweilige Datenfeld für die Ergebnisse ist. Tragen Sie vor den Feldnamen mit => getrennt die Relevanz des jeweiligen Feldes ein. Je höher die Relevanz, umso höher wird ein Artikel gezeigt, wenn der Suchbegriff in diesem Feld vorkommt (separat zu aktivieren). Wird der Suchbegriff in mehreren Feldern gefunden, addiert sich die Relevanz. Ist keine Relevanz angegeben, erhält das Feld automatisch den Wert 10. Weitere Informationen hierzu finden Sie im Handbuch im Kapitel "Relevanz und Wichtigkeiten".',
    'SHOP_CONFIG_SEARCHFIELDS'                        => 'Felder, in denen gesucht wird<br>"erweiterte Suche" verwendet eigene Einstellungen / Bearbeiten in <input type="button" onclick="document.getElementById(\'myedit\').target = \'basefrm\'; document.getElementById(\'myedit\').fnc.value=\'\';document.getElementById(\'myedit\').cl.value=\'d3_cfg_extsearch_main\';document.getElementById(\'myedit\').submit();" value="erweiterte Suche">',
    'SHOP_CONFIG_SEARCHUSEAND'                        => 'Wenn mehrere Suchbegriffe eingegeben werden, müssen alle Suchbegriffe in einem Suchergebnis vorkommen (AND). (Wenn die Option nicht aktiv ist, muss nur ein Suchbegriff vorkommen (OR).)',
    'D3_EXTSEARCH_MAIN_PUTINLEAVEOUT'                 => 'Auslassungen oder Einfügungen erlauben',
    'D3_EXTSEARCH_MAIN_PUTINLEAVEOUT_DESC'            => 'Setzen Sie diese Option, können die zu findenden Artikel auch weniger (ausgelassene) oder mehr (eingeschobene) Buchstaben als Ihr Suchbegriff haben. Bei schwierigen Suchbegriffen kann sich die Aktivierung möglicherweise lohnen. Haben Sie jedoch verständliche Artikeltitel, empfehlen wir, dies vorerst nicht zu aktivieren. Beispiel: Die Suche nach "Lampeschirm" findet so auch "Lampenschirm".',
    'D3_EXTSEARCH_MAIN_MULIPLEWORDS'                  => 'Verwendung mehrerer Suchworte',
    'D3_EXTSEARCH_MAIN_MULIPLEWORDS_DESC'             => 'Legen Sie hier fest, wie das Modul mit mehreren Suchbegriffen umgehen soll. So können Sie festlegen, ob mit dem kompletten, zusammenhängenden Begriff gesucht werden soll. Dann muss der Suchbegriff zwingend in einem Feld vorkommen. Stellen Sie ein, dass jeder Suchbegriff separat verwendet wird, können die Suchbegriffe über die Artikelfelder verstreut sein. Diese Einstellung empfehlen wir als Standard. Alternativ bieten Sie Ihren Kunden die Verwendung von Suchsyntax an. Dies kann für technikorientierte Shops besonders sinnvoll sein.<br><br>Für die Syntax gibt es folgende Fälle:<br><br><ul><li>In Anführungszeichen ( “ ) eingeschlossen: sucht oder vermeidet die komplette Wortgruppe, ansonsten wird jedes Wort einzeln verwendet, Apostrophe werden derzeit nicht unterstützt</li><li>Vorgestelltes Minus (-): Wort oder Wortgruppe darf in Treffern nicht vorkommen</li><li>Vorgestelltes Plus (+) (optional): Wort oder Wortgruppe muss in Treffern enthalten sein</li><li>Ohne Vorzeichen wird Plus angenommen</li><li>Vorzeichen und Einschluss in Anführungszeichen können kombiniert werden</li></ul><br>Mögliche Anwendungen:<br><ul><li>eins</li><li>"eins zwei"</li><li>+eins</li><li>+"eins zwei"</li><li>–drei</li><li>-"drei vier"</li></ul>',
    'D3_EXTSEARCH_MAIN_MULIPLEWORDS_SINGLE'           => 'jedes Wort wird separat gesucht',
    'D3_EXTSEARCH_MAIN_MULIPLEWORDS_WHOLE'            => 'wird nur als zusammenhängender Begriff gesucht',
    'D3_EXTSEARCH_MAIN_MULIPLEWORDS_SYNTAX'           => 'vom Nutzer über Suchsyntax steuerbar',
    'D3_EXTSEARCH_MAIN_SORTING'                       => 'Artikelsortierung',
    'D3_EXTSEARCH_MAIN_ORDERBYPRIORITY'               => 'Treffer nach Relevanz sortieren',
    'D3_EXTSEARCH_MAIN_ORDERBYPRIORITY_DESC'          => 'Die Relevanz definiert, wie gut ein gefundener Artikel zum Suchbegriff passt. (Daher ist die Relevanzsortierung auch nur in der Suche verfügbar. In Kategorien steht diese nicht zur Verfügung.) Kommt der Suchbegriff am Artikel vor, soll dieser natürlich in den Treffern gezeigt werden. Jedoch sind die Treffer, bei denen der Suchbegriff im Titel erscheint, sicher für Ihren Kunden sinnvoller, als wenn das gesuchte Wort irgendwo in der späteren Beschreibung auftaucht. Bei der Definition der zu verwendenden Suchfelder können Sie angeben, wie hoch der Treffer für jedes einzelne Suchfeld bewertet wird. Weitere Informationen hierzu finden Sie im Modulhandbuch im Kapitel "Relevanz und Wichtigkeiten".<br><br>Aktivieren Sie die Option "Treffer nach Relevanz sortieren", wenn die Suche die Reihenfolge der Artikel nach dieser Logik ändern darf. Zu den schon vorhandenen Sortiermöglichkeiten wird automatisch die Relevanzsortierung hinzugefügt.<br><br>Hat der Kunde keine eigene Treffersortierung gewählt, werden die Suchtreffer dann nach Ihrer eingestellten Relevanz sortiert. Die Relevanz legen Sie an den für die Suche definierten Datenbankfeldern fest. Die Summe der Relevanz der Felder, die den Suchbegriff enthalten, wird dann als Sortierkriterium verwendet. In Verbindung mit der Wichtigkeit der Artikel (separat zu aktivieren) kann sich die Relevanz vervielfachen. Die Sortierung Ihrer Artikel können Sie in der "Ergebnis-Feld-Analyse" nachvollziehen.',
    'D3_EXTSEARCH_MAIN_ORDERBYPUSH'                   => 'Treffer nach Wichtigkeit sortieren',
    'D3_EXTSEARCH_MAIN_ORDERBYPUSH_DESC'              => 'Sicher unterscheiden Sie in Ihrem Artikelsortiment nach Haupartikeln, Nebenartikeln und sonstigem Zubehör. Auch diese Einstufung können Sie in den Suchergebnissen berücksichtigen lassen. So werden bei Aktivierung dieser Einstellung Ihren Kunden die Hauptartikel eher gezeigt, weniger wichtige Produkte tauchen in den Treffern erst später auf.<br><br>Wie wichtig ein Artikel im Sortiment ist, legen Sie am Artikel selbst fest. Im Adminbereich des Shops finden Sie die Einstellung unter "Artikel verwalten -> Artikel -> Erweitert -> Wichtigkeit des Artikels im Sortiment". Über externe Importe oder Warenwirtschaftsanbindungen können Sie die Einstellung über das Feld "d3push" mit den Werten 1 (normal) bis 3 (besonders wichtig) befüllen.',
    'D3_EXTSEARCH_MAIN_ORDERBYALTERNATIVE'            => 'alternative Sortierung bei identischem Relevanzsortierwert',
    'D3_EXTSEARCH_MAIN_ORDERBYALTERNATIVE_DESC'       => 'Die Sortierreihenfolge wird auf Basis der hier gesetzten Einstellungen für jeden Artikel berechnet. Haben mehrere Artikel einen identischen Sortierwert, können diese untereinander nach einem weiteren Kriterium sortiert werden. Als Angabe ist hier der Name eines Feldes der Artikel-Tabelle zugelassen (ohne Sprach-Zusatz). Mit asc und desc stellen Sie ein, ob auf- oder absteigend sortiert wird.',
    'D3_EXTSEARCH_MAIN_VARIANTSETTINGS'               => 'Variantensuche',
    'D3_EXTSEARCH_MAIN_VARIANTSEARCH'                 => 'Shop sucht auch nach Variantenartikeln',
    'D3_EXTSEARCH_MAIN_VARIANTUSAGE'                  => 'wird eine Artikelvariante gefunden, wird ...',
    'D3_EXTSEARCH_MAIN_VARIANTUSAGE_SHOWPARENT'       => '... deren Elternartikel in der Trefferliste gezeigt',
    'D3_EXTSEARCH_MAIN_VARIANTUSAGE_SHOWVARIANT'      => '... die Variante selbst in der Trefferliste gezeigt',
    'D3_EXTSEARCH_MAIN_SHOWVARIANTSWITHOUTFILTERS'    => 'zeige Varianten auch ohne Filterung',
    'D3_EXTSEARCH_MAIN_SHOWVARIANTSWITHOUTFILTERS_DESC'=> 'Die Anzeige von Variantenartikeln ist meist nur dann sinnvoll, wenn speziell danach gefiltert wird. Sollen die Variantenartikel auch ohne Filterung gezeigt werden, aktivieren Sie diese Option. Die Artikellisten können dann umfangreicher werden. Diese Option wirkt auf Suchergebnisse und (sofern aktiv) auch auf Kategorien.',
    'D3_EXTSEARCH_MAIN_VARIANTINALIST'                => 'spezielle Variantenbehandlung wird auch in Artikellisten verwendet',
    'D3_EXTSEARCH_MAIN_VARIANTCHECKPARENTACTIVE'      => 'Aktivstatus des Elternartikel ausdrücklich prüfen',
    'D3_EXTSEARCH_MAIN_VARIANTUSAGE_DESC'             => '<p>Stellen Sie hier ein, ob bei einer gefundenen Variante diese Variante selbst oder deren Elternartikel in der Trefferliste gezeigt werden soll. Beachten Sie bei der Anzeige des Elternartikels anstatt der Variante bitte darauf, dass die Elternartikel auch aktiv und auswählbar sein müssen. Eine zusätzliche Prüfung darauf findet nur statt, wenn diese ausdrücklich konfiguriert wurde.</p><p>Bei der Anzeige der Elternartikel wird an den verwendbaren Filtern weiterhin die Anzahl der dazu passenden Varianten gezeigt, da diese weiterhin Basis für die Filter sind. Diese Abweichung kann den Shopbesucher verwirren. Deaktivieren Sie in diesem Fall die Darstellung der Anzahl zum Filter gefundener Artikel.</p>',
    'D3_EXTSEARCH_MAIN_VARIANTINALIST_DESC'           => 'Sollen auch Kategorie-, Lieferanten- und Herstellerseiten diese Varianteneinstellungen verwenden, aktivieren Sie diese Option. Damit ändern Sie die grundlegende Listengenerierung, wenn Sie Artikelvarianten verwenden. Die Variantenartikel müssen dann jedoch auch ausdrücklich den Kategorien, Herstellern oder Lieferanten zugeordnet sein.',
    'D3_EXTSEARCH_MAIN_VARIANTSEARCH_DESC'            => 'Statt wie üblich nur nach regulären Artikeln zu suchen, findet der Shop mit dieser Option auch einzelne Variantenartikel. Tragen Sie bitte zusätzlich in der Feldliste des Moduls und im Shop unter \'Stammdaten -> Grundeinstellungen -> Einstell. -> Suche\' den Feldname \'oxvarselect\' ein und generieren Sie den Suchindex neu.',
    'D3_EXTSEARCH_MAIN_VARIANTCHECKPARENTACTIVE_DESC' => 'Aus Performancegründen gehen wir pauschal davon aus, dass aktive und kaufbare Variantenartikel auch einen aktiven Elternartikel haben. Kann dies in Ihrem Shop abweichen, setzen Sie diese Option. Dann wird für jeden Variantenartikel geprüft, ob dessen Elternartikel auch verfügbar ist.<br><br>Beachten Sie, dass diese Option viel Leistung benötigt. Stellen Sie besser alternativ über die Datenbank sicher, dass Varianten von inaktiven Elternartikeln ebenfalls nicht aktiv sind.',
    'D3_EXTSEARCH_MAIN_OWNFORMFIELDS'                 => 'individuelle Filterfelder nutzen',
    'D3_EXTSEARCH_MAIN_OWNFORMFIELDS_DESC'            => 'Durch diese Option können Sie in einer einfachen Art dem Kunden weitere Felder zur Einschränkung der Treffer anbieten. Dieser Funktion haben wir ein eigenes Kapitel im Modulhandbuch gewidmet (siehe dazu "Technische Erläuterungen").',
    'D3_EXTSEARCH_MAIN_LOGSETTINGS'                   => 'Statistik',
    'D3_EXTSEARCH_MAIN_LOGHITLESS'                    => 'ergebnislose Suchaktionen für Statistik mitschreiben',
    'D3_EXTSEARCH_MAIN_LOGHITLESS_DESC'               => 'Startet der Kunde eine Suchanfrage, die keine Ergnisse liefern kann, werden die Suchbegriffe für Sie aufgezeichnet. Sie finden die Aufstellung dann unter der Registerkarte \'Logging\' und können Ihre Produkte ggf. auch für diese Begriffe optimieren.',
    'D3_EXTSEARCH_MAIN_LOGFORSEARCH'                  => 'alle Suchanfragen für Statistik mitschreiben (auch ohne shopweites Logging)',
    'D3_EXTSEARCH_MAIN_LOGFORSEARCH_DESC'             => 'Schreibt alle Suchanfragen für die modulinterne Statistik mit. Diese Einstellung kann auch gesetzt werden, ohne daß andere Shopfunktionen mitgeschrieben werden. Ist das shopweite Logging aktiviert, werden die Suchanfragen generell mitgeschrieben.',
    'D3_EXTSEARCH_MAIN_PHONETICS'                     => 'phonetische Suche (nach Klang)',
    'D3_EXTSEARCH_MAIN_PHONETICS_DESC'                => 'Hierbei handelt es sich um die fehlertolerante Suche, die klangähnliche Treffer findet, auch wenn diese anders geschrieben wurden. Damit wird die Suche für Schreibfehler tolerant.',
    'D3_EXTSEARCH_MAIN_SIMILARSEARCH'                 => 'wenn kein Suchergebnis, Shop sucht nach ähnlichen klingenden Artikel (Bsp.: Suche: <i>Pflan<b>s</b>e</i>, Treffer: <i>Pflan<b>z</b>e</i>)',
    'D3_EXTSEARCH_MAIN_SIMILARSEARCH_DESC'            => 'Hier aktivieren (oder deaktivieren) Sie die phonetische Suche. Damit fangen Sie zum Beispiel Schreibfehler in der Suchabfrage ab und der Kunde findet seine gewünschten Artikel trotzdem mit großer Wahrscheinlichkeit. Ist gleichzeitig die Suche nach Sinn (Semantic) aktiviert, wird zuerst versucht, sinngleiche Treffer zu finden. Schlägt dies fehl, werden Treffer über die Klangsuche ermittelt.',
    'D3_EXTSEARCH_MAIN_PHONETICLANG'                  => 'für die Ähnlichkeitssuche verwendete Sprache',
    'D3_EXTSEARCH_MAIN_PHONETICLANG_DESC'             => 'Da sich die verschiedenen menschlichen Sprachen in Ihrer Aussprache und in der Wort- bzw. Buchstabenzusammensetzung unterscheiden, ist für ein optimales Suchergebnis ein sprachenabhängiges Verfahren zur Indexgenerierung nötig. Sollten Sie in Ihrem Shop hauptsächlich eine andere Sprache als die nebenstehend Angezeigte verwenden, fragen Sie bei uns nach, ob auch ein Modul für Ihre Sprache zur Verfügung steht.<br><br>Im Standard liefern wir für die deutsche Sprache 2 Optionen mit. Wir empfehlen die Verwendung der Option "deutsch mit Vokalen", da hierin die Treffergenauigkeit deutlich höher ist.',
    'D3_EXTSEARCH_MAIN_SIMILAREXTLIST_1'              => 'Shop zeigt zusätzlich ähnliche klingende Treffer, wenn reguläre Suche maximal',
    'D3_EXTSEARCH_MAIN_SIMILAREXTLIST_2'              => 'Treffer',
    'D3_EXTSEARCH_MAIN_SIMILAREXTLIST_DESC'           => 'Wenn die Suche nur wenige Treffer erzielt, kann man dem Kunden so auch ähnliche Artikel liefern. Diese ähnlichen Artikel werden in der Ergebnisliste nach den tatsächlichen Treffern gezeigt. Der Kunde wird mit einer Meldung über die aufgefüllte Liste informiert. Setzen Sie diese Einstellung bitte jedoch mit Bedacht ein, da die zusätzlichen Treffer die Kunden verwirren könnten.',
    'D3_EXTSEARCH_MAIN_MINPHONLENGTH'                 => 'Treffergenauigkeit bei kurzen Suchworten',
    'D3_EXTSEARCH_MAIN_MINPHONLENGTH_LESS'            => 'weniger Genauigkeit',
    'D3_EXTSEARCH_MAIN_MINPHONLENGTH_REG'             => 'normale Genauigkeit',
    'D3_EXTSEARCH_MAIN_MINPHONLENGTH_MORE'            => 'mehr Genauigkeit',
    'D3_EXTSEARCH_MAIN_MINPHONLENGTH_DESC'            => 'Die indizierte Ähnlichkeitssuche kann erst ab einer bestimmten Wortlänge sinnvoll und effizient arbeiten. Daher bringt die phonetische Suche zwei verschiedene Abarbeitungswege mit: Die Suche über den vorher generierten Index und die zur Laufzeit definierte Ähnlichkeit.<br><br>Beide Methoden haben jeweils Vor- und Nachteile:<br><ul><li>Die indexbasierte Suche ist sehr treffgenau und schnell. Jedoch erfordert diese eine Mindestlänge an relevanten Zeichen. Sind die Suchbegriffe kürzer, lässt die Genauigkeit rapide nach und bei zu kurzen Suchworten würde sogar das ganze Shopsortiment gezeigt.</li><li>Bei kurzen Suchworten wird nun automatisch die Ähnlichkeit zur Laufzeit berechnet. Deren Stärken liegt in der Erkennung kurzer Suchworte. Zwar ist sie nicht ganz so genau, wie die Indexsuche. Da die Worte aber kurz sind, spielt dies hier keine so wichtige Rolle. Zu beachten ist jedoch, dass diese Art der Suche etwas mehr Rechenleistung benötigt und daher langsamer ist.</li></ul><br><br>Ab wann wird nun von einer Technik zur anderen umgeschaltet? Wird eine Suche gestartet, prüft das Modul an Hand der Wortlänge, welche Technik am sinnvollsten ist. Sie können nun über den Schalter `Treffergenauigkeit bei kurzen Suchworten` definieren, wie schnell auf die indexbasierte Suche umgeschaltet wird. Ziel sollte sein, schnellstmöglich auf den Index zu wechseln, ohne jedoch zu viele Treffer zu generieren. Die Einstellmöglichkeiten erstrecken sich auf (phonetische relevante) Wortlängen zwischen 3 und 5 Zeichen. Führen Sie mit den für Ihren Shop typischen Suchbegriffen einfach ein paar Versuche durch und variieren Sie die Einstellungen entsprechend. Bei Unklarheiten kontaktieren Sie uns bitte einfach.',
    'D3_EXTSEARCH_MAIN_SEMANTICS'                     => 'semantische Suche (nach Sinn)',
    'D3_EXTSEARCH_MAIN_SEMANTICS_DESC'                => 'Semantische Begriffe, sind Worte, die einen ähnlichen Sinn wie das Suchwort haben. Suchen Sie nach "Becher", werden auch Artikel gefunden, die als Inhalt "Tasse" haben.<br><br>Für die Verwendung der semantischen Suche ist ein passendes Lexikon notwendig. Dieses können Sie selbst nach eigenen Anforderungen im Synonym-Editor befüllen (empfohlen). Hinweise zu dessen Bedienung finden Sie im Handbuch.<br><br>Alternativ stellen wir auch eine umfangreiche Standarddatenbank zur Verfügung. Den Link dazu finden Sie in der Installationsanleitung des Moduls.',
    'D3_EXTSEARCH_MAIN_SEMANTICSEARCH'                => 'Shop sucht nach Artikeln mit ähnlichem Sinn (Bsp.: Suche: <i>Gew&auml;chs</i>, Treffer: <i>Pflanze</i>)',
    'D3_EXTSEARCH_MAIN_SEMANTICSEARCH_MISSING'        => 'Shop sucht nach Artikeln mit ähnlichem Sinn (Bsp.: Suche: <i>Gew&auml;chs</i>, Treffer: <i>Pflanze</i>)<br><b>Lexikon ist nicht installiert!</b>',
    'D3_EXTSEARCH_MAIN_SEMANTICSEARCH_DESC'           => 'Setzen Sie diesen Haken, um eine sinngleiche Suche im Shop zu ermöglichen. Durch z.B. regionale Unterschiede kann es vorkommen, daß Ihre Kunden einen Artikel zwar anders bezeichnen, jedoch Ihr Produkt meinen. Gibt der Kunde nun seinen Wunsch ein, bekommt er gegebenenfalls die Begriffe gezeigt, die in Ihrem Shop das gewünschte Produkt besser beschreiben.',
    'D3_EXTSEARCH_MAIN_SEMANTICUSEPHONETIC'           => 'enthält das Suchwort Schreibfehler, wird zusätzlich zur Sinnsuche versucht, die richtige Schreibweise zu ermitteln; erzeugt jedoch ggf. stark abweichende Treffer; erfordert aktivierte phonetische Suche',
    'D3_EXTSEARCH_MAIN_SEMANTICUSEPHONETIC_DESC'      => 'Diese Einstellung erlaubt zur sinngleichen Suche auch die phonetische Suche, wenn keine sinngleichen Worte gefunden werden. Da hier jedoch der gewünschte Sinn nicht eindeutig klar ist, werden unter Umständen stark abweichende Treffer gezeigt. Wir empfehlen die Verwendung dieser Einstellung nur eingeschränkt.<br>Für die Verwendung dieser Einstellung, lassen Sie zuvor den Index für die sinngleiche Suche erstellen: "D3 Module -> erweiterte Suche -> Einstellungen -> Grundeinstellungen -> Suchindex -> Lexikon für die sinngleiche Suche neu indizieren".',
    'D3_EXTSEARCH_MAIN_SAVE'                          => 'Speichern',
    'D3_EXTSEARCH_MAIN_INDEX'                         => 'Suchindex',
    'D3_EXTSEARCH_MAIN_INDEX_DESC'                    => 'Dass die Ähnlichkeitssuche arbeiten kann, ist die Generierung eines Suchindex nötig. Dazu werden die definierten Suchfelder mit einem sprachabhängigen Schlüssel für die Suche vorbereitet. So verläuft die eigentliche Suchabfrage nicht bedeutend langsamer als eine reguläre Artikelsuche. (Auf die Ausführungszeit anderer Einstellungen hat der Suchindex jedoch keine Auswirkungen.) Der Index wird automatisch aktualisiert, wenn Sie Ihre Artikel über den Adminbereich des Shops einpflegen oder das von Ihnen genutzte Importtool das Shop-Framework verwendet (Auskunft dazu kann Ihnen Ihr Oxid-Partner erteilen). Verwalten Sie Ihre Artikel über andere Wege, generieren Sie den Suchindex nach jedem Artikel-Update neu. Die Generierung benötigt durchaus etwas Rechenleistung, ist jedoch meist in wenigen Sekunden abgeschlossen.<br><br>Die Neugenerierung ist ebenfalls nötig, wenn Änderungen an den zu verwendenden Feldnamen vorgenommen werden.',
    'D3_EXTSEARCH_MAIN_INDEXARTCNT'                   => 'Artikel pro Durchlauf für Index aufarbeiten',
    'D3_EXTSEARCH_MAIN_INDEXARTCNT_DESC'              => 'Der Webserver bricht Scripte nach einer gewissen Laufzeit aus Sicherheitsgründen ab. Um die Generierung des Suchindexes dennoch fertigstellen zu können, verarbeitet dieses Script nur eine gewisse Anzahl Artikel und startet sich dann neu. Legen Sie hier fest, wie viele Artikel in einem Durchlauf bearbeitet werden sollen. Bricht die Generierung mit einem Fehler ab, reduzieren Sie die Zahl. Je niedriger die Anzahl, um so länger benötigt jedoch das Script.',
    'D3_EXTSEARCH_MAIN_INDEXERR'                      => 'Der benötigte Index für die fehlertolerante Suche ist lückenhaft. Klicken Sie hier, um die Liste neu zu generieren:',
    'D3_EXTSEARCH_MAIN_INDEXNOERR'                    => 'Der benötigte Index für die fehlertolerante Suche scheint vollständig. Im Moment ist keine Aktion nötig, wenn Sie die Sprache nicht geändert haben oder Artikel importiert haben.<br>Der Index muß für jede Sprache des Shop separat erstellt werden.',
    'D3_EXTSEARCH_MAIN_GENINDEXCMPL'                  => 'phonetischen Suchindex aktualisieren',
    'D3_EXTSEARCH_MAIN_GENINDEXCMPL_DESC'             => 'Generiert für veränderte oder neue Artikel den Suchindex neu.',
    'D3_EXTSEARCH_MAIN_GENSEMANTICINDEX'              => 'Lexikon für sinngleiche Suche neu indizieren',
    'D3_EXTSEARCH_MAIN_GENSEMANTICINDEX_DESC'         => 'Für die Verbindung von sinngleicher Suche und phonetischer Suche benötigt auch das Lexikon den phonetischen Index. Mit dieser Schaltfläche starten Sie die Neuindizierung des Lexikons. Im Normalfall ist dies jedoch nicht notwendig.',
    'D3_EXTSEARCH_MAIN_SHOW_POPUP'                    => 'PopUp während des Suchvorgangs zeigen',
    'D3_EXTSEARCH_MAIN_SHOW_POPUP_DESC'               => 'Um ungeduldige Kunden während des Suchvorgangs zu informieren, können Sie ein Informations-PopUp anzeigen lassen. Dieses können Sie Ihrem Shoplayout entsprechend auch inhaltlich und grafisch gestalten.',
    'D3_EXTSEARCH_MAIN_CATEGORY'                      => 'Suche in Kategoriennamen',
    'D3_EXTSEARCH_MAIN_CATEGORY_SEARCH'               => 'auch in Kategorienamen suchen und enthaltene Artikel finden',
    'D3_EXTSEARCH_MAIN_CATEGORY_SEARCH_DESC'          => 'Die Standardsuche findet nur Treffer in den angelegten Artikeln. Möglicherweise sucht Ihr Kunden aber einen Begriff, mit dem Sie eine ganze Kategorie benannt haben. Haben Sie diesen Haken gesetzt, wird auch in den Kategorienamen nach den Suchbegriffen gesucht.',
    'D3_EXTSEARCH_MAIN_CATEGORY_ANDOR_DESC'           => 'Diese Einstellung wird nur für die Suche in Kategorienamen verwendet. Für die Artikelsuche gibt es eine eigene Einstellung.',
    'D3_EXTSEARCH_MAIN_CATEGORY_ARTHANDLING'          => 'Kategorie selbst oder deren Artikel anzeigen',
    'D3_EXTSEARCH_MAIN_CATEGORY_ARTINCAT'             => 'Artikel aus Kategorie anzeigen',
    'D3_EXTSEARCH_MAIN_CATEGORY_CATINLIST'            => 'Kategorie zur Auswahl anzeigen',
    'D3_EXTSEARCH_MAIN_CATEGORY_PRIORITY'             => 'Relevanz bei Kategorietreffern',
    'D3_EXTSEARCH_MAIN_CATEGORY_PRIORITY_DESC'        => 'Artikeltreffer erhalten ihre Relevanz auf Grund der an den Feldern eingestellten Relevanzzahlen. Treffer, die auf Grund ihrer Kategoriezugehörigkeit gefunden werden, können ihre Relevanz so nicht enthalten. Definieren Sie hier, welchen Platz in der Artikelliste diese Treffer erhalten sollen.',
    'D3_EXTSEARCH_MAIN_MANUFACTURER'                  => 'Suche in Marken- und Lieferantennamen',
    'D3_EXTSEARCH_MAIN_MANUFACTURER_SEARCH'           => 'auch in Marken- und Lieferantennamen suchen und enthaltene Artikel finden',
    'D3_EXTSEARCH_MAIN_MANUFACTURER_SEARCH_DESC'      => 'Die Standardsuche findet nur Treffer in den angelegten Artikeln. Möglicherweise sucht Ihr Kunden aber einen Begriff, mit dem Sie eine Marke oder einen Lieferanten benannt haben. Haben Sie diesen Haken gesetzt, wird auch in den Marken- bzw. Lieferantennamen nach den Suchbegriffen gesucht.',
    'D3_EXTSEARCH_MAIN_MANUFACTURER_ANDOR_DESC'       => 'Diese Einstellung wird nur für die Suche in Marken- und Lieferantennamen verwendet. Für die Artikelsuche gibt es eine eigene Einstellung.',
    'D3_EXTSEARCH_MAIN_MANUFACTURER_PRIORITY'         => 'Relevanz bei Marken-/Lieferantentreffern',
    'D3_EXTSEARCH_MAIN_MANUFACTURER_PRIORITY_DESC'    => 'Artikeltreffer erhalten ihre Relevanz auf Grund der an den Feldern eingestellten Relevanzzahlen. Treffer, die auf Grund ihrer Marken- bzw. Lieferantenzugehörigkeit gefunden werden, können ihre Relevanz so nicht enthalten. Definieren Sie hier, welchen Platz in der Artikelliste diese Treffer erhalten sollen.',
    'D3_EXTSEARCH_MAIN_ADMINPANEL'                    => 'Adminbereich',
    'D3_EXTSEARCH_MAIN_ADMINSHOWVARIANTS'             => 'zeige nach Suche auch Varianten in Artikelliste',
    'D3_EXTSEARCH_MAIN_ADMINSHOWVARIANTS_DESC'        => 'Möchten Sie im Adminbereich Ihre Artikel bearbeiten ("Artikel verwalten -> Artikel"), können Sie dort nach vorhandenen Artikeln suchen. Die Standardsuche berücksichtigt jedoch keine Variantenartikel. Möchten Sie diese dort ebenfalls suchbar machen, aktivieren Sie diese Option.',
    'D3_EXTSEARCH_MAIN_USEARTNUMSEARCH'               => 'speziell nach Artikelnummern suchen',
    'D3_EXTSEARCH_MAIN_USEARTNUMSEARCH_DESC'          => 'Ist diese Option markiert, wird vor dem eigentlichen Suchdurchlauf ausdrücklich nach einer zum Suchbegriff passenden Artikelnummer gesucht. Gefundene Artikel werden dargestellt und die Suche beendet. Dies kann bei häufiger Verwendung zu schnelleren Suchergebnissen führen.',
    'D3_EXTSEARCH_MAIN_DONTUSEOWNDBVIEWS'             => 'Datenbankabfragen verwenden <b>nicht</b> die moduleigenen View-Tabellen',
    'D3_EXTSEARCH_MAIN_DONTUSEOWNDBVIEWS_DESC'        => 'Aus Performance-Gründen verwendet die Suche nicht die shopeigenen View-Tabellen, sondern bringt optimierte Versionen dessen mit. Je nach Größe des Datenbank kann deren Verwendung die Geschwindigkeit von Datenbankabfragen bis um den Faktor 100 beschleunigen. Sollen die spezialisierten View-Tabellen <b>nicht</b> verwendet werden, setzen Sie diesen Haken. Dann werden die Abfragen über die shopeigenen View-Tabellen geleitet.<br>Beachten Sie, dass bei deaktivierung dieser Option die View-Tabellen noch einmal aktualisiert werden müssen.',
    'D3_EXTSEARCH_MAIN_GENERATOR_INCONSISTENTTABLE'   => 'Die Artikel-Tabelle der Datenbank ist mit der Langtext-Tabelle nicht konsistent. Bitte bereinigen Sie dies vor der Ausführung des Generators. <br><br>Weitere Informationen finden Sie in der FAQ unter <a href="%1$s" target="_new">%1$s</a>.',
    'D3_EXTSEARCH_MAIN_GENERATOR_INCONSISTENTTABLE_NOLINK' => 'Die Artikel-Tabelle der Datenbank ist mit der Langtext-Tabelle nicht konsistent. Bitte bereinigen Sie dies vor der Ausführung des Generators.',
    'D3_EXTSEARCH_MAIN_GENERATOR_FINISHED'            => 'Beendet.',
    'D3_EXTSEARCH_MAIN_GENERATOR_NOTE'                => 'Hinweis',
    'D3_EXTSEARCH_MAIN_GENERATOR_PROCESSED'           => '%1$s Artikelsprachen (ca. %2$s Artikel) bearbeitet<br>Generierung abgeschlossen!',
    'D3_EXTSEARCH_MAIN_GENERATOR_TERMPROCESSED'       => '%1$s Wort/Wörter bearbeitet<br>Generierung abgeschlossen!',
    'D3_EXTSEARCH_MAIN_GENERATOR_PROCESSING'          => 'Bearbeite %1$s&#37;',
    'D3_EXTSEARCH_MAIN_GENERATOR_PROCESSING1'         => 'Bearbeite %1$s / %2$s Artikelsprachen (ca. %3$s Artikel)',
    'D3_EXTSEARCH_MAIN_GENERATOR_PROCESSING3'         => 'Bearbeite %1$s / %2$s Begriffe',
    'D3_EXTSEARCH_MAIN_GENERATOR_PROCESSING2'         => '%1$s&#37; bearbeitet',
    'D3_EXTSEARCH_MAIN_GENERATOR_WAIT'                => 'Bitte warten...',
    'D3_EXTSEARCH_MAIN_GENERATOR_CLOSEWND'            => 'Fenster schließen',
    'D3_EXTSEARCH_MAIN_GENERATOR_EXCEPTION'           => 'Generierungsfehler, der Index kann leider nicht erstellt werden.',

    'D3_EXTSEARCH_NAVI_MAINSETTINGS'                  => 'allgemeine Einstellungen',
    'D3_EXTSEARCH_NAVI_DISPTYPE'                      => 'Art der Filter-Anzeige',
    'D3_EXTSEARCH_NAVI_DISPTYPE_LINKLIST'             => 'als Linkliste',
    'D3_EXTSEARCH_NAVI_DISPTYPE_DROPDOWN'             => 'als DropDown-Liste',
    'D3_EXTSEARCH_NAVI_DISPTYPE_DESC'                 => 'Stellen Sie hier die Anzeigeform der Kategorie-, Lieferanten- und Markenlisten ein. Die DropDown-Listen sparen in der Anzeige Platz, können jedoch bei vielen Einträgen unübersichtlich lang werden. Alternativ empfehlen sich Linklisten, die in ihrer Länge auch eingeschränkt werden können.<br>Beide Anzeigeformen lassen sich im Template nachbearbeiten.',
    'D3_EXTSEARCH_NAVI_EMPTYSEARCH'                   => 'Suche ohne Suchbegriff zulassen',
    'D3_EXTSEARCH_NAVI_EMPTYSEARCH_DESC'              => 'Es kann durchaus sinnvoll sein, auch Suchvorgänge ohne einen Suchbegriff zuzulassen. Möglicherweise werden die dann erhaltenen Treffer erst durch eine zusätzliche Einstellung gefiltert oder Sie möchten ein umfangreiches Suchformular aufbauen, welches möglicherweise kein frei definierbares Suchwort enthält.',
    'D3_EXTSEARCH_NAVI_CATFILTER'                     => 'Kategoriefilter',
    'D3_EXTSEARCH_NAVI_CATLIST'                       => 'zeige Kategorienliste',
    'D3_EXTSEARCH_NAVI_CATLIST_DESC'                  => 'Setzen Sie den Haken, um Ihrem Kunden bei einer umfangreichen Trefferliste eine Auswahl der betroffenen Kategorien anzuzeigen. Damit kann er sein Suchergebnis gezielt einschränken und verbessern. Angezeigt wird der Kategoriename und die Anzahl der darin enthaltenen Artikel der Trefferliste.',
    'D3_EXTSEARCH_NAVI_CATLIST_SORT'                  => 'sortiert nach',
    'D3_EXTSEARCH_NAVI_CATLIST_SORT_COUNT'            => 'Anzahl der enthaltenen Artikel',
    'D3_EXTSEARCH_NAVI_CATLIST_SORT_DATA'             => 'einstellbare Sortierreihenfolge',
    'D3_EXTSEARCH_NAVI_CATLIST_SORT_DESC'             => 'Legen Sie hier fest, nach welchem Kriterium die Kategorieliste sortiert sein soll. Auf die Darstellung hat dies jedoch keinen Einfluß.',
    'D3_EXTSEARCH_NAVI_CATLIST_MORE_DESC'             => 'Weitere Einstellungen zu Kategoriefiltern finden Sie direkt an den jeweiligen Kategorien im Tab für die Sucheinstellungen.',
    'D3_EXTSEARCH_NAVI_FILTER_DISPLAYTYPE'            => 'angezeigte Auswahl',
    'D3_EXTSEARCH_NAVI_FILTER_DISPLAYTYPE_COMBINED'   => 'Einfach- und Mehrfachauswahl umschaltbar',
    'D3_EXTSEARCH_NAVI_FILTER_DISPLAYTYPE_SINGLE'     => 'nur Einfachauswahl',
    'D3_EXTSEARCH_NAVI_FILTER_DISPLAYTYPE_MULTI'      => 'nur Mehrfachauswahl',
    'D3_EXTSEARCH_NAVI_FILTER_DISPLAYTYPE_DESC'       => 'Stellen Sie ein, wie die Filter dem Shopbesucher gezeigt werden sollen.<br><br>Einfachauswahl stellt ein DropDown dar, welches den einzelnen Eintrag nach Auswählen sofort absendet. Ein weiterer Eintrag aus diesem Filter ist nicht wählbar.<br><br>Mehrfachauswahl stellt alle Einträge als Checkboxen dar. Der Kunde kann alle gewünschte Einträge auswählen und sendet diese gesamt ab.',
    'D3_EXTSEARCH_NAVI_FILTER_MORE_DESC'              => 'Weitere Einstellungen zu Attributsfiltern finden Sie direkt an den jeweiligen Attributen im Tab für die Sucheinstellungen.',
    'D3_EXTSEARCH_NAVI_CATLISTMAINCATEGORIESONLY'     => 'nur Hauptkategorien der Artikel anzeigen',
    'D3_EXTSEARCH_NAVI_CATLISTMAINCATEGORIESONLY_DESC'=> 'Die Option verhindert das Auflisten zusätzlich zugeordneter Kategorien als Filter. Er werden ausschließlich die Hauptkategorien der gefundenen Artikel gezeigt.',
    'D3_EXTSEARCH_NAVI_VENDORFILTER'                  => 'Lieferantenfilter',
    'D3_EXTSEARCH_NAVI_VENDORLIST'                    => 'zeige Lieferantenliste',
    'D3_EXTSEARCH_NAVI_VENDORLIST_DESC'               => 'Ebenso wie für die Kategorien gibt es auch die Möglichkeit, die Trefferliste noch einmal nach den Lieferanten zu filtern. Dies schalten Sie hier ein. Diese Option ist nur verfügbar, wenn Sie generell die Lieferantent im Shop aktiviert haben und auch eine Suche danach erlauben. (\'Lieferantenliste laden und anzeigen\')',
    'D3_EXTSEARCH_NAVI_VENDORLIST_SORT'               => 'sortiert nach',
    'D3_EXTSEARCH_NAVI_VENDORLIST_SORT_COUNT'         => 'Anzahl der enthaltenen Artikel',
    'D3_EXTSEARCH_NAVI_VENDORLIST_SORT_ALPHA'         => 'alphabetisch',
    'D3_EXTSEARCH_NAVI_VENDORLIST_SORT_DESC'          => 'Bestimmen Sie die Anzeigereihenfolge, in der die Lieferanten aufgelistet sein sollen.',
    'D3_EXTSEARCH_NAVI_MANUFACTURERFILTER'            => 'Markenfilter',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST'              => 'zeige Markenliste',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST_DESC'         => 'Ebenso wie für die Kategorien gibt es auch die Möglichkeit, die Trefferliste noch einmal nach den Marken zu filtern. Dies schalten Sie hier ein. Diese Option ist nur verfügbar, wenn Sie generell die Marken im Shop aktiviert haben und auch eine Suche danach erlauben. (\'Markenliste laden und anzeigen\')',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST_SORT'         => 'sortiert nach',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST_SORT_COUNT'   => 'Anzahl der enthaltenen Artikel',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST_SORT_ALPHA'   => 'alphabetisch',
    'D3_EXTSEARCH_NAVI_MANUFACTURERLIST_SORT_DESC'    => 'Bestimmen Sie die Anzeigereihenfolge, in der die Marken aufgelistet sein sollen.',
    'D3_EXTSEARCH_NAVI_REDIRECTS'                     => 'Weiterleitungen',
    'D3_EXTSEARCH_NAVI_UNIQUEHIT'                     => 'bei 1 Artikeltreffer, Shop wechselt direkt zur Detailseite des Artikels',
    'D3_EXTSEARCH_NAVI_UNIQUEHIT_DESC'                => 'Hat Ihr Kunde so präzise gesucht, daß er die gewünschte Information als Einziges in der Trefferliste hat, können Sie ihm den Umweg über die Trefferliste ersparen und liefern ihm sofort die Detailseite des gefunden Artikels.',
    'D3_EXTSEARCH_NAVI_UNIQUECONTENTHIT'              => 'bei 1 CMS-/Texttreffer, Shop wechselt direkt zur CMS-Seite',
    'D3_EXTSEARCH_NAVI_UNIQUECONTENTHIT_DESC'         => 'Enthält das Suchergebniss keine Artikel, jedoch einen einzigen CMS-Text, wird direkt auf die passende CMS-Seite weitergeleitet. Der Benutzer verlässt damit die Suchfunktion des Shops, seine Sucheinstellungen sind dann nicht mehr verfügbar.',
    'D3_EXTSEARCH_NAVI_UNIQUEVENDORHIT'               => 'bei 1 Lieferantentreffer, Shop wechselt direkt zur Lieferanten-Seite des Shops',
    'D3_EXTSEARCH_NAVI_UNIQUEVENDORHIT_DESC'          => 'Enthält das Suchergebniss keine Artikel, jedoch einen einzigen Lieferant, wird direkt auf die passende Lieferanten-Seite Ihres Shops weitergeleitet. Diese Option erfordert die "Suche in Marken- und Lieferantennamen". Der Benutzer verlässt damit die Suchfunktion des Shops, seine Sucheinstellungen sind dann nicht mehr verfügbar.',
    'D3_EXTSEARCH_NAVI_UNIQUEMANUFACTURERHIT'         => 'bei 1 Markentreffer, Shop wechselt direkt zur Marken-Seite des Shops',
    'D3_EXTSEARCH_NAVI_UNIQUEMANUFACTURERHIT_DESC'    => 'Enthält das Suchergebniss keine Artikel, jedoch eine einzige Marke, wird direkt auf die passende Marken-Seite Ihres Shops weitergeleitet. Diese Option erfordert die "Suche in Marken- und Lieferantennamen". Der Benutzer verlässt damit die Suchfunktion des Shops, seine Sucheinstellungen sind dann nicht mehr verfügbar.',
    'D3_EXTSEARCH_NAVI_CONTENTS'                      => 'Informationsseiten / CMS-Texte',
    'D3_EXTSEARCH_NAVI_CONTENTLIST'                   => 'suche in CMS-Texten',
    'D3_EXTSEARCH_NAVI_CONTENTLIST_DESC'              => 'Aktivieren Sie diese Option, wenn Sie Ihren Kunden auch Informationstexte suchbar machen wollen. Beachten Sie bitte, dass Sie jeden einzelnen CMS-Text für die Suche aktivieren müssen. Damit wird vermieden, dass z.B. Infotexte, die für E-Mails bestimmt sind, von der Suche berücksichtigt werden. Das Aktivieren nehmen Sie direkt am Text vor: <br><br>"Kundeninformationen -> CMS-Seiten -> Stamm -> kann gesucht werden"',
    'D3_EXTSEARCH_NAVI_ATTRIBUTEFILTER'               => 'Attributfilter',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST'                 => 'zeige Attributsliste',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_DESC'            => 'Aktivieren Sie diese Option, wenn auch nach Attributen gefiltert werden soll.<br>Jedes Attribut kann in dessen Einstellungen ("Artikel verwalten > Attribute") von der Filterung ausgeschlossen werden, wenn dies nicht sinnvoll ist.',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_ASSIGNMENT'      => 'verwende Attributsaktivierung pro Kategorie, Hersteller und Lieferant',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_ASSIGNMENT_DESC' => 'Sollen an diesen Elementen nicht alle verfügbaren Attribute zur Filterung angeboten werden, können Sie <br><ul><li>jedes Attribut generell von der Filterung ausschließen oder</li><li>alternativ auch definieren, welches Attribut bei welchem dieser Elemente verwendet werden darf</li></ul> Möchten Sie die individuelle Zuordnung nutzen, aktivieren Sie bitte diese Option. Aus Performancegründen ist diese nicht pauschal aktiviert.<br><br>Die Zuordnungen setzen Sie bitte an der jeweiligen Kategorie, Hersteller, Lieferant oder korrespondierend am jeweiligen Attribut.',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_ASSIGNMENT_NA'   => 'Zuordnungsverwendung ist nicht aktiviert.',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_ASSIGNMENT_NA_DESC'  => 'Die Verwendung der Zuordnungen muss aus Performcegründen in den Einstellungen des Moduls aktiviert werden (D3 Module -> Erweiterte Suche -> Einstellungen -> Filter + Anzeige -> Attributfilter -> verwende Attributsaktivierung pro Kategorie). Bis dahin können Sie die Zuordnung setzen. Verwendet werden diese jedoch erst nach Aktivierung.',
    'D3_EXTSEARCH_NAVI_ATTRIBUTES_COMBINE'            => 'mehrfache Attributselektionen werden mit "ODER" verknüpft',
    'D3_EXTSEARCH_NAVI_ATTRIBUTES_COMBINE_DESC'       => 'Aktivieren Sie diese Option, wenn beispielsweise bei gewählter Farbe und gewähltem Material auch Artikel gezeigt werden sollen, die nur eine der Eigenschaften haben. Ohne diese Option werden nur Artikel gezeigt, die beide Eigenschaften gleichzeitig besitzen.',
    'D3_EXTSEARCH_NAVI_ATTRIBUTES_SORT'               => 'Attribute sortiert nach',
    'D3_EXTSEARCH_NAVI_ATTRIBUTES_SORT_POS'           => 'einstellbarer Attributsposition',
    'D3_EXTSEARCH_NAVI_ATTRIBUTES_SORT_TITLE'         => 'Attributstitel',
    'D3_EXTSEARCH_NAVI_ATTRIBUTES_SORT_DESC'          => 'Hier definieren Sie die Reihenfolge der angezeigten Attribute.',
    'D3_EXTSEARCH_NAVI_ATTRIBUTEVALUES_COMBINE'       => 'mehrfache Attributwertselektionen ("Mehrfachauswahl") werden mit "UND" verknüpft',
    'D3_EXTSEARCH_NAVI_ATTRIBUTEVALUES_COMBINE_DESC'  => 'Aktivieren Sie diese Option, wenn beispielsweise bei gewählter Farbe "rot" und "grün" nur Artikel gezeigt werden sollen, die beide Farben gleichzeitig haben. Ohne diese Option werden auch Artikel gezeigt, die nur eine der beiden Eigenschaften besitzen.',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_SORT'            => 'Attributswerte sortiert nach',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_SORT_COUNT'      => 'Anzahl der enthaltenen Artikel',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_SORT_POS'        => 'einstellbarer Attributslistenposition',
    'D3_EXTSEARCH_NAVI_ATTRIBUTELIST_SORT_DESC'       => 'Hier definieren Sie die Reihenfolge der angezeigten Attributwerte.<br><br>Die Attributlistenposition lässt sich in der Datenbank hinterlegen. Leider bietet der OXID-Shop im Standard keine Möglichkeit, diese Werte im Backend zu verändern.',
    'D3_EXTSEARCH_NAVI_NOATTRIBUTEARTS'               => 'auch nach nicht dem jeweiligen Attribut zugeordneten Artikeln filtern',
    'D3_EXTSEARCH_NAVI_NOATTRIBUTEARTS_DESC'          => 'Die Attributsfilter bieten mit dieser Option die Wahlmöglichkeit, auch nach Artikeln zu filtern, die z.B. ausdrücklich keiner Farbe oder keinem Material zugeordnet sind.',
    'D3_EXTSEARCH_NAVI_SHOWNOTSELECTABLEATTRIBUTES'   => 'nicht (sicher) wählbare Attributswerte werden nicht ausgeblendet',
    'D3_EXTSEARCH_NAVI_SHOWNOTSELECTABLEATTRIBUTES_DESC' => 'Bei der Artikelfilterung über Attribute werden andere, nicht sicher wählbare Attribute normalerweise ausgeblendet. Wenn gewünscht ist, dass der Shopbesucher seine Trefferliste mit zusätzlichen Attributswerten ergänzt, können diese angezeigt werden. Jedoch können dann ggf. ungültige Attributskombinationen gewählt werden, die zu keinem Treffer führen.<br>Beachten Sie, dass zur Ermittlung dieser Attribute eine zusätzliche Datenabfrage ausgeführt wird. Je nach Artikel-Attributs-Struktur kann dies zusätzliche Ladezeit benötigen. Die Anzeige der verfügbaren Artikel sollte dann deaktiviert werden, da die Werte zwar noch richtig, dann aber nicht mehr plausibel sind.',
    'D3_EXTSEARCH_NAVI_CONTENTSEARCHINLONGTEXT'       => 'in CMS-Texten auch Langtexte durchsuchen',
    'D3_EXTSEARCH_NAVI_CONTENTLONG_DESC'              => 'Soll neben dem Titel Ihres Textes auch der Inhalt durchsucht werden, aktivieren Sie diese Optionen. Beachten Sie, dass dies mehr Leistung erfordert.',
    'D3_EXTSEARCH_NAVI_SMALLLISTITEMS'                => 'Kategorie-, Lieferanten-, Marken- und Textlisten begrenzen<br>(Kunde kann alle Treffer auf Wunsch anzeigen, funktioniert nur bei "Linklisten")',
    'D3_EXTSEARCH_NAVI_SMALLLISTITEMS_2'              => ' Einträge',
    'D3_EXTSEARCH_NAVI_SMALLLISTITEMS_DESC'           => 'Bei vielen Suchtreffern kann auch die Kategorie-, Marken-, Lieferanten- und Textliste sehr lang werden. Die Artikeltreffer rutschen so vielleicht nach unten aus dem Anzeigebereich heraus. Beschränken Sie die Anzahl der angezeigten Kategorien und Marken, um diese Listen kurz zu halten. Werden diese Listen dann tatsächlich gekürzt, steht Ihrem Kunden eine Schaltfläche zur Verfügung, um diese Listen auf Wunsch komplett anzuzeigen.',
    'D3_EXTSEARCH_NAVI_ALISTFILTER'                   => 'Filter werden auch in Artikellisten gezeigt',
    'D3_EXTSEARCH_NAVI_ALISTFILTER_DESC'              => 'Auch Artikellisten können mit Filtern eingeschränkt werden. Filterungen sind in Kategorieansichten, Hersteller- und Lieferantenlisten möglich. Als Filter stehen die Einschränkungen über Kategorien, Hersteller, Lieferanten, Attribute oder Preise zur Verfügung. Als Optionen werden die Einstellungen für die Suche verwendet.<br>Ist dieser Eintrag nicht wählbar, ist diese Option wahrscheinlich in Ihrer Modullizenz nicht enthalten. Lassen Sie Ihre Lizenz hierfür erweitern.',
    'D3_EXTSEARCH_NAVI_PRICELIST'                     => 'zeige Preiskategorien',
    'D3_EXTSEARCH_NAVI_PRICEFILTER'                   => 'Preisfilter',
    'D3_EXTSEARCH_NAVI_PRICELIST_DESC'                => 'Alle gefundenen Artikel werden in Preiskategorien aufgeteilt und diese als weitere Filterkriterien angeboten. So kann der Kunde eine gewisse Preisspanne für seine gewünschten Artikel wählen. Rabatte sind in den Kategoriepreisen nicht berücksichtig. Gefundene Artikel sind in dem Fall preiswerter, als die Suchanfrage vorgibt.',
    'D3_EXTSEARCH_NAVI_PRICELIST_ITEMS'               => 'maximale Anzahl der Preiskategorien',
    'D3_EXTSEARCH_NAVI_PRICELIST_ITEMS_DESC'          => 'So viele Preisspannen werden maximal angezeigt. Im Normalfall kann dies jedoch weniger sein, da leere Preisspannen (also ohne enthaltene Artikel) ausgefiltert werden. (nur wirksam bei Darstellung als DropDown-Liste)',
    'D3_EXTSEARCH_NAVI_PRICELIST_ROUNDED'             => 'Preisspannen werden gerundet',
    'D3_EXTSEARCH_NAVI_PRICELIST_ROUNDED_DESC'        => 'Die kleinste Preisspanne beginnt beim kleinstmöglichen Preis, die größte Preisspanne erstreckt sich bis zum höchten Preis. Die Grenzen dazwischen werden errechet. Diese können unter Umständen jedoch bei krummen Cent-Beträgen liegen. Mit der Option werden die Preise der Spannen gerundet, die Spannen sind jedoch dann weniger aussagekräftig. (nur wirksam bei Darstellung als DropDown-Liste)',
    'D3_EXTSEARCH_NAVI_PRICELIST_DISPLAY'             => 'Anzeige der Preisspannen',
    'D3_EXTSEARCH_NAVI_PRICELIST_DISPLAY_DESC'        => 'Neben den schon gewohnten Dropdown- bzw. Linklisten können Sie für die Preisspannen auch Schieberegler verwenden. Das macht die Auswahl für Ihre Kunden intuitiver.',
    'D3_EXTSEARCH_NAVI_PRICELIST_DISPLAY_LISTTYPE'    => 'als Dropdown',
    'D3_EXTSEARCH_NAVI_PRICELIST_DISPLAY_SLIDER'      => 'als jQuery-Schieberegler',
    'D3_EXTSEARCH_NAVI_PRICELIST_REQU'                => '* jQuery-Schieberegler erfordert installiertes jQuery-Framework in aktueller Version (getestet mit Version 1.4.2) mit Komponenten "jQueryUI Core", "jQueryUI Widget", "jQueryUI Mouse" und "jQueryUI Slider".',
    'D3_EXTSEARCH_NAVI_HIGHLIGHT'                     => 'gefundene Textstellen werden in Suchergebnissen hervorgehoben',
    'D3_EXTSEARCH_NAVI_HIGHLIGHT_DESC'                => 'Manchmal taucht der gesuchte Begriff erst mitten in Beschreibungen auf. Mit dieser Option heben Sie den Begriff optisch hervor.<br><br>Stellen Sie dazu im Template \'d3_ext_search_highlight.tpl\' ein, wie die Hervorhebung aussehen soll. Ersetzen Sie dann in \'inc/product.tpl\' alle Variablen, die Hervorhebungen enthalten sollen, gegen den Smarty-Aufruf \[\{ d3_extsearch_highlight text=$variablenname \}\], wobei $variablenname gegen die tatsächliche Textvariable ersetzt wird.',
    'D3_EXTSEARCH_NAVI_DONTSHOWFILTERARTICLECOUNT'    => 'Anzahl zum Filter gefundener Artikel wird <b>nicht</b> angezeigt',
    'D3_EXTSEARCH_NAVI_DONTSHOWFILTERARTICLECOUNT_DESC'=> 'An den angebotenen Artikelfiltern wird die Anzahl der dazu passenden Artikel gezeigt. Wenn die Anzeige nicht gewünscht ist, kann diese hier deaktiviert werden.',
    'D3_EXTSEARCH_NAVI_INDEXFILTER'                   => 'Buchstabenindex',
    'D3_EXTSEARCH_NAVI_SHOWINDEX'                     => 'zeige Buchstabenindex',
    'D3_EXTSEARCH_NAVI_SHOWINDEX_DESC'                => 'Dieser Index sind kleine Tabs oberhalb der Trefferliste, mit denen Ihren Kunden die Artikel nach deren Anfangsbuchstaben selektieren können. Die Anzeige des Buchstabenindex kann über CSS und den beiliegenden Templates bearbeitet werden.',
    'D3_EXTSEARCH_NAVI_FILTERFIELDNAME'               => 'Feldname, nach dem gefiltert wird',
    'D3_EXTSEARCH_NAVI_FILTERFIELDNAME_DESC'          => 'An Hand dieses Feldnamens wird der Indexbuchstabe ermittelt und die Artikel bei Auswahl eines Buchstabens gefiltert. Möglich sind hier alle Felder aus der Tabelle oxarticles (ohne Sprachzusatz).',
    'D3_EXTSEARCH_NAVI_OWNFORMFIELDS'                 => 'individuelle Filter',
    'D3_EXTSEARCH_NAVI_SAVE'                          => 'Speichern',

    'D3_EXTSEARCH_QUICK'                              => 'Schnelltreffer',
    'D3_EXTSEARCH_QUICK_ACTIVE'                       => 'bei Eingabe des Suchbegriffs werden Vorschläge geliefert',
    'D3_EXTSEARCH_QUICK_ACTIVE_DESC'                  => '<img src="../modules/d3/extsearch/out/admin/img/d3_extsearch_quicksearch.jpg"><br>Geben Sie Ihrem Kunden die Möglichkeit, Artikel noch schneller zu finden. Die Schnellsuche stellt schon während der Eingabe des Suchbegriffs die ersten Treffer in einem eigenen Rahmen dar.<br>In mobilen Ansichten wird die Schnelltrefferliste aus Gründen der Bedienbarkeit nicht gezeigt.<br><br>Das Ergebnisfenster der Schnellsuche kann über CSS und Templateanpassungen individuell gestaltet werden.',
    'D3_EXTSEARCH_QUICK_FULLOBJECTS'                  => 'Schnellsuche lädt komplette Objekte, statt performanceoptimierter Zuweisung',
    'D3_EXTSEARCH_QUICK_FULLOBJECTS_DESC'             => 'Für die gewöhnliche Darstellung der Schnellsuche reicht eine performanceoptimierte Zuweisung der Ergebnisdaten. Für die Anzeige von bestimmten Informationen (z.B. berechnete Preise etc.) ist es erforderlich, die kompletten Objekte zu laden. Dies vermindert jedoch die Ladegeschwindigkeit.',
    'D3_EXTSEARCH_QUICK_COUNT'                        => 'maximale Anzahl der zu ladenden Artikel in der Schnellsuche',
    'D3_EXTSEARCH_QUICK_COUNT_DESC'                   => 'Aus Performancegründen werden die Schnellsuchtreffer nur bis zu dieser definierten Anzahl gezeigt. Werden mehr Treffer gefunden, blendet sich die Artikelliste nicht ein, statt dessen wird ein Hinweis gezeigt. Erhöhen Sie den Wert, wenn Sie für häufig vorkommende Suchbegriffe keine Schnelltreffer erhalten. Kontrollieren Sie aber bitte unbedingt danach die Last Ihres Servers / Accounts. Der Standardwert ist 200.',
    'D3_EXTSEARCH_QUICK_LOADCATEGORIES'               => 'zusätzlich auch nach entsprechend benannten Kategorien suchen',
    'D3_EXTSEARCH_QUICK_LOADCATEGORIES_DESC'          => 'Neben Artikeln werden in der Schnellsuche auch Kategorien gesucht. Beachten Sie bitte, dass diese Option zusätzliche Resourcen verbraucht, die die Schnellsuche langsamer werden lassen.',
    'D3_EXTSEARCH_QUICK_LOADMANUFACTURERS'            => 'zusätzlich auch nach entsprechend benannten Marken suchen',
    'D3_EXTSEARCH_QUICK_LOADMANUFACTURERS_DESC'       => 'Neben Artikeln werden in der Schnellsuche auch Marken gesucht. Beachten Sie bitte, dass diese Option zusätzliche Resourcen verbraucht, die die Schnellsuche langsamer werden lassen.',
    'D3_EXTSEARCH_QUICK_LOADVENDORS'                  => 'zusätzlich auch nach entsprechend benannten Lieferanten suchen',
    'D3_EXTSEARCH_QUICK_LOADVENDORS_DESC'             => 'Neben Artikeln werden in der Schnellsuche auch Lieferanten gesucht. Beachten Sie bitte, dass diese Option zusätzliche Resourcen verbraucht, die die Schnellsuche langsamer werden lassen.',
    'D3_EXTSEARCH_QUICK_LOADCONTENT'                  => 'zusätzlich auch nach entsprechend benannten Texten suchen',
    'D3_EXTSEARCH_QUICK_LOADCONTENT_DESC'             => 'Neben Artikeln werden in der Schnellsuche auch Texte gesucht. Beachten Sie bitte, dass diese Option zusätzliche Resourcen verbraucht, die die Schnellsuche langsamer werden lassen.<br><br>Für die Verwendung dieser Option ist es erforderlich, dass die Textsuche auch für die reguläre Trefferliste aktiviert ist (Tab "Grundeinstellungen").',
    'D3_EXTSEARCH_QUICK_CMPLOBJ'                      => 'vor Oxid 4.3.0: komplettes Artikel-Objekt laden, sonst nur ID, Titel und Icon.<br>Nur bei Bedarf aktivieren, verbraucht mehr Ressourcen. ',
    'D3_EXTSEARCH_QUICK_CMPLOBJ_DESC'                 => 'Die Darstellung der Schnelltreffer kann von Ihnen in einem Template grafisch an Ihren Shop angepaßt werden. Vielleicht benötigen Sie für Ihre gewünschte Darstellung noch weitere Daten außer dem Arikelnamen und dem Link zum Artikel. So lassen sich z.B. auch Miniaturbilder, der Preis oder auch gleich ein Warenkorbbutton einblenden. Dazu benötigen Sie jedoch Informationen, die so im Standard nicht verfügbar sind. Setzen Sie diesen Haken, um alle Artikeldaten verfügbar zu machen.<br><br>Ab Shopversion 4.3.0 ist es unbedingt notwendig, das komplette Artikelobjekt zu laden. Diese Einstellung wird dann ignoriert.',
    'D3_EXTSEARCH_QUICK_LOADVARIANTS'                 => 'Variantenartikel laden und in der Schnellsuche anzeigen<br>Tragen Sie dazu in den Suchfeldern zusätzlich \'oxvarselect\' ein.',
    'D3_EXTSEARCH_QUICK_LOADVARIANTS_DESC'            => 'Normalerweise sucht die Shopsuche nicht nach Artikelvarianten. Haben Sie jedoch viele Variantenartikel in Ihrem Shop, kann es sinnvoll sein, die Suche dafür freizuschalten.',
    'D3_EXTSEARCH_QUICK_SAVE'                         => 'Speichern',
    'D3_EXTSEARCH_QUICK_TPLNOTICE'                    => 'Hinweis: Um das Fenster der Schnellsuche grafisch anzupassen, erweitern Sie die Templateblöcke in \'d3_ext_search_suggestsearch.tpl\'.',
    'D3_EXTSEARCH_QUICK_IAS'                          => 'interaktive Suche (Markier-Suche)',
    'D3_EXTSEARCH_QUICK_SHOWIAS'                      => 'zeige interaktive Suche (Markier-Suche)',
    'D3_EXTSEARCH_QUICK_SHOWIAS_DESC'                 => 'Markieren Sie im Shop ein Wort, wird Ihnen in dessen Nähe ein kleines Formular eingeblendet, mit dessen Hilfe Sie sofort nach dem markierten Wort suchen können. Klicken Sie an eine andere Stelle im Shop, verschwindet das Fenster wieder.',

    'D3_EXTSEARCH_STAT_TYPE'                          => 'Auswertung:',
    'D3_EXTSEARCH_STAT_NOHITS'                        => 'keine Auswertungen vorhanden',
    'D3_EXTSEARCH_STAT_NOREPORTBASE'                  => 'Ihr Shop unterstützt diese Auswertungen leider nicht.',
    'D3_EXTSEARCH_STAT_NOREPORTBASE_DESC'             => 'Für die Verwendung der Statistik ist die OXID-Klasse "OeStatistics_Report_Base" erforderlich. Im OXID eShop wird dieses Script durch ein separat zu installierendes Modul "Statistiken" bereitgestellt. Daher kann die grafische Auswertung in Ihrem Shop ohne dessen Installation leider nicht genutzt werden.',
    'D3_EXTSEARCH_STAT_TYPEHITLESS'                   => 'Suchabfragen ohne Treffer',
    'D3_EXTSEARCH_STAT_TYPEMOSTHITS'                  => 'Suchabfragen mit den meisten Treffern',
    'D3_EXTSEARCH_STAT_TYPEMOSTSEARCHES'              => 'häufigste Suchbegriffe',
    'D3_EXTSEARCH_STAT_LANG'                          => 'Sprache:',
    'D3_EXTSEARCH_STAT_TIME'                          => 'Zeitraum:',
    'D3_EXTSEARCH_STAT_GENERATESTAT'                  => 'Auswertung erstellen',
    'D3_EXTSEARCH_STAT_SEARCHWORD'                    => 'Suchwort',
    'D3_EXTSEARCH_STAT_HITS'                          => 'Treffer',
    'D3_EXTSEARCH_STAT_SEARCHES'                      => 'Anfragen',
    'D3_EXTSEARCH_STAT_TYPES_CATEGORY'                => 'Kategorie',
    'D3_EXTSEARCH_STAT_TYPES_PRICE'                   => 'Preis',
    'D3_EXTSEARCH_STAT_TYPES_VENDOR'                  => 'Lieferant',
    'D3_EXTSEARCH_STAT_TYPES_MANUFACTURER'            => 'Marken',
    'D3_EXTSEARCH_STAT_TYPES_OWNLIKE'                 => 'eig. Suchfeld (LIKE)',
    'D3_EXTSEARCH_STAT_TYPES_OWNIS'                   => 'eig. Suchfeld (IS)',
    'D3_EXTSEARCH_STAT_TYPES_OWNVALUE'                => '%s => "%s"',
    'D3_EXTSEARCH_STAT_TYPES_ATTRIBUTE'               => 'Attribute',
    'D3_EXTSEARCH_STAT_TYPES_INDEXLETTER'             => 'Indexbuchstabe',
    'D3_EXTSEARCH_STAT_TYPES_UNKNOWN'                 => 'unbekannte Filterung',
    'D3_EXTSEARCH_STAT_STATDESC_HITLESS'              => 'ergebnislose Suchanfragen in %s nach "%s" ',
    'D3_EXTSEARCH_STAT_STATDESC_MOSTSEARCHES'         => 'Suchanfragen in %s nach "%s" ',
    'D3_EXTSEARCH_STAT_NOITEMS'                       => 'für die Einstellungen sind keine Einträge vorhanden',
    'D3_EXTSEARCH_STAT_NOITEMS_DESC'                  => 'Wenn Sie hier Daten erwartet haben, kontrollieren Sie bitte, ob die Statistikerfassung in den Moduleinstellungen passend aktiviert ist.',
    'D3_EXTSEARCH_STAT_SELECTFILTER'                  => 'Setzen Sie den gewünschten Filter und schicken Ihre Auswahl ab, um Ergebnisse zu erhalten.',

    'D3_EXTSEARCH_PLUGIN_SETTINGS'                    => 'Einstellungen',
    'D3_EXTSEARCH_PLUGIN_SEARCHACTIVE'                => 'dem Nutzer im Browser anbieten, das Such-Plugin zu installieren',
    'D3_EXTSEARCH_PLUGIN_SEARCHACTIVE_DESC'           => 'In aktuellen Browsern finden Sie im rechten oberen Eck eine Möglichkeit, von jeder beliebigen Stelle im Internet aus die wichtigsten Suchmaschinen zu starten. Bieten Sie Ihren Kunden an, auch Ihren Shop in diese Liste hinzuzufügen. So reicht es, in der Drop-Down-Box Ihren Shop auszuwählen und den Suchbegriff einzugeben. Sofort wird Ihr Shop mit den Suchtreffern gezeigt. Als Text wird Ihr Shoptitel verwendet, ein Icon können Sie weiter unten festlegen.',
    'D3_EXTSEARCH_PLUGIN_INSTALLLINK'                 => 'einen Installationslink in der Shop-Suche anzeigen',
    'D3_EXTSEARCH_PLUGIN_INSTALLLINK_DESC'            => 'Kann Ihr Kunden Ihren Shop in die Suchmaschinenliste hinzufügen, wird dies im Browser durch eine farbige Umrandung angezigt. Dies ist jedoch nur wenig auffällig, viele Nutzer übersehen dies. Stellen Sie in den Suchergebnissen besser noch einen zusätzlichen Link dar, um auf diese Funktion hinzuweisen.',
    'D3_EXTSEARCH_PLUGIN_SEARCHICON'                  => 'Icon für Browserplugin',
    'D3_EXTSEARCH_PLUGIN_CHOOSEICON'                  => 'Bitte wählen Sie noch ein Icon.',
    'D3_EXTSEARCH_PLUGIN_SEARCHICON_DESC'             => 'Legen Sie hier das Icon fest, welches im Browser-Plugin angezigt werden soll. Das Icon muß ein Größe von 16 x 16 Pixeln haben und im PNG- oder JPG-Format vorliegen.',
    'D3_EXTSEARCH_PLUGIN_SAVE'                        => 'Speichern',
    'D3_EXTSEARCH_PLUGIN_GENERATE'                    => 'Generierung',
    'D3_EXTSEARCH_PLUGIN_GENERATE_DESC'               => 'Haben Sie Ihren Shoptitel geändert, ein neues Icon festgelegt oder sogar Ihren Shop auf eine neue Adresse umgezogen, ist es nötig, das Suchplugin zu aktualisieren. Weisen Sie bitte auch Ihre Kunden darauf hin, das Plugin zu aktualisieren. Es erneuert sich nicht automatisch.',
    'D3_EXTSEARCH_PLUGIN_STARTGENERATING'             => 'Erstellung durchführen',
    'D3_EXTSEARCH_PLUGIN_GENERATEFILE'                => 'Installations-Datei erstellen:',
    'D3_EXTSEARCH_PLUGIN_GENERATENOTICE'              => 'Mit der Erstellung der Installations-Datei haben Sie alle erforderlichen Schritte durchgeführt. Startet Ihr Kunde die Integration, wird diese Datei automatisch von Ihrem Server ausgelesen.',
    'D3_EXTSEARCH_PLUGIN_CREATE_SUCC'                 => 'Plugindatei wurde erfolgreich generiert.',
    'D3_EXTSEARCH_PLUGIN_CREATE_NSUCC'                => 'Plugindatei konnte nicht erstellt werden.',

    'D3_EXTSEARCH REPORT_MOSTSEARCHES'                => 'Suchbegriffe (nur im Suchmodul verfgb.)',
    'D3_EXTSEARCH_STATISTIC_MOSTSEARCHES'             => 'häufigste Suchbegriffe',
    'D3_EXTSEARCH_STATISTIC_MOST_DESC'                => 'So oft wurde der gewählte Begriff gesucht',
    'D3_EXTSEARCH_STATISTIC_FURTHERFILTERS'           => '(durch weitere Filter eingeschränkt)',
    'D3_EXTSEARCH_STATISTIC_GRAPH'                    => 'grafische Auswertung',

    'D3_EXTSEARCH_CONTENT_SEARCHABLE'                 => '<img src="../modules/d3/modcfg/public/d3logo.php" alt="D³" title="D³ Data Development"> CMS kann gesucht werden',
    'D3_EXTSEARCH_PUSH'                               => '<img src="../modules/d3/modcfg/public/d3logo.php" alt="D³" title="D³ Data Development"> Wichtigkeit des Artikels im Sortiment',
    'D3_EXTSEARCH_PUSH_1'                             => 'normal',
    'D3_EXTSEARCH_PUSH_2'                             => 'wichtiger',
    'D3_EXTSEARCH_PUSH_3'                             => 'besonders wichtig',
    'D3_EXTSEARCH_PUSH_DESC'                          => 'D³ Modul "erweiterte Suche": Die Wichtigkeit definiert die erste Reihenfolge der Artikel in der Suche (bei Verwendung der "erweiterten Suche"). In Verbindung mit Feldrelevanz funktioniert die Wichtigkeit als Faktor. Besonders wichtige Artikel haben zum Beispiel die 3 fache Relevanz von normal gewichteten Artikeln. Beachten Sie dies auch bei der Vergabe der Feldrelevanz.',

    'D3_EXTSEARCH_ATTRIBUTE_NOTUSE4FILTER'            => 'Attribut für Filter NICHT verwenden',
    'D3_EXTSEARCH_ATTRIBUTE_NOTUSE4FILTER_DESC'       => 'Bestimmte Attribute können aus der Filterliste ausgeschlossen werden, wenn diese beispielsweise nur für die Artikelverwaltung genutzt werden.',
    'D3_EXTSEARCH_ATTRIBUTE_USECORRESPONDINGVALUES'   => 'fügt korrespondierende Attributwerte hinzu',
    'D3_EXTSEARCH_ATTRIBUTE_USECORRESPONDINGVALUES_DESC' => '<p>Wenn zum ausgewählten Attributswert Synonyme im Synonym-Editor gepflegt sind, werden diese zur Auswahl hinzugefügt, ohne dass der Kunde diese ausdrücklich wählen muss.</p><p>Dies ist zum Beispiel für sinngleiche oder sehr ähnliche Werte sinnvoll (z.B. Kleidungsgrößen im EU- und US-Format).</p>',
    'D3_EXTSEARCH_CATEGORY_NOTUSE4FILTER'             => 'Kategorie für Filter und Kategorieergebnisse NICHT verwenden',

    'D3_EXTSEARCH_SYNED_NOLEXICON'                    => 'Das semantische Lexikon ist nicht installiert! Weitere Informationen hierzu finden Sie im Modulhandbuch.',
    'D3_EXTSEARCH_SYNED_WORD'                         => 'Wort',
    'D3_EXTSEARCH_SYNED_WORD_DESC'                    => 'Suchen Sie nach einem bestimmten Begriff, geben Sie diesen hier ein und senden die Eingabe ab.',
    'D3_EXTSEARCH_SYNED_ALTWORD'                      => 'sinnähnliche Worte',
    'D3_EXTSEARCH_SYNED_SYNSETID'                     => 'Synonym-ID',
    'D3_EXTSEARCH_SYNED_SYNSETID_DESC'                => 'Suchen Sie nach einer bestimmten Synonym-ID, geben Sie diese hier ein und senden die Eingabe ab.',
    'D3_EXTSEARCH_SYNED_SAVENEWSYN'                   => 'neues Synonym speichern',
    'D3_EXTSEARCH_SYNED_SAVENEWSYN_DESC'              => 'Legen Sie hier einen weiteren Begriff für die gewählte Bedeutung ab.',
    'D3_EXTSEARCH_SYNED_DELETESYN'                    => 'Soll das Synonym wirklich gelöscht werden?',

    'D3_EXTSEARCH_SYNED_MAIN_NEWWORD'                 => 'Neues Wort / Wortgruppe',

    'D3_EXTSEARCH_SYNED_MAIN_WORD'                    => 'Wort / Wortgruppe:',
    'D3_EXTSEARCH_SYNED_MAIN_WORD_DESC'               => 'Möchten Sie für eine neue Wortbedeutung passende Begriffe anlegen, notieren Sie hier den ersten Begriff. Fügen Sie den Begriff hier nur ein, wenn die Wortbedeutung noch nicht im Lexikon existiert. Ansonsten tragen Sie den neuen Begriff in der passenden Bedeutung im Tab "Synonyme bearbeiten" nach.',
    'D3_EXTSEARCH_SYNED_MAIN_COMMENT'                 => 'Kommentar:',
    'D3_EXTSEARCH_SYNED_MAIN_COMMENT_DESC'            => 'Der Kommentar dient ausschließlich dazu, weitere interne Erklärungen zum Begriff ablegen zu können. Er wird für die Suche nicht verwendet.',
    'D3_EXTSEARCH_SYNED_MAIN_SYNSETID'                => 'Synonym-ID:',
    'D3_EXTSEARCH_SYNED_MAIN_SYNSETID_DESC'           => 'Unter einer einheitlichen Synonym-ID werden alle Begriffe mit gleicher Bedeutung abgelegt. Bei Neueinträgen wird automatisch eine neue ID vergeben. Wurde ein Begriff versehentlich der falschen Bedeutung zugewiesen, suchen Sie sich aus der passenden Bedeutung die Synonym-Id und ändern diese an Ihrem Begriff.',
    'D3_EXTSEARCH_SYNED_MAIN_LANGUAGE'                => 'Sprache:',
    'D3_EXTSEARCH_SYNED_MAIN_LANGUAGE_DESC'           => 'Bestimmen Sie hieran, aus welcher Sprache der ausgewählte Begriff stammt und in welcher dieser verwendet werden soll. Es stehen nur die im Shop aktivierten Sprachen zur Verfügung.',
    'D3_EXTSEARCH_SYNED_MAIN_LANGUAGE_DISABLED'       => '(deaktiviert)',
    'D3_EXTSEARCH_SYNED_MAIN_SYNONYMUSE'              => 'Synonym wird genutzt für',
    'D3_EXTSEARCH_SYNED_MAIN_SYNONYMUSEFORTERMS'      => 'Ergänzung der Suchbegriffe',
    'D3_EXTSEARCH_SYNED_MAIN_SYNONYMUSEFORTERMS_DESC' => 'Sofern die Synonymverwendung in den Modulgrundeinstellungen aktiviert ist, wird dieses Synonym verwendet, wenn der Shopbesucher nach einem der anderen zugeordneten Begriffen sucht. So lassen sich z.B. regionale Begriffe suchbar machen, ohne diese an allen Artikeln zu pflegen.',
    'D3_EXTSEARCH_SYNED_MAIN_SYNONYMUSEFORATTRIBUTES' => 'korrespondierende Attributwerte',
    'D3_EXTSEARCH_SYNED_MAIN_SYNONYMUSEFORATTRIBUTES_DESC' => 'Sind für einzelne Attribute korrespondierende Werte aktiviert, wird dieses Synonym zusätzlich verwendet, wenn nach einem der anderen zugeordneten Begriffe gefiltert wird. So lassen sich z.B. landesabhängige Kleidungsgrößen übergreifend suchen.',

    'D3_EXTSEARCH_SYNED_MANAGE_DESC'                  => 'Die hier gezeigten Synonyme sind alternative Begriffe für die oben gewählte Bedeutung.',
    'D3_EXTSEARCH_SYNED_MANAGE_EDIT'                  => 'bearbeiten',
    'D3_EXTSEARCH_SYNED_MANAGE_EDIT_DESC'             => 'Möchten Sie zusätzliche Details zu dem Begriff hinterlegen oder diesen einer anderen Bedeutung zuordnen, klicken Sie auf das Symbol. Der Adminbereich wechselt zum Bearbeitungsbereich für genau den Begriff.',
    'D3_EXTSEARCH_SYNED_MANAGE_SYNONYM'               => 'Synonym',

    'D3_EXTSEARCH_SETTINGS'                           => 'Einstellungen für <img src="../modules/d3/modcfg/public/d3logo.php" alt="D3" title="D3 Data Development"> erweiterte Suche',
    'D3_EXTSEARCH_SETTINGS_DESC'                      => 'Verwendung erfordert aktiviertes Modul',
    'tbclattribute_extsearch'                         => 'Such- und Filtereinstellungen',
    'D3_EXTSEARCH_ASSIGNCATEGORIES'                   => 'filterbare Kategorien zuordnen',
    'D3_EXTSEARCH_ASSIGNCATEGORIES_DESC'              => 'Soll das gewählte Attribut nur an bestimmten Kategorien zur Filterung gezeigt werden, ordnen Sie diese Kategorien hier zu. Ohne eine Zuordnung wird das Attribut an allen Kategorien zur Filterung verwendet, in denen entsprechende Artikel verfügbar sind.<br><br>Die Zuordnung wirkt nur, wenn das Attribut nicht grundsätzlich von der Verwendung als Filter ausgeschlossen ist (Artikel verwalten -> Attribute -> Such- und Filtereinstellungen -> Attribut wird in Ergebnislisten für Filter NICHT verwendet) und die Verwendung dieser individuellen Zuordnung in den Modulgrundeinstellungen aktiviert wurde (D3 Module -> Erweiterte Suche -> Einstellungen -> Filter + Anzeige -> Attributfilter -> verwende Attributsaktivierung pro Kategorie, Hersteller und Lieferant).',
    'D3_EXTSEARCH_ASSIGNMANUFACTURERS'                => 'filterbare Marken zuordnen',
    'D3_EXTSEARCH_ASSIGNMANUFACTURERS_DESC'           => 'Soll das gewählte Attribut nur an bestimmten Marken zur Filterung gezeigt werden, ordnen Sie diese Marken hier zu. Ohne eine Zuordnung wird das Attribut an allen Marken zur Filterung verwendet, in denen entsprechende Artikel verfügbar sind.<br><br>Die Zuordnung wirkt nur, wenn das Attribut nicht grundsätzlich von der Verwendung als Filter ausgeschlossen ist (Artikel verwalten -> Attribute -> Such- und Filtereinstellungen -> Attribut wird in Ergebnislisten für Filter NICHT verwendet) und die Verwendung dieser individuellen Zuordnung in den Modulgrundeinstellungen aktiviert wurde (D3 Module -> Erweiterte Suche -> Einstellungen -> Filter + Anzeige -> Attributfilter -> verwende Attributsaktivierung pro Kategorie, Hersteller und Lieferant).',
    'D3_EXTSEARCH_ASSIGNVENDORS'                      => 'filterbare Lieferanten zuordnen',
    'D3_EXTSEARCH_ASSIGNVENDORS_DESC'                 => 'Soll das gewählte Attribut nur an bestimmten Herstellern zur Filterung gezeigt werden, ordnen Sie diese Lieferanten hier zu. Ohne eine Zuordnung wird das Attribut an allen Lieferanten zur Filterung verwendet, in denen entsprechende Artikel verfügbar sind.<br><br>Die Zuordnung wirkt nur, wenn das Attribut nicht grundsätzlich von der Verwendung als Filter ausgeschlossen ist (Artikel verwalten -> Attribute -> Such- und Filtereinstellungen -> Attribut wird in Ergebnislisten für Filter NICHT verwendet) und die Verwendung dieser individuellen Zuordnung in den Modulgrundeinstellungen aktiviert wurde (D3 Module -> Erweiterte Suche -> Einstellungen -> Filter + Anzeige -> Attributfilter -> verwende Attributsaktivierung pro Kategorie, Hersteller und Lieferant).',
    'tbclcategory_extsearch'                          => 'Such- und Filtereinstellungen',
    'D3_EXTSEARCH_AJAX_ALLCATEGORIES'                 => 'Alle Kategorien',
    'D3_EXTSEARCH_AJAX_SETCATEGORIES'                 => 'Zugeordnete Kategorien',
    'D3_EXTSEARCH_AJAX_ALLMANUFACTURERS'              => 'Alle Marken',
    'D3_EXTSEARCH_AJAX_SETMANUFACTURERS'              => 'Zugeordnete Marken',
    'D3_EXTSEARCH_AJAX_ALLVENDORS'                    => 'Alle Lieferanten',
    'D3_EXTSEARCH_AJAX_SETVENDORS'                    => 'Zugeordnete Lieferanten',

    'GENERAL_AJAX_SORT_D3NOTUSE4FILTER'               => 'nicht für Filter verwendbar',
    'GENERAL_AJAX_SORT_OXSHORTDESC'                   => 'Kurzbeschreibung',

    'D3_EXTSEARCH_UPDATE_GENPHONETIC'                 => '"erweiterte Suche": Das Modulupdate führte Änderungen in der Datenbankstruktur für die Ähnlichkeitssuche aus. Aktualisieren Sie deshalb nach Abschluss dieser Installation den Suchindex im Adminbereich des Moduls.',

    'GENERAL_ARTICLE_D3_PHONETIC'                     => 'erwSuche - phonetischer Index', // Multilang-Fields for importer
    'GENERAL_ARTICLE_D3_SEARCHINDEXDATE'              => 'erwSuche - Datum letzte Indizierung', // Multilang-Fields for importer
    'GENERAL_ARTICLE_D3PUSH'                          => 'erwSuche - Artikelwichtigkeit', // Multilang-Fields for importer
    'GENERAL_ARTICLE_D3CONTENTHASH'                   => 'extSearch - Hash der indizierten Inhalte', // Multilang-Fields for importer
    'GENERAL_ARTICLE_OXVARSELECT'                     => 'Variantentitel',

    'D3_EXTSEARCH_CLI_COMMON_RUNFROMCLI'              => 'Dieses Script muss von der Befehlszeile aus ausgeführt werden. / This script has to be run from the command line',
    'D3_EXTSEARCH_CLI_COMMON_UNVALIDSHOPID'           => 'ungültige Shop-ID',
    'D3_EXTSEARCH_CLI_COMMON_NOGENERATORSCRIPT'       => 'Keine Generierungssprache definiert, setzen Sie diese bitte in den Einstellungen des Moduls.',
    'D3_EXTSEARCH_CLI_HELP'                           => 'Ermöglicht automatisierte Aufgaben  / Wartung des Moduls "erweiterte Suche".',
    'D3_EXTSEARCH_CLI_OPTION_VERSION'                 => 'zeigt Version',
    'D3_EXTSEARCH_CLI_OPTION_QUIET'                   => 'verhindert die Anzeige der Ausgabe',
    'D3_EXTSEARCH_CLI_OPTION_LANG'                    => 'optional - Sprache der ausgegebenen Meldungen, mögliche Werte sind: "%1$s"',
    'D3_EXTSEARCH_CLI_OPTION_HELP'                    => 'Diesen Hilfetext anzeigen und den Aufruf verlassen.',
    'D3_EXTSEARCH_CLI_OPTION_NOCOLORS'                => 'Verwendet keine Farben in der Ausgabe. Nützlich bei der Weitergabe der Ausgabe an andere Tools oder Dateien.',
    'D3_EXTSEARCH_CLI_OPTION_LOGLEVELS'               => 'Kleinstes Level der anzuzeigenden Meldungen. Standard ist "info". Gültige Stufen sind: "debug", "info", "notice", "success", "warning", "error", "critical", "alert", "emergency".',
    'D3_EXTSEARCH_CLI_COMMAND'                        => 'Dieses Tool akzeptiert einen Befehl als ersten Parameter, wie unten beschrieben:',
    'D3_EXTSEARCH_CLI_COMMAND_GENERATEINDEX'          => 'phonetischen Suchindex aktualisieren',
    'D3_EXTSEARCH_CLI_COMMAND_GENERATESEMANTIC'       => 'Lexikon für sinngleiche Suche neu indizieren',
    'D3_EXTSEARCH_CLI_COMMAND_FIXARTEXTENDS'          => 'Langtexttabelle bereinigen',
    'D3_EXTSEARCH_CLI_ARGUMENT_SHOPID'                => 'ID des ausgewählten Shops, mögliche Werte sind: "%1$s"',
    'D3_EXTSEARCH_CLI_ARGUMENT_ENCLOSER'              => '", "',
    'D3_EXTSEARCH_CLI_GENERATOR_PROCESSING'           => 'Verarbeitung gestartet ...',
    'D3_EXTSEARCH_CLI_GENERATOR_PROCESSED'            => '%1$s Artikelsprachen (ca. %2$s Artikel) bearbeitet - Generierung abgeschlossen!',
    'D3_EXTSEARCH_CLI_GENERATOR_TERMPROCESSED'        => '%1$s Wort/Wörter bearbeitet - Generierung abgeschlossen!',
    'D3_EXTSEARCH_CLI_FINISHED_SUCCFESSFULLY'         => 'Das Script wurde erfolgreich beendet.',

);
